### ISSUE TITLE
50hz and 150hz telemetry causing bad connection on master

### ISSUE THREAD

**Issue by P-I-Engineer** [ExpressLRS/ExpressLRS#1010]
## Current Behavior
only happening on PP, tested on EP1, no issue

150hz, telem at 1/32 = bad connection
change to telem off = good connection
change back to 1/32 tele = good connection
power cycle rx = bad connection

50hz, nothing works

## Details
issue not happening on 250hz

issue not happening on 1.1 either

[150hz bad connection.txt](https://github.com/ExpressLRS/ExpressLRS/files/7384410/150hz.bad.connection.txt)

## Your Environment

- TX hardware: diy e28
- RX hardware: PP
- Handset model: x9 lite s
- OpenTX version 2.3.14
- ExpressLRS version (TX & RX MUST MATCH): ff3215
- Packet Rate: 150
- Telemetry Ratio:1/32
- user_defines:
 -DRegulatory_Domain_ISM_2400
-DUART_INVERTED
-DLOCK_ON_FIRST_CONNECTION
-DDEBUG_LOG
-DDEBUG_RX_SCOREBOARD
-DDEBUG_CRSF_NO_OUTPUT

**Comment by P-I-Engineer** [comment]
i'm not seeing this issue any longer

**Comment by CapnBry** [comment]
Thanks for checking back in and confirming!
