### ISSUE TITLE
Update UI still shows Rev. 1.0 after updating to 1.2

### ISSUE THREAD

**Issue by knoopx** [ExpressLRS/ExpressLRS#1015]
## Current Behavior

Update UI still shows Rev. 1.0 after updating to 1.2

![image](https://user-images.githubusercontent.com/100993/138352722-0361c64f-e225-4c73-9e11-eda4d7851e25.png)

## Steps to Reproduce

* Update to 1.2

## Your Environment

- TX hardware: HM jumper t-lite tx
- RX hardware: HM EP2
- ExpressLRS version (TX & RX MUST MATCH): 1.2

**Comment by CapnBry** [comment]
Closing via 1.2.1
