### ISSUE TITLE
TX selects wrong ModelID after using Wifi/BLE mode

### ISSUE THREAD

**Issue by CapnBry** [ExpressLRS/ExpressLRS#1022]
## Current Behavior

After going into Wifi / BLE joystick mode via Lua, exiting this mode (which reboots the module) reverts the TX to model 0's configuration.

## Steps to Reproduce

1. Create at least two different model configurations using the ModelID in OpenTX. Use different packet rates to be able to distinguish them.

2. From the model that is NOT modelid=0, enter Wifi mode or BLE joystick mode using the Lua

3. Exit this mode, the TX module reboots to resume normal operation, but ModelID 0 is selected, which uses the wrong model config in ELRS. If the user then resets their settings to how they want then, this is actually changing modelid 0's settings.

## Possible Solution

Is this resolved in the newest EdgeTX / OpenTX nightly? I'm know the behavior has been modified but I am not sure if the new behavior anticipates that the TX will forget the ModelID. 

Possible solution if not worked around upstream: Store the modelid in RTC RAM and restore it after reboot?

## Your Environment

- TX hardware: Any
- RX hardware: None needed
- Handset model: Taranis Q X7 / Mambo
- OpenTX version (including nightly number): 2.3.14
- ExpressLRS version (TX & RX MUST MATCH): master 2021-10-24 
- Packet Rate: Any
- Telemetry Ratio: Any
- user_defines: 
```
-DMY_BINDING_PHRASE="frog a damp gear"
-DRegulatory_Domain_ISM_2400
-DUSE_DIVERSITY
-DUNLOCK_HIGHER_POWER
```

**Comment by pkendall64** [comment]
> Thanks for the expertise! I thought that maybe if we had gone disconnected for a while maybe it would send the ModelID when packets started coming again. I didn't think that's the case but I didn't know the extent of the fix. Seems like we need to hang on to that ModelID across the reboot then, since there's no mechanism for it to be sent again from the handset.

Yeah, we can save the modelId in the RTC ram and on reboot default it to that.
