### ISSUE TITLE
Lua cmd struct member missing

### ISSUE THREAD

**Issue by xtr0d3m0n** [ExpressLRS/ExpressLRS#1066]
## Current Behavior

Error while compiling Lua files

## Steps to Reproduce

Compile Master Branch with VERBOS BEBUG enabled

this log macro tries to access a missing struct member on cmd
DBGVLN("sending response for [%s] chunk=%u step=%u", cmd->name, nextStatusChunk, cmd->step);

In file included from lib/LUA/lua.cpp:5:0:
lib/LUA/lua.cpp: In function 'void pushResponseChunk(luaItem_command*)':
lib/LUA/lua.cpp:155:61: error: 'struct luaItem_command' has no member named 'name'
   DBGVLN("sending response for [%s] chunk=%u step=%u", cmd->name, nextStatusChunk, cmd->step);
                                                             ^
lib/logging/logging.h:47:26: note: in definition of macro 'DBGLN'
       debugPrintf(msg, ##__VA_ARGS__); \
                          ^
lib/LUA/lua.cpp:155:3: note: in expansion of macro 'DBGVLN'
   DBGVLN("sending response for [%s] chunk=%u step=%u", cmd->name, nextStatusChunk, cmd->step);
   ^
*** [.pio\build\EXPRESS_TX\lib461\LUA\lua.cpp.o] Error 1
1.

2.

3.

4.

## Possible Solution (Not obligatory)

remove the struct access, Not sure if the cmd ->name is needed, Was this struct member got removed by a mistake ?

## Your Environment

Windows

- TX hardware:
- RX hardware:
- Handset model:
- OpenTX version (including nightly number)
- ExpressLRS version (TX & RX MUST MATCH):
- Packet Rate:
- Telemetry Ratio:
- user_defines:

**Comment by xtr0d3m0n** [comment]
It seems like there is no mention of name anywhere else. Seems like it was left there by mistake. Should I just remove it at commit a fix to master?

**Comment by pkendall64** [comment]
Yes it's definitely leftover from some earlier refactoring work

**Comment by xtr0d3m0n** [comment]
https://github.com/ExpressLRS/ExpressLRS/pull/1070
Fixed on this pr can somebody review?
