### ISSUE TITLE
OLED Telem Ratio Not Updated

### ISSUE THREAD

**Issue by brandonrc** [ExpressLRS/ExpressLRS#1083]
## Current Behavior

When you update the telemetry ration in the lua script the display shows the wrong value. 

All the other fields seem to change. 

## Steps to Reproduce

1. Turn on the TX from a fresh state. 

2. Look at the telemetry ratio on the OLED

3. Use the lua script to change that telemetry ratio

4. Look at the telemetry ratio on the OLED :( 

## Your Environment

Tested on ghost TX and betaFPV tx. 
Plugged into a horus x10s express and x7 taranis.

**Comment by CapnBry** [comment]
Fixed via #1084
