### ISSUE TITLE
build fails with "(" in HOME_WIFI_PASSWORD

### ISSUE THREAD

**Issue by jonas-ott** [ExpressLRS/ExpressLRS#1095]
## Current Behavior
Build of  2.0.0-RC1 fails if there's an `(` in `HOME_WIFI_PASSWORD`, with following error in the Configurator:
``sh: -c: line 1: syntax error near unexpected token `(' sh: -c: line 1: `xtensa-esp32-elf-g++ -o ".pio/build/HappyModel_ES24TX_2400_TX_via_WIFI/src/common.cpp.o"`` ...

[configurator-log.txt](https://github.com/ExpressLRS/ExpressLRS/files/7522583/configurator-log.txt)

## Steps to Reproduce

In ELRS Configurator:

1. Select 2.0.0-RC1

2. Enable HOME_WIFi

3. Use a wifi password with an `(` in it

4. Build

## Possible Solution (Not obligatory)

pkendall64 suggested on Discord to replace `(` with `\\\\050`, it fixed the issue

## Your Environment

- TX hardware: HM ES24TX
- ExpressLRS version (TX & RX MUST MATCH): 2.0.0-RC1
- OS: Manjaro Linux
- Configurator Version: v.1.2.3

**Comment by pkendall64** [comment]
Added bug report to configurator https://github.com/ExpressLRS/ExpressLRS-Configurator/issues/130

**Comment by JyeSmith** [comment]
@jonas-ott if you are comfortable testing PRs would you like to see if this is working for you. https://github.com/ExpressLRS/ExpressLRS/pull/1101

**Comment by jonas-ott** [comment]
Yes, it builds and connects to my WiFi network.

**Comment by CapnBry** [comment]
Closing since OP says resolved, re-open if that is not the case.
