### ISSUE TITLE
Telemetry lost during dynamic power test 2.0.0 RC2

### ISSUE THREAD

**Issue by unluckyfrog** [ExpressLRS/ExpressLRS#1111]
Elrs 2.0.0 -RC2
Edge tx 2.5.0 (28cbd40e) TX16s
Happy model 2.4 tx, EP1 rx.

250hz Paket rate
1:4 telemetry
TX Power dynamic on. Max 250mw

So I thought I'd try out the dynamic power setting on a flight today. Was working great, then for some reason I got a telemetry lost message and it got stuck on 10mw. I kept flying, as  Inav osd said I had 100LQ and ~85db. Telemetry reconnected after about 5 minutes, but lost connection soon after. 

I'm using a Baud rate of 1.87k.

Wasn't sure whether to bring this up in elrs or edgetx github. Apologies if this is the wrong group.

**Comment by SunjunKim** [comment]
Do you set AUX1 as the arm switch, and set "high" as an arming?
With RC2 code it's expected to jump up to the max power when telemetry is lost.

**Comment by unluckyfrog** [comment]
Yes Aux 1 is arm switch.  
hmmm that's embarrassing, I have arming set as low. I did't check this ><.
THX

**Comment by SunjunKim** [comment]
It's not uncommon to have telemetry lost, as downlink is much weaker than uplink on EP1.
If you often encounter challenging situations, consider upgrading your RX to one has PA/LNA.
https://www.expresslrs.org/2.0/hardware/receiver-selection/

**Comment by avsaase** [comment]
> Yes Aux 1 is arm switch. Arming on low, not high though. Didn't think that matters. Can change though.

Yes, this is important for dynamic power to work correctly. When you lose telemetry it will increase power to the max configured level, but only when the arming channel is in the high position. This is to avoid blasting at full power when switching batteries.

**Comment by unluckyfrog** [comment]
**avsaase** "This is to avoid blasting at full power when switching batteries" 

Ahhh that makes sense, very clever. 
Thanks

**Comment by unluckyfrog** [comment]
**Sunjunkim** "consider upgrading your RX to one has PA/LNA"
Done and ordered. Thanks for the advice.

**Comment by AerialClone** [comment]
I have the arming in low and I made the set up long ago and I can't remember how to change it to high... anyone can help?

**Comment by jurgelenas** [comment]
> I have the arming in low and I made the set up long ago and I can't remember how to change it to high... anyone can help?

It is configured through OpenTX/EdgeTX. Go to model settings -> Mixes tab and set CH5 (AUX1) weight to -100. Do not forget to update betaflight arming as well. Something like this: 

![A053D9C7-DA99-4A07-8E01-E3D46A9DCEC9](https://user-images.githubusercontent.com/1081265/147565522-c6dbfa72-7ab4-4037-b33c-3aac00d84afa.jpeg)

For the future: it is unlikely to get answers for questions like this in GitHub issues. Please use ExpressLRS discord help and support channel :) there are lots of smart people willing to help you.

**Comment by Vittaly** [comment]
Hi All!
> With RC2 code it's expected to jump up to the max power when telemetry is lost.
I have FC with ArduPilot and arming is makes through throttle stick. 5th channel is using for other function. Is it mean thet I can not use function "dynamic power"?
