### ISSUE TITLE
FrSky R9 TX communication problem [2.0.0-RC3]

### ISSUE THREAD

**Issue by RomkaV** [ExpressLRS/ExpressLRS#1141]
After upgrading from version 1.2 to 2.0.0-RC3, it is not possible to configure FrsSky P9. Settings are not saved.

[Steps to Reproduce](https://youtu.be/2nc4--IKlLA)

Transmitter: Taranis QX7 ACCT, EdgeTX 2.5.0
TX Module: FrsKy R9M

![1638124226261](https://user-images.githubusercontent.com/5110901/143781531-8dfe93fa-7b3b-4444-9fda-0ee33a2b8e5c.jpg)

**Comment by CapnBry** [comment]
I believe this should be fixed by the latest 2.0.x-maintenance branch and when 2.0.0-RC4 comes out.
https://github.com/ExpressLRS/ExpressLRS/pull/1133

Can you try using Branch -> 2.0.x-maintenance in the configurator to verify? Only the TX needs to be flashed.

**Comment by hyperion11** [comment]
use R9M 2019 with OpenTX 2.3.14 2.0.0-RC3. All settings saved except WideChannels.

**Comment by CapnBry** [comment]
> use R9M 2019 with OpenTX 2.3.14 2.0.0-RC3. All settings saved except WideChannels.

Great!

You can't change switch mode with a receiver connected, that's be design.

**Comment by RomkaV** [comment]
Thanks! Solved!
