### ISSUE TITLE
BetaFPV RX disconnected when starting LUA script (2.0)

### ISSUE THREAD

**Issue by blind-oracle** [ExpressLRS/ExpressLRS#1170]
Radiomaster TX16S / OpenTX 2.3.14
TX: HappyModel ES24TX
RX1: Matek 2.4 Diversity
RX2: Matek 2.4 Diversity
RX3: BetaFPV 2.4

I've flashed 2.0 to all of the above, update to 2.0 LUA.

Matek RXs work flawlessly. But when using BetaFPV RX it works fine only until I start LUA - then immediately RX is disconnected (telemetry lost and no channel updates on the FC).

RX reboot does not help to restore communication - I have to reboot the radio and then the connection is reestablished.
Tried re-flashing RX, no change.

Video: https://tube.novg.net/w/9vRMGm6FwoR2yKfeMn5nKn

UPDATE2:
RX works fine with -RC4 version. Does not work with 2.0 release.

UPDATE:
RX goes into reboot with an exception, was able to catch it using serial passthrough:
```
Exception (29):
epc1=0x402166dc epc2=0x00000000 epc3=0x00000000 excvaddr=0x06630000 depc=0x00000000

>>>stack>>>

ctx: cont
sp: 3ffffba0 end: 3fffffc0 offset: 0190
3ffffd30:  3ffef4d4 3ffef868 000010e9 40100a75  
3ffffd40:  3ffffd32 e9ea0028 3ffffd50 401013cc <
3ffffd50:  00000001 2804ee01 3fe9ea00 ffffffff  
3ffffd60:  00000004 00008002 3ffef868 ffffffff  
3ffffd70:  00000004 00008002 3ffef868 40100db0  
3ffffd80:  00000004 00008002 3ffef868 40100f7e  
3ffffd90:  00000000 3ffef4b0 3ffef8b0 40100fbd  
3ffffda0:  00e007be 00000001 00000000 40100fdd  
3ffffdb0:  40101f42 3ffef4b0 00000093 40101fd4  
3ffffdc0:  40038235 00000020 3ffef868 40100db0  
3ffffdd0:  00000004 00008002 3ffef868 00000022  
3ffffde0:  00000063 00000064 3ffef4fc 00000022  
3ffffdf0:  3fffc200 40101f08 3fffc258 4000050c  
3ffffe00:  4000dd2b 00000030 00000010 ffffffff  
3ffffe10:  4000066d 84a120a0 013353e6 0000040e  
3ffffe20:  00004bc6 84a120a0 00000000 fffffffe  
3ffffe30:  00001712 3fffc6fc 2d3d20a0 040e44f6  
3ffffe40:  4bc6a7f0 3fffdad0 3fffff70 00000030  
3ffffe50:  00000bd0 3fffc6fc 3fffc248 4000050c  
3ffffe60:  402049af 00000030 00000010 ffffffff  
3ffffe70:  40201907 00000000 3fffff74 3fffff70  
3ffffe80:  3ffe8764 00000004 00000008 3ffef594  
3ffffe90:  00000001 3ffe8744 00000004 00000001  
3ffffea0:  3ffe85d8 00000000 ffffffff 00000030  
3ffffeb0:  3ffef594 3ffefea4 3fffff70 00000030  
3ffffec0:  00000000 00000004 00000008 3ffef594  
3ffffed0:  00000000 3ffe8744 00000004 3ffeffc0  
3ffffee0:  00000000 4bc6a7f0 020c49ba 013344da  
3ffffef0:  00000000 00000000 4bc6a7f0 00000000  
3fffff00:  00000000 3fffdad0 40101dd5 00000000  
3fffff10:  040e44f6 4bc6a7f0 3fffdad0 3fffff70  
3fffff20:  040e44f6 00000000 4bc6a7f0 00000000  
3fffff30:  000109bf 00000002 40101da6 00000000  
3fffff40:  040e44f6 00000002 3ffefb24 402025e1  
3fffff50:  140cc80e 3ffef594 000109cc 3fffff70  
3fffff60:  3fffdad0 00000000 3ffeffc0 40201651  
3fffff70:  00000000 3ffe8500 3ffef868 4020251d  
3fffff80:  00000000 00000000 00000001 40101b90  
3fffff90:  3fffdad0 00000000 3ffeffc0 3ffeffd4  
3fffffa0:  3fffdad0 00000000 3ffeffc0 402077d4  
3fffffb0:  feefeffe feefeffe 3ffe8794 40102c8d  
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

ExpressLRS Module Booting...
Setting 2400MHz Mode
2000
0
$6666

--------------- CUT HERE FOR EXCEPTION DECODER ---------------
...
```

So until I reboot the TX it does cyclic reboots infinitely.

**Comment by deadbytefpv** [comment]
I just tried the same setup (only difference is that I'm using EdgeTX 2.5.0 on the Tx16s and a HM ES24TX Pro)

Powered up module. Then the kwad with the BetaFPV Nano 2.4G. Connection established.
Went into ExpressLRS Lua script.. Connection is still intact.
Change a bunch of settings (Packet rate, Telem Ratio, Tx Power). Connection Stays.

**Comment by pitts-mo** [comment]
I had found this behavior repeatable using opentx 2.3.14 and the 2.0.0 RCx biulds w/250hz,1/16 or 1/32 telem, wide switches,  dynamic power... confirmed on issue on betafpv and matek. i had suspected it was related to telemitry somehow but it does occur on both inav and betaflight. i do not remember this occuring on my builds w/ happymodel rx. I will retest all my builds with 2.0.0 release in the next couple days and report results. -p

**Comment by pitts-mo** [comment]
Sorry, i jumbled the dwtail. I was thibking of lua freakout. But i do recall betafpv rx having odd behavior after attempting to set model match.... somehow the rx did stabalize and accept model match. I will still report updated findongs. -p

**Comment by blind-oracle** [comment]
I've disabled model matching both in TX (set to Off) and on RX (set to 255 on the web GUI). No change.

Strange thing is that the connection is lost when running some other LUA scripts from TOOLS.
E.g. if I start `Betaflight Config` -> bang, telemetry lost, reboot radio.

Will investigate more.

@deadbytefpv Well maybe the fact that you use the Pro TX makes the difference as I think this is some OpenTX + TX module problem...

**Comment by deadbytefpv** [comment]
@blind-oracle Pro or non-pro shouldn't really matter much.. same hardware/pin mapping.. pro just have some extra pins in use for the PA..

**Comment by blind-oracle** [comment]
@deadbytefpv I agree - it shouldn't.
And Matek/BetaFPV shouldn't matter either. But it does for some reason...

Just flashed a plane with Matek 24D - also works like a charm. I have another BetaFPV RX lying around, maybe will test on it.

**Comment by pitts-mo** [comment]
Ok, please disregard most of my other comments here.
I do not ever recall my BetaFPV RX loosing connection on entry into luaV2.

In case this ends up being related:
Today, I updated to 2.0.0 final release.
I cycled model match OFF then ON with a BetaFPV RX a couple times. It takes maybe 5-10 seconds to catch hold but did not seem to become stuck like I had seen it do before. It still recall spending ~15 minutes on my first BetaFPV binding/model match attempts where it appeared to be stuck partially bound. Maybe the partially bound issue I saw was related to a change in binding or on attempts to set model match ON after a change of model ID? 

Additionally the luaV2 "freakout" I was originally focused on appeared as cyclic lua page refresh after only partial data display and is repeatable in 2.0.0 final release. I still suspect the cause is related to telemetry data and it occurs with all of my receivers (BetaFPV, Matek, HappyModel).

**Comment by pitts-mo** [comment]
My betaflight setup lua (betaflight config) does not appear to run correctly for me. But testing this and other crossfire  and elrs lua versions do not seem to be killing my RX links on my happymodel/Betafpv betaflight builds.

Something with the build the betafpv RX is connect to?

**Comment by blind-oracle** [comment]
Update: tried different settings (same as Matek and others) of Hz/Power/Telemetry ratio etc. Nothing helps.

Here's the video of the process: https://tube.novg.net/w/9vRMGm6FwoR2yKfeMn5nKn

**Comment by blind-oracle** [comment]
Update: RX reboots infinitely, see topic for an exception.

**Comment by blind-oracle** [comment]
Update2: Works fine with -RC4

**Comment by blind-oracle** [comment]
I've rebuilt 2.0 in VSCode from maintenance branch - it started to work fine.
Then I've cleaned `.platformio` folder to reset the environment - it started to work also when building from Configurator...

I guess that's my mistake, sorry for disturbance.
Why it worked on Mateks and with RC4 though remains unknown.

**Comment by blind-oracle** [comment]
Oops, I guess I'm too early. After cleaning up the environment and reflashing everything from scratch - I have the same behaviour on the Matek receiver...

**Comment by brandonrc** [comment]
@blind-oracle is this only with betaFPV rx's? 

Have you tried different TX's or you just have the one?

**Comment by blind-oracle** [comment]
@brandonrc Like I said in the last message - that happened also with Matek 24D.

But it looks like that the problem is connected to the build environment - though I've removed `|/.platformio` on my Windows PC - it still produced buggy/unstable(?) binaries, though I don't know what causes this.

Then I switched to MacOS with VSCode and built `2.0.x-maintenance` branch there for all my devices (Matek/HappyModel/BetaFPV) - it works flawlessly everywhere now.

So I guess the cause is not the code, but some PlatformIO inconsistencies... Hard to say what exactly.

**Comment by pkendall64** [comment]
If you can get it to crash again, having the stack trace and the .elf file is the only way we can decode the trace to find out where the problem is.

**Comment by blind-oracle** [comment]
@pkendall64 Ok, will try. The stack trace like in the initial message is enough? Or do I need to build with some debug defines?
And ELF - just the RX firmware image is enough?

**Comment by pkendall64** [comment]
The .elf file,`firmware.elf`, should be next to the .bin file. That contains all the information about the names of the classes and functions that the trace decoder uses to turn the big glob of hex into a human readable stack trace. If you are using configurator, you may have to search your filesystem for the file.

**Comment by blind-oracle** [comment]
@pkendall64 Got it, binary with debug info. Will try to repro.

**Comment by blind-oracle** [comment]
@pkendall64 Sad, cannot reproduce it anymore. I guess after cleaning the `.platformio` folder I've altered the environment too much. Gonna close this now, will reopen if I'll have a repro.

**Comment by pkendall64** [comment]
Ok, thanks for trying.
