### ISSUE TITLE
HappyModel EP 2400 RX [Enable RX WiFi] doesn't work (2.0)

### ISSUE THREAD

**Issue by taraskornuta** [ExpressLRS/ExpressLRS#1175]
## Current Behavior

I try to enable the wifi on Rx via Lua script command, but nothing happened.  
Try to scan wifi ap's by Android phone and Windows 10 + WiFi dongle
With Tx works fine
## Steps to Reproduce

1. Open ExpressLRS 2.0 Lua 

2. Go to "WiFi Connectivity"

3. Chouse and press "Enable Rx WiFi"

## Your Environment

- TX hardware: HappyModel ES24TX 2400 TX
- RX hardware: HappyModel EP 2400 RX
- Handset model: Jumper T16
- OpenTX version 2.3.11
- ExpressLRS version (TX & RX MUST MATCH): 2.0
- Packet Rate: 250
- Telemetry Ratio: 1:32
- user_defines:
build flags: ['-D PLATFORM_ESP32=1', '-D CONFIG_TCPIP_LWIP=1', '-D BEARSSL_SSL_BASIC', '-DTARGET_TX=1 -Wall -Iinclude', '-DRADIO_2400=1', '-include target/HappyModel_ES24TX_2400_TX.h', '-D VTABLES_IN_FLASH=1', '-O2', '-DMY_BINDING_PHRASE="112233"', '-DMY_UID=141,178,139,235,143,2', '-DFEATURE_OPENTX_SYNC', '-DUART_INVERTED', '-DAUTO_WIFI_ON_INTERVAL="20"', '-DFAST_SYNC', '-DLATEST_COMMIT=53,99,52,56,48,56', '-DLATEST_VERSION=50,46,48,46,48', '-DTARGET_NAME=HAPPYMODEL_ES24TX_2400_TX']

build flags: ['-D PLATFORM_ESP8266=1', '-D VTABLES_IN_FLASH=1', '-D PIO_FRAMEWORK_ARDUINO_MMU_CACHE16_IRAM48', '-D CONFIG_TCPIP_LWIP=1', '-D BEARSSL_SSL_BASIC', '-O2', '-DTARGET_RX=1 -Wall -Iinclude', '-DRADIO_2400=1', '-include target/DIY_2400_RX_ESP8285_SX1280.h', '-DMY_BINDING_PHRASE="112233"', '-DMY_UID=141,178,139,235,143,2', '-DLOCK_ON_FIRST_CONNECTION', '-DAUTO_WIFI_ON_INTERVAL="20"', '-DFAST_SYNC', '-DLATEST_COMMIT=53,99,52,56,48,56', '-DLATEST_VERSION=50,46,48,46,48', '-DTARGET_NAME=HAPPYMODEL_EP_2400_RX']

**Comment by pkendall64** [comment]
Please as on discord, in the help-and-support channel.
