### ISSUE TITLE
Compatibility. Happymodel ExpressLRS module ES900TX  and Frsky R9MM/Mini

### ISSUE THREAD

**Issue by al1965al** [ExpressLRS/ExpressLRS#1196]
Compatibility. 
Happymodel ExpressLRS module ES900TX and Frsky R9MM/Mini (915).
Will this bundle work together?
(Or for compatibility, I need to use receiver only from Happymodel ??  )
Will telemetry be transmitted?
In other words.
Are all ExpressLrs products (receivers & transmitters)  compatible?
Thanks

**Comment by avsaase** [comment]
Yes, all ExpressLRS that runs on the same frequency is compatible. 868 and 915Mhz hardware is also compatible but the antennas made for one frequency may not be good for the other.

https://www.expresslrs.org/2.0/faq/#will-x-receiver-work-with-y-tx-module-from-z-manufacturer

**Comment by CapnBry** [comment]
Yes I test using this exact combination all the time (Frsky R9 Mini-OTA 915MHz ACCESS)
