### ISSUE TITLE
The "select file" button doesn't work when automatically redirecting to 10.0.0.1 after connecting to wifi

### ISSUE THREAD

**Issue by ikherty** [ExpressLRS/ExpressLRS#1197]
When you connect to Wi-Fi ExpressLRS, you are automatically redirected to http://10.0.0.1. All buttons are available, but nothing happens when you try to click on the "select file" button. If I close the page and manually enter the in the browser 10.0.0.1, everything works fine.

The error is reproduced on google pixel 3 and xiaomi mi 8.

- ExpressLRS version (TX & RX MUST MATCH): all versions

**Comment by pkendall64** [comment]
This is a "security" feature of some phones when in captive portal mode. Theres nothing we can do about it as far as I know.
