### ISSUE TITLE
Concern with bind phrase

### ISSUE THREAD

**Issue by brandonrc** [ExpressLRS/ExpressLRS#1203]
# Issue
A few people on JB's live chat asked about issue with bind phrases. What happens if someone uses your phrase and connects to your drone before you do. Or what happens if someone uses the same phrase.. can they take over control or cause failsafes? 

## Discussion
Around the 40min markish
https://www.youtube.com/watch?v=z-BgE34tc58

## Solution? 
Just like we have lock on packet rate on first connection, should we try a lock on tx with first connection. Not sure what unique identifier we could use on the TX? Is this even something we could do? 

Someone else brought up maybe only using that bind phrase for the first lock then it would not use it anymore. I am not sure I like that idea because it would make it hard to have multiple TX's right? 

### Should we add a lock a lock on first TX to the RX's? 

*Instead of commenting "I want this too", consider leaving a :+1: instead, to reduce spam and clutter*

**Comment by brandonrc** [comment]
After speaking with a few people, looks like this issue is very unlikely to cause issues. 

1. You have to have 6 consecutive packets for BF to disarm. 
2. You have to have the same bindphrase
3. The TX does not start in sync, so 'most' of the time they don't collide

Maybe if companies ship with a default bind phrase, then we might have some issues.

**Comment by brandonrc** [comment]
Closing this until a company makes a bad decision with shipping all systems with default bind phrase.

**Comment by avsaase** [comment]
One thing I like about ExpressLRS is that I can switch radios in-flight. Making this change would make that impossible. 

The documentation is also pretty clear on setting a unique bind phrase. Since it is not a secret you can just use your name and birth date, that should rule out any collision.

**Comment by brandonrc** [comment]
> One thing I like about ExpressLRS is that I can switch radios in-flight. Making this change would make that impossible.
> 
> The documentation is also pretty clear on setting a unique bind phrase. Since it is not a secret you can just use your name and birth date, that should rule out any collision.

Agreed. I do not think this is a big enough issue considering @JyeSmith and @AlessandroAU have flown together with the same phrase with little to no issues. 

I would also think lock on first connection could be a default option that one could turn off like our packet rate. 

Still do not think it is worth the dev effort for this edge case, unless a company really messes up.. but then we could just tell users to flash a unique bind phrase and solve that.
