### ISSUE TITLE
Over the air updates from tx module to rx

### ISSUE THREAD

**Issue by karl03** [ExpressLRS/ExpressLRS#1204]
I'm not sure how difficult this would be to add, or how much demand there is for it, but one feature others still have over expresslrs is the ability to update rxs from the tx module directly.

Maybe it would be possible to include precompiled firmwares for all RX's with the tx firmware, which you can then flash from the lua? Though there might not be enough space in the tx modules.

An easier approach might be just adding a flash option to the lua where you select a file from the radio SD card to flash.

Again, I'm not sure how difficult this is to implement or how much demand there is for it but I think it would be quite useful.

*Instead of commenting "I want this too", consider leaving a :+1: instead, to reduce spam and clutter*

**Comment by pkendall64** [comment]
We've had this discussion multiple times on Discord and a github issue is not the right place to start this type of discussion.
It is impractical to build all the RX firmwares into the TX as they are too large. You would have to go the route of copying them to the SD Card. The other problem is that the user has to build the firmware themselves as there are many options that each user sets as personal preferences e.g. binding phrase, startup melody etc. So the user would have to build it, copy to SD Card, then flash to RX. It was deemed easier to just flash the firmware directly at that point.
