### ISSUE TITLE
Free RST pin for PWM

### ISSUE THREAD

**Issue by JyeSmith** [ExpressLRS/ExpressLRS#1219]
Something is like to eventually test, or anyone else can jump in.

The sx1276 RST pin isn't connected on the DIY receivers, so it isn't required and the gpio can be reused.  7th PWM?

RST on the sx1280 is connected, but we could call a SPI command to reset the transceiver of required.  Testing needed.  This might free the gpio for a 6th PWM.

**Comment by maybenikhil** [comment]
Now in 2.1!
