### ISSUE TITLE
Failure to flash a R9MX with INAV passthrough

### ISSUE THREAD

**Issue by OlivierC-FR** [ExpressLRS/ExpressLRS#1224]
- RX hardware: Frsky R9MX
- OpenTX version (including nightly number) : 2.3.14
- ExpressLRS version (TX & RX MUST MATCH): 2.0.1
- FC : Matek F722-SE INAV 3.0.2

R9MX is with its correct ELRS bootloader, but then the flashing fails, going through a Matek F722-SE running INAV 3.0.2
I tried to check the box at the bottom (UART_RECV SPD something don't recall the exact name) to 400000, 115200 and 57600, didn't seem to make any difference)

Screenshot 1, 2 and 3 below are if I don't push the receiver button before plugging the USB cable, and screenshot 4 is when the RX button is pushed prior powering. The R9MX shows blinking red/green as expected.
Before that I managed to successfully flash an identical R9MX, through a Matek F405-WSE, also running INAV 3.0.2, but it took like maybe 20 attempts, maybe had a lucky one, I don't know.

Both FC powers the whole stack when plugged to USB, so if I try to reboot the RX during the process (+ RX button pressed), it ends it all, since it cuts the com port. And I get same results if I manually repower the RX + button, right after the passthrough is tested.

Inversion and half-duplex for the port are off, the protocol is set to CRSF in INAV, wiring and port number are correct and triple checked.

Will try to flash Betaflight later tonight to see if it's a workaround or not.

UPDATE : Flashed Betaflight latest version, flashing work fine at the first attempt, so the issue is definately with INAV.

![Capture d’écran 2021-12-28 182137](https://user-images.githubusercontent.com/25566932/147595118-430dca9e-62a5-4942-b0b8-856c0e8ca985.png)

![Capture d’écran 2021-12-28 183111](https://user-images.githubusercontent.com/25566932/147594571-64cb0212-38d0-4a6a-8349-45aa8256237b.png)

![Capture d’écran 2021-12-28 183129](https://user-images.githubusercontent.com/25566932/147594577-b19d4734-1654-47a9-9855-23adad624ccc.png)

![Capture d’écran 2021-12-28 183340](https://user-images.githubusercontent.com/25566932/147594586-699c1ec8-4822-4518-b8b9-664d41720238.png)

**Comment by Dropsleutel** [comment]
I can remember I had the same issue with I nav. Strangely it only worked when set to Auto.....
I made a screenshot at the time, only set as such pass true flash it worked; 

![Flash ELRS True Flight Controller Inav](https://user-images.githubusercontent.com/42233240/147814805-becd625b-649f-4371-83ff-161ae334892c.JPG)

**Comment by OlivierC-FR** [comment]
Thanks, I will try with auto, I have few more receivers to flash

**Comment by pkendall64** [comment]
@OlivierC-FR Did you get this working, can we close this issue?

**Comment by OlivierC-FR** [comment]
> @OlivierC-FR Did you get this working, can we close this issue?

Can be closed I guess, over 4 R9MX receivers, I managed to flash only 1 using INAV, by sheer luck and after trying like 20 times. 2 others I flashed at the first attempt with Betaflight, and the last one never wanted to be flashed for whatever reason. So I guess it's an issue with INAV passthrough.

**Comment by bill-zb** [comment]
HI, I have exactly the same issue as OliverC-FR in almost the same environment:
RX hardware: Frsky R9Slim+ OTA
OpenTX version : 2.3.14
ExpressLRS version: 2.1
FC : Matek F722-WING INAV 3.0.1

I'm not even including the screenshot, because they are identical as in the Oliver's issue #1224. 
Is there something specific in Inav, that prevents successful flashing? Yesterday I flashed 2 quads with BF4.3 and R9MM without a hiccup...

**Comment by bill-zb** [comment]
Just to not leave this issue unnecessarily open - I fixed it by flashing bootloader 0.5.3, as proposed in the issue #1256. So for me, this one can be closed.
