### ISSUE TITLE
Add the commit SHA to the WiFi SSID

### ISSUE THREAD

**Issue by skorokithakis** [ExpressLRS/ExpressLRS#1234]
Would it be a good idea to add the first few letters of the commit hash to the WiFi SSID, so we knew which receivers are up to date and which are not? Might make flashing multiple receivers easier.

**Comment by AlessandroAU** [comment]
It's not a bad idea, but I just wanted to point out that if you use the home wifi feature the RX will pop up in the configurator with all the details: 
![image](https://user-images.githubusercontent.com/22009829/149346126-97c025c9-227e-467e-acfa-ce82c47b4ec2.png)

**Comment by skorokithakis** [comment]
Ahh, I haven't tried the latest version, I will, thank you!
