### ISSUE TITLE
Lost "good" packets when refreshing Lua on some STM32

### ISSUE THREAD

**Issue by CapnBry** [ExpressLRS/ExpressLRS#1276]
## Current Behavior

When refreshing Lua, the bad/good number goes down, e.g. from 0/250 to 0/246. This is apparently only present on FM30 STM32 TXes which worked perfectly on 2.0.1.

## Steps to Reproduce

1. Install master (2022-Jan-13)

2. Go into Lua

3. Watch as the bad/good number dips as the Lua loads

## Possible Solution (Not obligatory)

This starts happening with 7f25cd837e5249e3d7046cf47be5cafa2fe168a7 STM32 platform upgrade (#1169), the previous commit is fine.

## Details

There's no CRC errors reported from our debugging, and no errors reported from the OpenTX debug log side either. The platform was updated from ststm32@8.0.0 to ststm32@15.1.0 so there's a lot that could be wrong here.

* R9M apparently works fine (same STM32F103)
* Ghost apparently works fine (different STM32)

## Your Environment

- TX hardware: SIYI FM30
- RX hardware: None
- Handset model: Taranis Q X7 ACCST
- OpenTX version: 2.3.14 (115200 and 400000)
- ExpressLRS version (TX & RX MUST MATCH): master as of today
- Packet Rate: any except 50Hz
- Telemetry Ratio: doesn't matter
- user_defines: defaults + `DEBUG_LOG`

**Comment by zandorsp** [comment]
Is this related to my case?
[https://youtube.com/shorts/3WoXJ2juR-E?feature=share](url)

I'm using a Siyi FM30 TX with ELRS 2.4.0 on Flysky NV14 with EdgeTX 2.7.0

**Comment by pkendall64** [comment]
Is this still a problem on your Siyi @CapnBry ?

**Comment by CapnBry** [comment]
> Is this still a problem on your Siyi @CapnBry ?

I'll check and see when I have a chance to put together a test tomorrow

**Comment by zandorsp** [comment]
I tested today a SIYI FM30 TX (master 82f623) module on a RadioMaster Boxer (EdgeTX 2.8.2) and I see 2 things:
- The max functional baud rate is 921k
- Even on this or lower baud rate the status error counter keep raising, as same way of the video I send before (I don't have NV14 radio anymore)

**Comment by pkendall64** [comment]
Marked as closing as no one seems that bothered by it and STM probably have a limited life span.
