### ISSUE TITLE
jitter at high power with R9M

### ISSUE THREAD

**Issue by dataema92** [ExpressLRS/ExpressLRS#1283]
from 250mw and up there is more and more noise that generates a lot of jitter on gimbal channel.

- TX hardware: R9M 2019
- RX hardware: R9MM
- ExpressLRS version (TX & RX MUST MATCH): 2.0.1 (tried also other versions with the same result)

**Comment by Sekilsgs2** [comment]
> from 250mw and up there is more and more noise that generates a lot of jitter on gimbal channel.
> 
> * TX hardware: R9M 2019
> * RX hardware: R9MM
> * ExpressLRS version (TX & RX MUST MATCH): 2.0.1 (tried also other versions with the same result)

Why you think that this is ELRS problem?? Noise generate your transmitter (taranis, jumper , radiomaster ...) - high power affects the readings of the gimbal sensors - because of cheap equipment - what transmitter you using?

**Comment by dataema92** [comment]
Thank you. My transmitter is a taranis qx7. If I revert back to the original R9 firmware all is correct. As soon as I flash ELRS the noise start on all channels in specific in channel 4. Can you help me?

**Comment by Sekilsgs2** [comment]
> Thank you. My transmitter is a taranis qx7. If I revert back to the original R9 firmware all is correct. 

This is strange - i'm using r9m 2019 and tbs mambo - dont have this problems...

**Comment by brandonrc** [comment]
@dataema92 could you try and swap antennas? See if the jitter changes?

**Comment by brandonrc** [comment]
I am removing bug label for now, if you can test with a different antenna please let me know the results. 

Thanks.

**Comment by AlessandroAU** [comment]
I'm 99% sure this is RF interference from a poorly balance antenna. Open up the radio, unplug the gimbal wires and put a few twists the cable assembly and reassemble.

**Comment by dataema92** [comment]
unfortunately i don't have a second antenna for the transmitter to try. if i revert back to stock R9 firmware the problem vanish. if it is a problem with the antenna, why on the stock firmware the problem is not present?
Thank you very much to all.

**Comment by WinD52** [comment]
I can confirm this issue.  I have the same problem on my R9M and Taranis QX7 Access.  The higher the R9M power, the greater the amplitude of the control bounces.  At a power of 1W, the bounce is + - 30us.  According to your advice, instead of the super8 antenna from frsky, I tried the antenna from happymodel es900, but nothing has changed dramatically.  I discovered this problem a long time ago, it was present on version 1.0 of ELRS.  Sorry for my English.

**Comment by WinD52** [comment]
The shielding of the high-frequency module board helped me a little.  I glued the inside of the module with aluminum tape and connected it to ground.  This helped reduce the bounce to 15-20us at 1W, and 5-10us at 250mW.  In Inav, I raised the insensitive threshold to these values.

**Comment by dataema92** [comment]
I also tried to put a few more twist on cables without succes.
