### ISSUE TITLE
CRSF and PWM on same RX

### ISSUE THREAD

**Issue by MacDaddyFPV** [ExpressLRS/ExpressLRS#1290]
I have a PDB which I have designed with onboard MCU to do canvas mode OSD for HDZERO in a wing with a PWM RX. Problem is I can't send stick commands as there is no through connection from RX to VTX.

I would like if there could be the ability on a 5ch RX to set 2 channels to CRSF (TX/RX) and the remaining 3 to stay PWM. This would allow me to connect to the MCU (which is flashed with bf) to enable stick commands to be directed through MSP.

*Instead of commenting "I want this too", consider leaving a :+1: instead, to reduce spam and clutter*

**Comment by CapnBry** [comment]
I'm looking into this, it certainly is doable but requires some internal changes. I'm just trying to work out how it will be accessible because I don't want to create a whole new target for it.

**Comment by danxdz** [comment]
How about one option from webui? Like in debug mode, serial keeps working..
