### ISSUE TITLE
No connection on 2.1

### ISSUE THREAD

**Issue by nightwolfix** [ExpressLRS/ExpressLRS#1306]
I am having issues with HMES24TX and EP receivers when using 2.1 on all of them:
-2.1 TX does not connect with 2.1 RX. RX light blinks slowly but does not go into wifi mode when TX is on. Goes into wifi when TX is off
-2.1 TX binds with 2.0 RX no issues

This is happening on all three receivers

**Comment by AlessandroAU** [comment]
Are you saying they work on 2.0 and not 2.1?

**Comment by pitts-mo** [comment]
Hi @nightwolfix 
My first though is the partially bound / model match behavior. Have you tried cycling the model match ON OFF state from LUA? I think the LUA may also provides some status indication that this is occurring.

**Comment by kongzheng333** [comment]
Uncheck HOME_WIFI options then have a try.

**Comment by nightwolfix** [comment]
> Uncheck HOME_WIFI options then have a try.

Home wifi has always been off

**Comment by nightwolfix** [comment]
> Hi @nightwolfix My first thought is the partially bound / model match behavior. Have you tried cycling the model match ON OFF state from LUA? I think the LUA may also provide some status indication that this is occurring.

Tried to cycle on or off and also deactivating model match, still blinking slowly

**Comment by Witchdoctor2015** [comment]
Had a similar issue with the happy model ep2 rx.  In 2.1.0 I could flash the rx and it would enter bind mode when a tx was powered on but it would never bind.  going to 2.0.1 allowed the rx to bind.
