### ISSUE TITLE
NamimnoRC FLASH 2400 OLED TX module wifi does not appear when using the OLED or LUA when enabling wifi update

### ISSUE THREAD

**Issue by Witchdoctor2015** [ExpressLRS/ExpressLRS#1316]
I was attempting to change the bind phrase by flashing the module via the modules wi-fi but I could not get it to show up at all and eventually just used UART connection to flash.

## Your Environment

- TX hardware: NamimnoRC FLASH 2400 OLED TX
- RX hardware: NA
- Handset model: TBS MAMBO
- FreedomTX version TBS-1.3.0
- ExpressLRS version (TX & RX MUST MATCH):
- Packet Rate: 250
- Telemetry Ratio: 1:128
- user_defines:

**Comment by pkendall64** [comment]
Did you as on discord in the #help-and-support channel. Some devs have Namimno modules and these are tested prior to release.
You don't say if you were connecting to the hotspot or home network either, could it be that it connected to your home network and you expected it to create a hotspot or vice-versa?

**Comment by piwi3910** [comment]
have the same module, no issues, 
i do have the same problem with the backpack.
When enabling it, it goes back to the main menu without activating it.
However the TX module just worked, as i just flashed 2.1 on it via wifi.
