### ISSUE TITLE
R9MX shows linked but no telemetry signal

### ISSUE THREAD

**Issue by Manakoy** [ExpressLRS/ExpressLRS#1318]
## Current Behavior
TX : Frsky TX R9M LITE PRO
RX : R9MX
ELRS version : 2.1.0

The LED of R9MX shows normal link (red and yellow LEDs are always on), but the remote control does not show that it is linked. When the power of the remote control is turned off, the yellow light of the R9MX turns off and the red light flashes.
![1](https://user-images.githubusercontent.com/46884853/150678015-2da31122-99eb-4e9b-ae12-d8aebfe6f9e7.jpg)
![2](https://user-images.githubusercontent.com/46884853/150678022-dd47fe6c-913f-4d0a-a694-0c43cdf8b353.jpg)

## Steps to Reproduce

1.Disable read protection through [STM32 ST-LINK Utility] software

2.Flashing Bootloader through [STM32 ST-LINK Utility] software
![image](https://user-images.githubusercontent.com/46884853/150678268-2ac7731d-db28-41c2-a944-7c717dd59bfe.png)

3.Flash the bin file produced by ExpressLRS Configurator into 0x08008000 of R9MX through the [STM32 ST-LINK Utility] software
![image](https://user-images.githubusercontent.com/46884853/150678405-53c89715-bbd1-45e2-beb4-a72e7e713d70.png)
![image](https://user-images.githubusercontent.com/46884853/150678312-753d233e-ca5b-4866-9a80-4525ead202fc.png)

## Your Environment

- TX hardware: Frsky TX R9M LITE PRO
- RX hardware: R9MX
- Handset model: Frsky x-lite
- OpenTX version (including nightly number) : 2.3.9
- ExpressLRS version (TX & RX MUST MATCH): 2.1
- Packet Rate: 200
- Telemetry Ratio: 1:64

**Comment by deadbytefpv** [comment]
1. OpenTX is 2.3.9 when the earliest recommended is 2.3.12
2. you don't seem to have the latest ExpressLRS Configurator because "Enable Telemetry" is no longer needed for 2.x (as it was always enabled on the firmware)

**Comment by Manakoy** [comment]
@deadbytefpv 
1. I'm not sure if it's because of the opentx version, I'll try to upgrade to the latest version and test again
2. ExpressLRS Configurator version is 1.3.3, which is indeed the latest

**Comment by deadbytefpv** [comment]
![R9_Options2 1_02](https://user-images.githubusercontent.com/83231715/150679510-04dbe994-e474-41f4-9e24-38ef7444948b.jpg)
If you have the latest ExpressLRS Configurator and is indeed flashing 2.1, why is it our options are very different for these devices?

**Comment by Manakoy** [comment]
Probably due to I am building from a local file. 
![image](https://user-images.githubusercontent.com/46884853/150679824-dde40f9d-4fcf-4dbd-b372-289a5543f94c.png)

**Comment by deadbytefpv** [comment]
Use Manual Mode on Device Options
```
-DRegulatory_Domain_FCC_915
-DMY_BINDING_PHRASE="201361"
-DLOCK_ON_FIRST_CONNECTION
```

Also make sure TLM Ratio is not OFF via Lua Script.

**Comment by Manakoy** [comment]
Tried, nothing changed. Very strange.
![image](https://user-images.githubusercontent.com/46884853/150680529-e9af92ed-603d-4b1f-a160-b1e9361ebfd8.png)
![微信图片_20220123212251](https://user-images.githubusercontent.com/46884853/150680589-150cec52-3fa6-4eb3-8e05-4cb468536a53.jpg)

**Comment by deadbytefpv** [comment]
See how the packet counter is saying you have 0/250 bad-good packets, when your max packet should only be 200 (for 900 system)?

CRSFShot isn't working...

Do you have any other R9 receivers to test?

**Comment by Manakoy** [comment]
I use R9MM for testing and it links fine and receives telemetry data. But it still shows 0/250.
![1](https://user-images.githubusercontent.com/46884853/150681293-25b1d0e4-c5e8-44d3-a20a-440f134e628f.jpg)
![2](https://user-images.githubusercontent.com/46884853/150681302-f9831c13-0732-4126-9384-bb9f200d09de.jpg)
![3](https://user-images.githubusercontent.com/46884853/150681312-1e5abdf8-11b6-4543-b2dd-a911c67ac193.jpg)

**Comment by Manakoy** [comment]
I used another 2.4G TX to test the problem still exists, I think this is the reason for the low version of opentx.
![11](https://user-images.githubusercontent.com/46884853/150681594-fd55bdfd-8555-437f-8aa8-2efc6a5e2b8a.jpg)
![12](https://user-images.githubusercontent.com/46884853/150681595-62022fcf-ff1b-44a8-8975-6818d1633637.jpg)

**Comment by deadbytefpv** [comment]
With all these "working" setups, you're still using the 2.3.9 OpenTX version.. hence CRSFShot isn't working.. 

Refer to this page again for setting up your radio.
https://www.expresslrs.org/2.0/quick-start/transmitters/tx-prep/

**Comment by deadbytefpv** [comment]
This is my r9mx that I haven't used for a while. Flashed it via STLink to 2.1 just today for this.
![r9mx-bind-01](https://user-images.githubusercontent.com/83231715/150689877-337c31ce-4a9a-4a15-9b17-0488e85a0749.jpg)
![r9mx-bind-03](https://user-images.githubusercontent.com/83231715/150689888-e3e86ca3-d0d4-4ef0-a833-1adcec6d9896.jpg)
![r9mx-bind-02](https://user-images.githubusercontent.com/83231715/150689882-3780e282-8523-4c45-b0a6-9ce65306b964.jpg)
as you can see from the `C` on the lua script, it was connected.. 

and getting telemetry data:
![screen-2022-01-24-004019](https://user-images.githubusercontent.com/83231715/150690188-ecae5752-8cc0-435f-ab93-f7fbfbccba73.jpg)

**Comment by Manakoy** [comment]
I just updated to opentx2.3.14, and the phenomenon has changed.
The lua script can display 0/200 normally. After I try to bind, the remote control is connected to the R9MX, but it is quickly disconnected, and then it is connected again and then quickly disconnected, and it keeps looping.
In the telemetry data interface, i can see that several frames of data are received at intervals

**Comment by deadbytefpv** [comment]
> I just updated to opentx2.3.14, and the phenomenon has changed. The lua script can display 0/200 normally. After I try to bind, the remote control is connected to the R9MX, but it is quickly disconnected, and then it is connected again and then quickly disconnected, and it keeps looping. In the telemetry data interface, i can see that several frames of data are received at intervals

Is this r9mx new-ish? 
When you say "disconnected and connected again", is it the "Telemetry Lost/Recovered" loops?
Does the Lua script top-right corner loses the "C" during these loops?

And at this point, we're shifting into a different issue altogether, I recon? no longer about Telemetry?

**Comment by Manakoy** [comment]
It's not a new R9MX, but I'm pretty sure it worked before ELRS was flashed.
Yes, is the "Telemetry Lost/Recovered" loops.
"C" is never displayed in the upper right corner of the lua script, but "-"

**Comment by bladan83** [comment]
> It's not a new R9MX, but I'm pretty sure it worked before ELRS was flashed. Yes, is the "Telemetry Lost/Recovered" loops. Yes, "c" sometimes appears

Same problem of you! have you solved?
I made the same procedure of you, but different radio.
My HW: R9MX, R9M 2017 (with resistor mod), Nirvana NV14 edgeTX 2.6
Express LRS version flashed 2.3 (i have tried older version with same results)
if telemetry is set 1/4 or 1/2 "Telemetry Lost/Recovered" loops, other rates no telemetry at all
baud rate set to also to 115k but nothing change. 
I think that the problem for some reason is on the R9MX maybe different revision, mine is rev0.2.

NOTE: I bought R9M 2nd hand, It was flashed with a firmaware called FLEX!
