### ISSUE TITLE
Baud rate for passthrough/UART should be configurable

### ISSUE THREAD

**Issue by sfjuocekr** [ExpressLRS/ExpressLRS#1349]
```
======== PASSTHROUGH INIT ========
  Trying to initialize /dev/ttyACM0 @ 420000
```

Baud rate is hardcoded to 420000, but some people like myself have receivers on slower UART's.

There could be a selection for this, taking the RCVR_UART_BAUD is not wise as a receiver might not be running at a lower baud rate.

**Comment by commanderguy3001** [comment]
Why can't you run on a higher uart baud rate is an important question I think, or: why do you run it at a slower rate in the first place?

**Comment by sfjuocekr** [comment]
Because there are devices that do not support the default, higher, baud rate.

For example, I use a Teensy board as a joystick with my receiver attached to it. It can't run 420000, so I have set RCVR_UART_BAUD to 115200.

The configurator allows changing RCVR_UART_BAUD but not the baud at which it is going to flash. I think this should be configurable as well.

I can flash it with esptool manually at any baud rate no problem.

**Comment by CapnBry** [comment]
Ugh is all I have to say about this. The upload baud rate is defined by the PIO target definition, we have a handful of different speed it can run at. Just update your one-off joystick RX through wifi? You're making work for us! 😛

Also: This is strictly a Configurator thing I think.

**Comment by sfjuocekr** [comment]
Yes I think so as well, I might look at it when I find the time. Never done any UI work :)
