### ISSUE TITLE
Add configurator option to disable telemetry.

### ISSUE THREAD

**Issue by inouekou** [ExpressLRS/ExpressLRS#1350]
I should have posted it to Configurator.
I will delete it.

*Instead of commenting "I want this too", consider leaving a :+1: instead, to reduce spam and clutter*

**Comment by inouekou** [comment]
I should have posted it to Configurator.

**Comment by jurgelenas** [comment]
> I should have posted it to Configurator.

I have transferred your issue to the firmware repository. It is firmware issue first, not the configurator

**Comment by pkendall64** [comment]
If you have a module with an OLED and joystick, you can disable telemetry from there.
This is not a configurator or firmware issue. The enhancement we made was to allow the user to set telemetry ratio in LUA or from OLED/TFT interface per model.

**Comment by inouekou** [comment]
@jurgelenas Thank you so match.

@pkendall64 The only product that can be used in Japan is BetaFPV nano TX.
There is no certified product that can use OLED and joystick.
This means that neither Lua script nor OLED/TFT can be used with FUTABA transmitters.
This is due to the fact that Japan's radio wave certification system is unique compared to the rest of the world.
