### ISSUE TITLE
NamimnoRC FLASH 2400 OLED TX. The capability indicators on the module screen and the LUA script do not match.

### ISSUE THREAD

**Issue by RCPOINT** [ExpressLRS/ExpressLRS#1356]
## Current Behavior
I change the power in a script on the control equipment. It was 50, I set it to 100. The screen displays 50. I change the power. It was 100, set 250. Screen display 100. I see the set previous characteristic on the screen. If I change the power with the joystick, then the script does not display the actual readings.
The bluetooth controller in the script is activated if the power is set to 25 mW. If the installed power is higher than 25 mW, the script switches to "Joystick" mode and returns to the main screen. The module is rebooting. The connection does not occur.
P.S. I apologize if the text is not correct. Made with google translate.

## Steps to Reproduce

1.

2.

3.

4.

## Your Environment

- TX hardware: NamimnoRC FLASH 2400 OLED TX
- RX hardware: -
- Handset model: RADIOMASTER TX16S
- OpenTX version (including nightly number)  OpenTX 2.3.14
- ExpressLRS version (TX & RX MUST MATCH): 2.1
- Packet Rate: - switching
- Telemetry Ratio: 1:128
- user_defines:

**Comment by pkendall64** [comment]
I have reproduce the problem with the power settings not being updated on the OLED when changed in the LUA.
I cannot reproduce the BLE problem. Can you give a step-by-step of how to reproduce please?
