### ISSUE TITLE
After the elrs 2.2 version is out of control, it cannot be reconnected.

### ISSUE THREAD

**Issue by wsnfly** [ExpressLRS/ExpressLRS#1382]
## Steps to Reproduce

1.After the elrs 2.2 version is out of control, it cannot be reconnected.  Use the zorro remote and lightning receiver.  When the flight distance reaches 6 kilometers, it loses control due to obstruction, and it cannot be reconnected after losing control.  In the end, it was forced to land by digital transmission.  It can be connected normally after powering on again.

https://m.youtube.com/watch?v=YsR14p3QuWM

2.

3.

4.

## Your Environment

- TX hardware:zorro
- RX hardware:thunder2.4
- Handset model:2.2.0
- OpenTX version (including nightly number)
- ExpressLRS version (TX & RX MUST MATCH):
- Packet Rate:
- Telemetry Ratio:
- user_defines:

**Comment by CapnBry** [comment]
Do you have `NO_SYNC_ON_ARM` enabled? I can't reproduce this and lose connection all the time.

**Comment by wsnfly** [comment]
With this tag enabled, this phenomenon does not occur every time.  Can't reproduce at close range.  I'll test it at a distance with the full recording later.  I remember that the early beta version 915 also had this phenomenon

**Comment by SunjunKim** [comment]
> With this tag enabled, this phenomenon does not occur every time

You HAVE TO DISABLE `NO_SYNC_ON_ARM` for any long-range flight. FYI.
