### ISSUE TITLE
X9D_OneBit_Status_2_3_14

### ISSUE THREAD

**Issue by lion13ch** [ExpressLRS/ExpressLRS#1397]
I use OpenTX 2.3.14(X9D_OneBit_Status_2_3_14.bin) at Taranis X9D with HM ES24TX Pro module. Elrsv2.lua script run once normal but the other times it get memory error (script panic not enough memory) until next radio off/on. 
Without OneBit option Taranis X9D runs Elrsv2.lua script very slow (slow inverter problem).
Can X9D_OneBit_Status firmware be compiled without debug option to fix this problem?

**Comment by schugabe** [comment]
We stopped building open tx versions since edgetx has all features like onebit merged so you can get a release build with onebit.
