### ISSUE TITLE
SX127xDriver::SetMode: bug wo consequence

### ISSUE THREAD

**Issue by olliw42** [ExpressLRS/ExpressLRS#1426]
https://github.com/ExpressLRS/ExpressLRS/blob/master/src/lib/SX127xDriver/SX127x.cpp#L363

gladly ModFSKorLoRa is 0x80 which is equal to the write bit ...

should be hal.writeRegister(SX127X_REG_OP_MODE, mode);

:)

**Comment by RishiKumarRay** [comment]
can i raise a PR  changing this fix

**Comment by pkendall64** [comment]
> can i raise a PR changing this fix, is the fix involves changing the line only

I don't think you ever raised the PR did you?
