### ISSUE TITLE
Binding phrase is not protected

### ISSUE THREAD

**Issue by haybeseret** [ExpressLRS/ExpressLRS#1447]
Hi,

I am running with Configurator 1.3.8 and 2.2.0 FW.
Building BETAFPV_2400_TX_via_UART .
Upon strings inspection in the bin file i can see the binding phrase in clear text around 4E646h offset. ( i guess it can be viewed in a simple notepad++ as well, just search for  "DMY_BINDING_PHRASE")

Taking into consideration that it is treated as a "password" in the configuration, I think it should remain so in the FW files as well.

Thanks for the awesome work ! This project is simply amazing !

**Comment by pkendall64** [comment]
The binding phrase is NOT for security. It's for uniqueness.
