### ISSUE TITLE
LOCK_ON_FIRST_CONNECTION bug (2.2.0)

### ISSUE THREAD

**Issue by SagittariusA33** [ExpressLRS/ExpressLRS#1449]
Few days ago updated from 1.2.0 to latest 2.2.0 and when switching the packet rate in script I get in situation where I cannot connect to receiver. It should work after powercycling the RX but it doesn't work even after powercycling both RX and TX. 

Flashed fw with LOCK_ON_FIRST_CONNECTION disabled and works just fine as expected. 

Am I missing something? Because it should reconnect again after powercycle when changing packet rate with this option enabled. (had no problems on v1.2.0 with LOCK_ON_FIRST_CONNECTION enabled)

R9mm and R9 MX
R9M (pre-2019) 
Frsky QX7 accst
OpenTX 2.3.14
ELRS 2.2.0

**Comment by StonedDawg** [comment]
do you have modelmatch on? can you upload please write all the parameter value you have from the lua script

**Comment by SagittariusA33** [comment]
Model match is off, 100 Hz, 1:16 telemetry, hybrid switches.

R9M:
![image](https://user-images.githubusercontent.com/100162836/158224033-e007a901-06ef-4c59-b12a-e6a8d25887f4.png)

R9mm:
![image](https://user-images.githubusercontent.com/100162836/158224521-bae3f870-e32a-4167-97f5-76470e1f311a.png)

But like I said, disabling "lock on first connection" fixed it. I don't exactly need it, but maybe I'm not the only one facing this problem.
