### ISSUE TITLE
Taranis Q X7 / Jumper Aion Nano T-Pro TX serial packet loss

### ISSUE THREAD

**Issue by froqstar** [ExpressLRS/ExpressLRS#1451]
## Current Behavior

I am using a Taranis Q X7 radio running EdgeTX 2.6 (non-ACCESS, no inverter mod) and a Jumper Aion Nano T-Pro TX module running 2.2.0 CE attached via JR bay adapter. 

The ExpressLRS LUA script is stuck at `Loading` when baud rate is set to 400000/OneBit, the only way to make it work is setting baud to 115200, OneBit or Normal doesn't really matter.
Even with this low baud rate, it doesn't get better than 6/242 in the top row link stats, going as low as 17/232 at 250 packet rate.
At 50Hz packet rate it averages around 2/48.

## Steps to Reproduce

1. Use stock Taranis Q X7 non-ACCESS, with Jumper Aion Nano T-Pro module on latest release.

## Possible Solution (Not obligatory)

Is the inverter mod mandatory?

## Details

My Taranis is from a pretty early batch that still had the non-angled top switches. Could it be that the inverter is even worse there? 
GIven that it can't properly do 115200 as well, this seems unlikely. 
Maybe my TX module is faulty?

## Your Environment

- TX hardware: Jumper Aion Nano T-Pro TX
- RX hardware: None
- Handset model: Taranis Q X7
- OpenTX version (including nightly number): EdgeTx 2.6.0
- ExpressLRS version (TX & RX MUST MATCH): 2.2.0
- Packet Rate: 250
- Telemetry Ratio: 1:64 but doesn't matter, same behaviour at all rates even OFF.
- user_defines: CE regulatory domain

**Comment by pkendall64** [comment]
This would be better asked on discord.
But yes, an inverter mod is pretty much mandatory for this radio because the built-in inverter is far too slow!
