### ISSUE TITLE
ERROR[4]: Not Enough Space

### ISSUE THREAD

**Issue by jianwwpro** [ExpressLRS/ExpressLRS#1473]
## Current Behavior

Upload firmware on web site for reciver.
When upload 100% report an error:
`ERROR[4]: Not Enough Space`

- TX hardware: Jumper aion 2400 TX
- RX hardware: Jumper 2400 RX MINI

- ExpressLRS version (TX & RX MUST MATCH): 2.2.0

**Comment by pkendall64** [comment]
Have you asked on discord in the #help-and-support channel? Please ask questions there before opening bug tickets.
This error is usually intermittent and is normally resolved by retrying the upload.
