### ISSUE TITLE
diy e28 tx

### ISSUE THREAD

**Issue by hz89377361** [ExpressLRS/ExpressLRS#1491]
My hardware version is diy e28 tx, and the software version is master. When I use WiFi to flash to version 2.3, there will be a refresh rate error, which is displayed as ERRHZ, and cannot be used normally.

**Comment by pkendall64** [comment]
You are effectively downgrading from master to 2.3 which is not a supported operation.
If you wish to flash 2.3, I would suggest doing it via UART with a full flash reset first with `esptool erase_flash`
