### ISSUE TITLE
Flywoo Elrs EL24P

### ISSUE THREAD

**Issue by ElRouge** [ExpressLRS/ExpressLRS#1493]
good morning guys I took a flywoo RX and while I was about to fleshare I came out this msg.  Can I go quiet?  it is the first time that I come out.  thank you
![IMG20220322114605](https://user-images.githubusercontent.com/96788158/159465842-8e81fc59-b8d4-499c-932d-fe31c2908a50.jpg)

**Comment by jurgelenas** [comment]
You can still use this receiver. It is just a warning to let users know that this manufacturer does not collaborate with the ExpressLRS team.
