### ISSUE TITLE
TTGO Display

### ISSUE THREAD

**Issue by Sn0ff** [ExpressLRS/ExpressLRS#15]
Thanks for this project.
I want to ask, you have a plan to add support for S.port (  mavlink telemetry ) probably only latest GPS data and battery information  in  TTGO  display  . it would be very useful in crashes.

Thanks

**Comment by AlessandroAU** [comment]
Should be possible, but I want to work on some more important features first like dynamic power and dynamic RF rates :)

**Comment by playermty** [comment]
Thanks in advance.
Can you add support for r9slim v1?

**Comment by brandonrc** [comment]
This has been added to V2.0
