### ISSUE TITLE
BLE Joystick under windows 10

### ISSUE THREAD

**Issue by adriancodre** [ExpressLRS/ExpressLRS#1523]
I have a Jumper T-Pro with internal ELRS module. When i enable the joystick capability of elrs, i can not find it in widnows 10 using aTP-LINK UB400 dongle, but on my android phone i see the joystick and can connect to it. What am i missing ?

**Comment by mavenius** [comment]
I came for the opposite problem; what are you able to use the joystick for on Android? I can bind and connect to it, but it doesn't seem to be detected by any apps. Thanks!

**Comment by adriancodre** [comment]
i did not try in any app, but it connected to it. i bought a cheap dongle and that worked under windows, but the distance was not great at all and the connection was not usable so cable is king :)

**Comment by mavenius** [comment]
Cool, thanks for responding. I used BT with Velocidrone yesterday (using my laptop's interested BT.) It works, but it's a little laggier than when wired or using the XSR-SIM dongle.

**Comment by Dr-Gandalf** [comment]
I have similar issue, it works ok on internal Bluetooth adaptor of my dell laptop and a Bluetooth enabled azus motherboard, but it is not detected by a generic usb Bluetooth dongle (V3+EDR)
![image](https://user-images.githubusercontent.com/26264000/171330667-820f2a4a-5d2c-4337-b21b-5a4d2d1708a1.png)

**Comment by dougshell** [comment]
I have found that the BT range on my Zorro is incredibly short (inches). Have you guys tested the offending hardware at obnoxiously close ranges?

**Comment by taraskornuta** [comment]
I have an external BT module TP-LINK UB500 and HappyModel 2.4RX (Win10, 11). It successfully paired and I even can see the joystick in Windows device manager. 
But none of the three simulators can't work with this joystick. The sim crashes or hangs. 
Ardupilot Mission Planner also can't see the joystick

**Comment by socalengineer** [comment]
I also have the same issue: Under windows using two different USB bluetooth adapters no bluetooth joystick was found (ASUS and TP-Link adapters).

 I have resorted to using a wire.

Under Mac OSX my laptop sees the Joystick just fine, I can even see the adapter with my iPhone 13 Pro.

Using a Happy Model ES24TX Pro.

**Comment by Dr-Gandalf** [comment]
> I have similar issue, it works ok on internal Bluetooth adaptor of my dell laptop and a Bluetooth enabled azus motherboard, but it is not detected by a generic usb Bluetooth dongle (V3+EDR) ![image](https://user-images.githubusercontent.com/26264000/171330667-820f2a4a-5d2c-4337-b21b-5a4d2d1708a1.png)

I finally found the problem I had. My Bluetooth adaptor was only version 2.0, and this Bluetooth version is not compatible with Bluetooth LE. Solution, update the adaptor to Bluetooth version >= 4.0

**Comment by jurgelenas** [comment]
> > I have similar issue, it works ok on internal Bluetooth adaptor of my dell laptop and a Bluetooth enabled azus motherboard, but it is not detected by a generic usb Bluetooth dongle (V3+EDR) ![image](https://user-images.githubusercontent.com/26264000/171330667-820f2a4a-5d2c-4337-b21b-5a4d2d1708a1.png)
> 
> I finally found the problem I had. My Bluetooth adaptor was only version 2.0, and this Bluetooth version is not compatible with Bluetooth LE. Solution, update the adaptor to Bluetooth version >= 4.0

Bluetooth

**Comment by jurgelenas** [comment]
> > I also have the same issue: Under windows using two different USB bluetooth adapters no bluetooth joystick was found (ASUS and TP-Link adapters).
> > I have resorted to using a wire.
> > Under Mac OSX my laptop sees the Joystick just fine, I can even see the adapter with my iPhone 13 Pro.
> > Using a Happy Model ES24TX Pro.
> 
> Thought I would post my update here that I had to get it to work--I tried what others on this thread mentioned to bring the Joystick closer to the PC, that worked. However, I'm only getting 5 channels (4ch for controls, and 1 switch). I need more switches to work any advice?

You need to setup that in your radio model settings.

**Comment by jurgelenas** [comment]
Closing as all of this looks like it is related to the user environment / old bluetooth dongles.
