### ISSUE TITLE
Script Syntax error on lua with x9d+

### ISSUE THREAD

**Issue by spyder0069** [ExpressLRS/ExpressLRS#1548]
## Current Behavior
Trying to run the latest elrsV2  lua script on a x9d+ running 2.7.0 gives:

Script syntax error
Tools/elrsv2.lua:7
unexpected symbol near '<'

**Comment by pkendall64** [comment]
That would mean that you have not downloaded the LUA correctly. Probably downloaded from github in html form hence the `<` character.
Please ask for help on discord #help-and-support channel.

**Comment by spyder0069** [comment]
I am not 100% sure which source I got that lua from so to confirm I just downloaded the lua through the expresslrs configurator.  I deleted the original and copied the new one to the SD.  It gives a different error on the x9d+:

Script syntax error
not enough memory

**Comment by spyder0069** [comment]
This x9+ is running edgetx 2.7.0.  I have not tried on opentx.

**Comment by StonedDawg** [comment]
@spyder0069 you can try turn off the x9d and run it again, it might be out of memory on 1st launch only. if you still can't solve this, please jump to discord for further guidance.

**Comment by spyder0069** [comment]
This morning I powered up the radio and the lua worked so turning off the radio and back on must have corrected it.  Thanks for the help.
