### ISSUE TITLE
Make hybrid switch mode use -DARM_CHANNEL

### ISSUE THREAD

**Issue by JBKingdon** [ExpressLRS/ExpressLRS#157]
#156 introduces a define for which channel means 'arm', so the hybrid switch code should be updated to use this as the channel that is sent with every packet.

**Comment by maybenikhil** [comment]
Would require pretty significant rewriting of the hybrid switch code

**Comment by CapnBry** [comment]
The ARM_SWITCH define has been removed and AUX1 is always the arm switch now, which is sent on every packet in HYBRID_SWITCHES_8 (and normal mode too) so this request is obsolete.
