### ISSUE TITLE
wrong fimware

### ISSUE THREAD

**Issue by shijianzhong** [ExpressLRS/ExpressLRS#1591]
## Current Behavior

wrong firmware
![image](https://user-images.githubusercontent.com/15205387/170389394-001d8f4a-b866-4a29-b9e1-4f5babd36d11.png)

## Steps to Reproduce

1.

2.

3.

4.

## Your Environment

- TX hardware:
- RX hardware:
- Handset model:
- OpenTX version (including nightly number)
- ExpressLRS version (TX & RX MUST MATCH):
- Packet Rate:
- Telemetry Ratio:
- user_defines:

**Comment by shijianzhong** [comment]
![image](https://user-images.githubusercontent.com/15205387/170389442-51993c59-a68d-4533-9cf5-a51dc4966e73.png)
![image](https://user-images.githubusercontent.com/15205387/170389448-80c39957-2149-4107-9b6e-b476fe6d422e.png)
![image](https://user-images.githubusercontent.com/15205387/170389454-ab107f26-afc1-4eca-8c02-3a0692b37c0a.png)
![image](https://user-images.githubusercontent.com/15205387/170389466-0ea5ab38-0bfb-4418-b6e5-6b3d318206d4.png)

**Comment by pkendall64** [comment]
This is not a bug. Please ask on discord in the #help-and-support channel.
This target is actually an alias of the DIY target and it looks like you are running a very old version of the firmware on the RX.
I suggest you update using an FTDI adapter.

**Comment by shijianzhong** [comment]
use wifi， not ftdi
