### ISSUE TITLE
 force flash fail on DIY_2400_RX_ESP8285_SX1280_VIA_BETAFLIGHTPASSTHROUGH

### ISSUE THREAD

**Issue by liuxyc** [ExpressLRS/ExpressLRS#1597]
## Current Behavior

when using expressLRS-configurator  force flash DIY_2400_RX_ESP8285_SX1280_VIA_BETAFLIGHTPASSTHROUGH
it report *** Do not know how to make File target `uploadforce'   

## Steps to Reproduce

1. Choose 2.5, Target BETAFPV 2.4G.   BETAFPV Lite 2400 RX

2. Select COM3(the only one), Choose  ForceFlash

## Your Environment

- TX hardware:  
- RX hardware:
- Handset model:
- OpenTX version (including nightly number)
- ExpressLRS version (TX & RX MUST MATCH):  rx is 2.5 which already flashed by wifi
- Packet Rate:
- Telemetry Ratio:
- user_defines:

**Comment by CapnBry** [comment]
ForceFlash is not available until 3.0, so this will be resolved then. Consider it a button for a feature that you don't have yet, and the way to override the target is the same way it was before the button: use the webui, which pops up a confirmation dialog.
