### ISSUE TITLE
Receiver led is triple-blinking, no reaction on TX commands

### ISSUE THREAD

**Issue by davidT54** [ExpressLRS/ExpressLRS#1641]
## Current Behavior

The receiver is bind but there is no reaction on TX commands.
Led is triple-blinking. If I disconnect the battery Tx warns - "telemetry lost". 
All started when I flashed elrs firmware version 2.5 to both. Previous version, 2.0, worked. 

Any idea what is going wrong. Thank you.

## Environment

- TX hardware:   Zorro ELRS
- RX hardware:  Happymodel EPW5 2.4GHz 
- ExpressLRS version (TX & RX MUST MATCH):  2.5.0
- Packet Rate: 500

**Comment by pkendall64** [comment]
This is a question for discord, the issues tracker in github is for bugs.
A tripple blink is model mistmatch - https://www.expresslrs.org/2.0/software/model-config-match/

**Comment by davidT54** [comment]
Thank you.
