### ISSUE TITLE
Happymodel TX pro 3.0 RC1 does not fit.

### ISSUE THREAD

**Issue by Hermiedaddy2** [ExpressLRS/ExpressLRS#1687]
2.51 Happymodel TX Pro fits in transmitter module.
3.0 RC1 fails to upload because it does not fit.

**Comment by pkendall64** [comment]
Can you please ask on discord. This module does run 3.0rc1.

**Comment by padcom** [comment]
@pkendall64 @Hermiedaddy2  Could you post the solution here for people that aren't on Discord? Google leads to this ticket...
