### ISSUE TITLE
3.0.0-RC1 Flash Fails with "Type Mismatch"

### ISSUE THREAD

**Issue by DocTrucker** [ExpressLRS/ExpressLRS#1726]
## Current Behaviour

Flash update to a Happymodel 2.4ghz Tx module ( HAPPYMODEL_ES24TX_2400_TX ) fails. Web update suggests a 'Type Mismatch'. Force update via web also fails.

## Steps to Reproduce

Using ExpressLRS configurator on Ubuntu options:
Release: 3.0.0-RC1

Target:
Device category: Happymodel 2.4 GHz
Device: HappyModel ES24TX 2400 TX

Flashing Method:
WIFI selected

Device options:
Standard Mode selected

Regulatory domains:
REGULATORY_DOMAIN_EU_CE_2400 enabled

Binding phrase setup:
BINDING_PHRASE enabled
Custom binding phrase specified.

Compatibility options
UART_INVERTED enabled

Extra data:
TLM_REPORT_INTERVAL_MS disabled

Network:
AUTO_WIFI_ON_INTERVAL enabled
Value 60
HOME_WIFI_SSID enabled
Value specified
HOME_WIFI_PASSWORD enabled
Value specified

Other options:
WS2812_IS_GRB disabled
## Possible Solution (Not obligatory)

Actions:
Tx Module auto appears on "WiFi Device Selection" after selecting "Enable WiFi" option on the LUA script (express 2.5.1) page under "WiFi Connectivity".

Tried both "BUILD" followed by using the webpage to load the firmware and "BUILD & FLASH"

## Your Environment

Hardware: Ubuntu
ExpressLRS Configurator: expresslrs-configurator_1.4.2_amd64.deb
Tx: Jumper T16 Pro
Tx module: Happymodel ES24TX 2.4G ExpressLRS Micro TX Transmitter ( https://www.ebay.co.uk/itm/164983737086 )
Existing ExpressLRS version on Tx Module 2.5.1

## Attached files

[ExpressLRSBuildLog_20220728083828689_FailWifiUpdate.txt](https://github.com/ExpressLRS/ExpressLRS/files/9207535/ExpressLRSBuildLog_20220728083828689_FailWifiUpdate.txt)
[ExpressLRSBuildLog_20220728084249717_BuildOnly.txt](https://github.com/ExpressLRS/ExpressLRS/files/9207537/ExpressLRSBuildLog_20220728084249717_BuildOnly.txt)
![WebUpdateFail](https://user-images.githubusercontent.com/30924036/181467391-d54007e5-d108-49c7-b4e3-76a886af6fea.png)
(Home network details specified, but removed from screen capture image)

**Comment by pkendall64** [comment]
Yes, thats correct, because the targets are now Unified targets, you will need to select Flash anyway.

**Comment by DocTrucker** [comment]
Please share a link to something discussing the "Unified targets".

I pressed force anyway and it failed to update.

**Comment by DocTrucker** [comment]
I will run the force anyway and capture screenshots of the results. Is it perhaps something to do with the fixes applies to force wifi flash needing to be apploed to the website flash?

https://github.com/ExpressLRS/ExpressLRS/pull/1600

**Comment by DocTrucker** [comment]
These are the screen shots of the webpage update process and it's ultimate failure even after force flash - bad size error.

I tried with the 3.0.0-rc1 lua script and had the same result.

![01_220729_ELRS_Update](https://user-images.githubusercontent.com/30924036/181716633-86040d0f-dc33-4656-978c-acc4a4ec4da3.png)

![02_220729_ELRS_Update](https://user-images.githubusercontent.com/30924036/181716705-642448ae-1122-4dd6-904b-0a12faa9b2f3.png)

![03_220729_ELRS_Update](https://user-images.githubusercontent.com/30924036/181716733-383be607-e49b-463b-a7dc-af32a73fe8a5.png)

![04_220729_ELRS_Update](https://user-images.githubusercontent.com/30924036/181716756-7b022942-b822-4531-ba46-d5a56b6da53e.png)

**Comment by pkendall64** [comment]
You will probably be better opening it up and flashing using the the USB connector and choosing UART flash in configurator.

**Comment by DocTrucker** [comment]
This is the resulting logs  from the "Build & Flash" and "Force Flash" options on the ELRS Configurator.

![07_220729_ELRS_Update](https://user-images.githubusercontent.com/30924036/181719865-43b5232c-9100-4e77-9b09-6c4b84551a52.png)

[ExpressLRSBuildLog_20220729083336281_BuildAndFlashFail.txt](https://github.com/ExpressLRS/ExpressLRS/files/9218254/ExpressLRSBuildLog_20220729083336281_BuildAndFlashFail.txt)

[ExpressLRSBuildLog_20220729083145272-ForceFlashFail.txt](https://github.com/ExpressLRS/ExpressLRS/files/9218258/ExpressLRSBuildLog_20220729083145272-ForceFlashFail.txt)

**Comment by DocTrucker** [comment]
The UART and WiFi flashing from configurator isn't working for me at all. Only way I have had successful updates is via the webpage. Webpage update fails with bad size.

I suspect this is two issues; the configurator isn't happy on my Ubuntu machine, & the bad size issue on the webpage based update.

**Comment by pkendall64** [comment]
The "Bad Size" issue is because the upload page doesn't seem to be supplying the X-FileSize header with size of the binary file.
You could try from the command line using curl. 
Find the bin file, ls -al firmware.bin, to get the file size and put then in the place of xxx below.
```
curl -Fupload=@firmware.bin -H "X-FileSize=xxx" http://elrs_tx.local/upload?force
```

**Comment by DocTrucker** [comment]
Will have a look at that later. Why would that be an issue post 3.0.0-rc1 with force flash, but not 2.5.1 with normal flash?

**Comment by pkendall64** [comment]
It shouldn't, Ive been over that code so many times! You could even try opening the web-page on the module with ?force at the end of the URL so it will just do the force and not check for the mismatch.
i.e. http://elrs_tx.local/?force
Also try with the module really close to the wifi router as well.

**Comment by pkendall64** [comment]
Also, you should join the discord server and ask in the help-and-support channel, there will be plenty of helpful folk there who can help too.

**Comment by DocTrucker** [comment]
Yeah, trying to get on discord but they decided I was a spam bot on log in and blocked me until late last night!

**Comment by DocTrucker** [comment]
Curl not behaving properly either...

![08_220729_ELRS_Update_CurlCMD](https://user-images.githubusercontent.com/30924036/181767866-a2a45a54-76a0-4df8-9d23-7f43827f0318.png)

**Comment by DocTrucker** [comment]
http://elrs_tx.local/?force still results in a Targets mismatch warning. Ultimately fails anyway.

**Comment by DocTrucker** [comment]
UART flashing issue solved. Power only USB lead! :-D

Think the wifi build and flash issues relate to curl, as when I manually run curl it fails to find the file, despite ls having justbreported its size fine.

Type mismatch and bad size issues remain.

**Comment by pkendall64** [comment]
I'm glad you got it sorted, but it seems odd that curl is broken on your system!

**Comment by tomhorst2004** [comment]
Currently having the same problem with the slim pro series, will try to do it via uart  but flashing via wifi does not work (exact same problem)

**Comment by SplinterII** [comment]
Exactly same story here!

**Comment by fraro** [comment]
same problem here (2.5.1 -> 3.0.0rc2):
curl -F upload=@firmware.bin -H "X-FileSize: 1455061" -X POST   http://192.168.1.228/forceupdate
results in
{"status": "ok", "msg": "Update cancelled"}
!?

**Comment by pkendall64** [comment]
forceupdate is the command to complete an update after an upload.
You need upload?force instead which will do the upload and assume you want to force flash the device.
I that does not work, then a UART flash is required.

**Comment by fraro** [comment]
Since UART seems to be the only way, I would like to drop https://www.youtube.com/watch?v=yJ8Gu9XVjV0 for the next BetaFPV micro 1W users spending hours to get the UART (USB-C) update working :-/
Now my TX is on 3.0.0RC2, which hopefully solves an issue on the RX (PWM) side with my ESC...

**Comment by pkendall64** [comment]
We've figured out the issue and provided a solution in the pinned comments in the #help-and-supprt channel on discord.

**Comment by mazzus** [comment]
This solved the issue for my HappyModel ES24TX Pro :smile: 


For anyone who doesn't want to search for the pinned message on the discord:

> deadbyte — 09/01/2022
>
> Regarding "Bad Size Given" on some TX modules being flashed to 3.x, here's your fix:
> https://github.com/pkendall64/repartitioner#what-is-this
> use the Releases page: https://github.com/pkendall64/repartitioner/releases/tag/1.0
> and download the 
> repartitioner.bin
> and flash it first to your tx module,
> once flashed, exit the lua script and relaunch it, then reactivate the WiFi on the module and upload the 3.x firmware
> tagging @V-22 @commanderguy3001
