### ISSUE TITLE
Mixing touch and scroll support in Lua breaks input

### ISSUE THREAD

**Issue by CapnBry** [ExpressLRS/ExpressLRS#1733]
ExpressLRS 3.x.x-maint elrsv3.lua (latest)

## Steps to Reproduce

1. Enter Lua on a touchscreen device (TX16S used), click any `luaItem_selection` item to start changing the value
2. Swipe right to try to change the value, the loading bar comes up?
3. Note the srollwheel no longer works
4. Use Exit/Rtn physical button to exit edit mode
5. Scrollwheel doesn't work at all any more

**Comment by CapnBry** [comment]
I've debugged this, and after any touch event, EdgeTX stops sending us `EVT_VIRTUAL_NEXT / EVT_VIRTUAL_PREV` events. I still get `EVT_VIRTUAL_EXIT / EVT_VIRTUAL_ENTER` but the scroll wheel no longer generates an event.
```lua
local function run(event, ts)
  lcd.clear()
  if ts then
    lcd.drawText(0, 0, string.format("%ux%u", ts.x, ts.y))
  elseif event ~= 0 then
    lcd.drawText(0, 0, tostring(event))
  end
  
  return 0
end

return { run=run }
```

With this code, when I use the scroll wheel, I see the event for the scroll appearing briefly on the screen, but then I tap, and I never get another scroll event. EdgeTX 2.7.0, 2.7.1 and the PR#2100, but works fine in the simulator

**Comment by pkendall64** [comment]
@CapnBry should this be closed now?

**Comment by CapnBry** [comment]
Oh yes sorry, I need to open a EdgeTX issue for it I suppose.
