### ISSUE TITLE
Blinking RXBt Telemetry, Low Battery warning

### ISSUE THREAD

**Issue by caspervanbeek** [ExpressLRS/ExpressLRS#1777]
## Current Behavior

INAV 5.0, EDGE TX
From my Telemetry an RXBt flashes 16.1v and 4.7v.
Bat% flashes 76% and 0%

## Steps to Reproduce

1.

2.

3.

4.

## Details
Three questions:
I think this alarm can't be there because the battery gives 16.1v.
Why is the RXBt and the Bat% blinking?
How can I cancel this alarm?

## Your Environment

- TX hardware: Radiomaster TX16S
- RX hardware: INAV 5.0,  TBS Nano receiver
- Handset model: ??
- OpenTX version (including nightly number)
- ExpressLRS version (TX & RX MUST MATCH): edgetx-tx 16s - version 2.71 (a55aff02)
DATE 2022-05-09
TIME 04:02:03
CFGV: 221

- Packet Rate:
- Telemetry Ratio:

https://user-images.githubusercontent.com/81965645/185372190-2dc2963e-c58f-43a9-bfe1-f58a806bfd30.mp4

- user_defines:

**Comment by caspervanbeek** [comment]
![TBS Agent X TX 6 19](https://user-images.githubusercontent.com/81965645/185379416-f05ab06c-4c4e-4aa2-8e0a-6a2af3f67af8.jpg)
![TBS Agent XF Micro TX](https://user-images.githubusercontent.com/81965645/185379423-409dfc72-84e2-4cd7-9c2b-3fd7c5e5132d.jpg)
![TBS Agent XF Nano RX](https://user-images.githubusercontent.com/81965645/185379424-a539292e-598c-45da-981a-657b95d85546.jpg)
![TBS Agent X RX 6 19 Settings](https://user-images.githubusercontent.com/81965645/185379425-1d39c57e-171b-4939-bb80-7cf357033ff8.jpg)
![TBS Agent X RX 6 19](https://user-images.githubusercontent.com/81965645/185379427-3de4c2d6-abe8-447b-94c3-23520962269f.jpg)
![TBS Agent X TX 6 19 Settings](https://user-images.githubusercontent.com/81965645/185379429-1e7a083f-1574-4612-ab7f-dca7ffd19236.jpg)

Greetings casper

**Comment by qubic** [comment]
Ask TBS.

**Comment by jurgelenas** [comment]
ExpressLRS is not affiliated with TBS products in any way. Try contacting TBS customer support or post this question to Inav community page. Best of luck!
