### ISSUE TITLE
ELRS 3.0 RC2 Flash Fail with Radiomaster Zorro/ TX12. I reflashed ELRS 2.51 and the flash completed with Success as it's supposed to.

### ISSUE THREAD

**Issue by burgerplanet** [ExpressLRS/ExpressLRS#1807]
## Current Behavior

ELRS 3.0 RC2 Flash Fail with Radiomaster Zorro/ TX12. I reflashed ELRS 2.51 and the flash completed with Success as it's supposed to.
## Steps to Reproduce

1. Trying to flash ELRS 3.0 RC2

2. Using EdgeTX

3. Tried flashing over usb. Flash keeps failing.

4.

## Details

 trying to flash new firmware

## Your Environment

- TX hardware: Radiomaster Zorro ELRS Module
- RX hardware: Radiomaster RP1
- Handset model: Radiomaster TX12 MKII
- EdgeTX version 2.8.0 f475a9ce
- ExpressLRS version (TX & RX MUST MATCH): 2.51
- Packet Rate: 250
- Telemetry Ratio: 1:64
- user_defines:

> They have probably flashed a pre-release version onto the TX16S, so you should be ok to use that version and just follow the other instructions to flash the ELRS module.

Cool. I figured it out. Thanks.

**Comment by pkendall64** [comment]
You have not provided any useful information in this bug report! I assume you got the dreaded "Bad size given" message.
If that is the case then you need to flash via USB and this is very easy to do with the Zorro, just follow the instructions here https://www.expresslrs.org/2.0/quick-start/transmitters/rm-internal/#flashing-via-edgetx-passthrough

**Comment by pkendall64** [comment]
Also, you should as for help on discord about this in the #help-and-support channel.

**Comment by burgerplanet** [comment]
> You have not provided any useful information in this bug report! I assume you got the dreaded "Bad size given" message. If that is the case then you need to flash via USB and this is very easy to do with the Zorro, just follow the instructions here https://www.expresslrs.org/2.0/quick-start/transmitters/rm-internal/#flashing-via-edgetx-passthrough

That's what I tried originally. It says I have EdgeTX 2.8.0, but only version 2.7.1 is available online? Im using the new Radiomaster TX12 MKII

**Comment by pkendall64** [comment]
They have probably flashed a pre-release version onto the TX16S, so you should be ok to use that version and just follow the other instructions to flash the ELRS module.
