### ISSUE TITLE
"Telemetry lost/telemetry recovered" loop with ELRS 3.0.0/2.4g LBT/LoRa/EdgeTX 2.8 nightly

### ISSUE THREAD

**Issue by froqstar** [ExpressLRS/ExpressLRS#1834]
## Current Behavior

At some point (can be directly after turning equipment on, or after some minutes of flying), I get callouts for telemetry being lost, followed by telemetry being recovered, then lost again and so on, with what feels like increasing frequency, ending up with lost/recovered loops happening nearly every second.

Along with the callout by EdgeTX, the `C` in the ELRS Lua disappears and reappears, and the telemetry in the model telemetry page freezes and turns red while the connection is lost.
Control input still works fine and the model is fully controllable, minus telemetry of course.

The issue only seems to appear with LoRa modes 150Hz and up.

EDIT: For 150Hz, I often don't ever get telemetry at all. Control link seems stable as well though. 
EDIT2: 150Hz also loops when allowing the TX to go higher than 10mW (100mW dynamic power, but armed/disarmed aparently doesn't make a difference) 

## Steps to Reproduce

- turn on TX, turn on RX, wait some minutes (usually <<5min for me)

## Possible Solution (Not obligatory)

- switch to ISM domain (instead of EU_CE)
- switch to a FLRC mode
- switch to a fullres LoRa mode
- switch to 50Hz LoRa mode

Those modes seem to be unaffected, but 150Hz, 250Hz and 500Hz LoRa modes experience this problem.

## Details

[EdgeTX logs](https://github.com/ExpressLRS/ExpressLRS/files/9551808/log-2022-09-12-224452.csv)
![configurator 1.5.0 settings](https://user-images.githubusercontent.com/1944754/189762724-d2e06b8b-86fc-4791-b4b0-b5972feeda7c.png)
![LUA settings](https://user-images.githubusercontent.com/1944754/189763037-ec5f4834-745b-4b0f-90b9-e4ae2e3a4081.jpg)

[Video](https://user-images.githubusercontent.com/1944754/189763956-29c836bf-1356-478f-b05e-dad81444b2bb.webm)

## Your Environment

- TX hardware: TX16S MKII internal module (also reproduced with Happymodel ES24TX non-pro in a QX7 in the RC phase)
- RX hardware: Vantac Lite RX & Betafpv lite RX so far, multiple models of each
- Handset model: TX16S MKII, 1.87M baud
- OpenTX version (including nightly number): EdgeTX 2.8.0-nightly (1c715626) from 2022-09-11 
- ExpressLRS version (TX & RX MUST MATCH): 3.0.0
- Packet Rate: 150Hz (also happens on 250Hz & 500Hz LoRa modes)
- Telemetry Ratio: Std (doesn't seem to matter)
- user_defines: - all defaults except bind phrase & wifi credentials

Happens both on the bench at home (only 3 wifi networks around) as well as on my flying field.
Happens both with standalone RX as well as with INAV FC or Matek PWM boards attached.

**Comment by CptLuki** [comment]
Just flashed 3.0 and having similiar issue.
- Matek R24S RX
- Ghost Lite TX + Tango 2
- 250hz Lora
- 250mw
- 2.4g ism
- hybrid switches
- 1:64 tlm
Getting tlm lost tlm recovered warnings. It starts after arm and couple of seconds into flight. Pretty much doing circles around myself and getting these warnings. Tried 1:32 ratio and same thing. Tried to lower tlm power from 100mw to 50mw. Same thing. All was fine on 2.5.1.

**Comment by Demon8Core** [comment]
I got the same problem with my Zorro, but I also lose the connection and it fail-saves like every second. 
Setup:
25mw
5.75M with 0 Err

BetaFPV micro PWM
d250hz
1:32 tlm

Radiomaster EP2 
d250hz
1:64 tlm

I also tried 50hz, but with no luck.

both receivers got the same problem, losing every second the connection...

**Comment by Sekilsgs2** [comment]
Im have same issue with r9m

**Comment by mattiamari** [comment]
I have the same issue using:
- Radiomaster zorro, edgetx 2.7.0, internal elrs
- elrs rx: happymodel EP2 with builtin ceramic antenna
- elrs v3.0.0, 500hz (did not test with other rates)

**Comment by CptLuki** [comment]
Did some back and forth tests with 2.5.1 and 3.0.0. 
Can confirm that on 2.5.1 everything works as expected. Could not get tlm lost when walked to different rooms. Tlm LQ solid 80-90 through couple of walls. In flight could not get tlm lost in normal proximity flying up to at least 300m. Overall good LQ droping max to 85 with ceramic antenna. 

On 3.0.0 always getting tlm lost when I walk to next room. So basically just 1 wall causing tlm lost. In flight same thing. Couple of meters away getting into tlm lost tlm recovered loop when flying pretty close. When flying further like 200m I get tlm lost and it is not even getting back. Only when I come closer again. And overall LQ also seems to be lower. Was hitting LQ 40s while on 2.5.1 could not get under 85. So seems hardware is fine. Not sure what is wrong on FW side. 

- Matek R24S RX (ceramic antenna)
- Ghost Lite TX + Tango 2 ( latest fw 1.34)
- LoRa 250hz + 250 mW power

Not sure if that oscillator has something to do with it as Matek was in danger zone. Also that RX is using PA. And in 2.5.1 it was only 1 target for both Matek RXs. Now in 3.0.0 there are 2 targets. 1 specially for diversity RX R24D

**Comment by robertgodlewski** [comment]
I have experienced same issue on 3.0.0 and LoRa 150Hz mode - constant "telemetry lost/recovered" and poor LQ despite good rssi (~-40dbm). No failsafe though. No problem after switching to FLRC 500Hz.
My setup:
- Taranis X9D with EdgeTx 2.7.1
- DIY 2.4GHz Tx
- Matek R24D
- CE LBT @ 50mW

**Comment by pkendall64** [comment]
Would any of you be willing to test PR #1845 to see if makes a difference.

**Comment by froqstar** [comment]
@pkendall64 I just flashed my TX16S MKII and a betafpv lite RX to this PR version, and it doesn't improve the behavior as far as I can tell. Thanks for the suggestion though.

**Comment by 0crap** [comment]
@froqstar Can you delete all sensors on the radio model in question and rescan for sensors?
Just to make sure your radio is not waiting for sensors that do not exist any more for some funny reason.
It's really weird you have no telemetry at all on 150Hz...

**Comment by froqstar** [comment]
@0crap been there, done that, no change. but thanks for taking a look at this :)

In the meantime I think I found a clue @pkendall64 :
I flashed both TX and RX to ISM instead of EU_LBT domain and ran it for 20min at 250Hz LoRa, rock solid telemetry :).
Same for 500Hz LoRa so far.

I am just wondering why it affects some RF modes and others not at all? Or I just didn't hit that bug there _yet_...

**Comment by 0crap** [comment]
While I'm in the EU (NL) I never used EU_LBT, just sounds like a bad idea.
But OK, for the sake of testing I flashed my 2.4 GHz DIY module to 3.0.0 release EU_LBT.
(Radio is a Taranis QX7S ACCST with the hardware inverter mod.)
Also flashed a HM EP1 RX to 3.0.0 release EU_LBT.

Unfortunately I can't reproduce the issue.
On 150Hz LoRa I can go as low as 1:64 telem (46bps), all fine. (iNav 5.0 reporting 23 sensors total.)
Also tested LoRa 250 and 500Hz at 1:64, all fine.
On LoRa 50Hz I need to bump the telem ratio a bit because of the ridicules slow updates at 1:64.

**Comment by froqstar** [comment]
I seem to have fixed it!? by playing with the dynamic power settings (turning it off/on, changing power levels). I think it started to disappear once I disabled dynamic power, but not entirely sure anymore, could just have been timing. 

Could be that I got corrupted data in those settings that needed to be overwritten to make it work? 
Is there a way to completely clear the TX module memory (apart from the firmware itself) to have a clean slate instead of trying to fix it by fiddling with those settings for all my models?

**Comment by pkendall64** [comment]
Not sure if it could happen from corrupt data in the config, but yes, there is a way to reset the config i.e. all models and other settings available in Lua, back to defaults. Start wifi and visit `http://elrs_tx.local/reset?model` note that the hostname part may be different depending on if you network supports MDNS or if you are using access point mode.

**Comment by 0crap** [comment]
@froqstar Please let us know if the `reset?model` fixes your issues.

**Comment by froqstar** [comment]
@0crap 
first an update _without_ `reset?model`: This morning, the issue I thought fixed yesterday just reappeared. 
Then I tried the suggested `reset?model`, and so far the problem didn't manifest in about an hour of testing on the simulator, with different LoRa rates. 
I also _think_ the controls are much smoother now, but that could be placebo.

**Comment by froqstar** [comment]
And here we go again...the `reset?model` "fix" only worked for two hours or so, then the problem appeared again.
Next I tried the same (`reset?model`) with the RX, which again "fixed" it for about two hours give or take, and now it happens again...
Not so sure about the ISM domain firmware now, I may need to use that for an extended amount of time to be sure.

**Comment by 0crap** [comment]
Try the PR above as asked by pkendall64.
Take your time to see if that makes an improvement.

**Comment by froqstar** [comment]
> Try the PR above as asked by pkendall64.
> Take your time to see if that makes an improvement.

Already tried that (https://github.com/ExpressLRS/ExpressLRS/issues/1834#issuecomment-1250232098) and it showed no difference in behavior, got telemetry loops almost instantly. 
I may just re-test that PR though because I have no other ideas anyway at the moment, maybe I did something wrong yesterday while testing it :)

**Comment by froqstar** [comment]
Just a confirmation: 
ISM firmware version is stable for multiple hours of simulator flying.
Can you confirm my findings @robertgodlewski ?

**Comment by robertgodlewski** [comment]
I've flashed ISM version today and do some tests on the desk - no issues at all. Next, I have flashed CE and after a while problem returned. For me only 150Hz LoRa mode is affected and tx power level (static and dynamic) does not make a difference. I've switched again to ISM and play with it a little bit longer - it worked flawless. I will do some flights over the weekends with ISM and share the results.

**Comment by robertgodlewski** [comment]
Ok, over half an hour in air with ISM 150Hz LoRa mode and not a single issue/hiccup - solid link all the time. Power was set to dynamic but stayed at 10mW all the time. I'll stick to ISM for now.

**Comment by pkendall64** [comment]
> Ok, over half an hour in air with ISM 150Hz LoRa mode and not a single issue/hiccup - solid link all the time. Power was set to dynamic but stayed at 10mW all the time. I'll stick to ISM for now.

Thanks for the report, that will help immensely in finding the problem!

**Comment by zenobik** [comment]
I have the same issue with telemetry lost/recovered in an endless loop:

TX: Radiomaster Zorro EdgeTX 2.7.1, internal elrs
RX: Radiomaster EP1
ELRS v3.0.0, 150 Hz (1:32, 1:16), 250Hz (1:32, 1:64)
TX Power 100mW Dynamic EU_CE_LBT

I had no problems with the previously released version v2.5.1.
The overall range and link stability is much better in 3.0.0, but this telemetry issue is really annoying.

**Comment by Demon8Core** [comment]
Hey Zenobik,
Can you try the ISM domain?
It also worked for me.

**Comment by pkendall64** [comment]
Could you all that are having this problem please re-test pr #1845 as @JyeSmith and I have made some significant improvements to the timing.

**Comment by alphabravogroup** [comment]
Same issue here, but reflashing both TX16s and Matek R24D seems to have fixed it.
Initially it would happen within 10 seconds of powering up changing any/all settings didn't seem to affect it.

**Comment by robertgodlewski** [comment]
> Could you all that are having this problem please re-test pr #1845 as @JyeSmith and I have made some significant improvements to the timing.

Quick test on desk - no problems for me. More testing later.

**Comment by froqstar** [comment]
Same here, finally came around to testing with the linked PR, and while it *may* have improved (hard to tell), I still get the telemetry loops after a few minutes.

**Comment by pkendall64** [comment]
> Maybe @pkendall64 is onto something with #1867 ? After flashing commit `03d9d5` and a good hour of testing the 250Hz LoRa mode seems to be stable for me. 500Hz only hit "the loop" after 10 minutes or so. 150Hz is still broken, goes into looping mode almost immediately. I only flashed the TX, RX is still on 3.0.0 as that PR should not make a difference there?

You shouldn't need to update the RX with that PR.

Can you tell me all your settings on the module because I cannot, for the life of me, replicate the problem described in this ticket. I've just been fixing other issues that I see.

I really need these things, packet rate, telem ratio, switch mode, model match?, power settings (dynamic?) etc. for the mode that exhibits the worst behaviour for you. Also, what values do you see in the telem screen in the radio for 1RSS, RQLY, TRSS and TQLY.

**Comment by froqstar** [comment]
Settings for worst behaviour:

Rate: 150Hz
Telem Ratio: Std (doesn't matter AFAIK)
switch mode: hybrid (doesn't matter as well)
model match: Yes
dynamic power: Yes, 100mW limit
EdgeTX latest nightly (I update every week or so, with no change regarding this bug)
Baud: 1.87M

Telemetry values, RSSI and Qly are averages but don't change very much:
1RSS: -45dB
2RSS: 0dB
RQly: 98%
RSNR: 14dB
RFMD: 5
TPWR: 25mW-100mW
TRSS: -48dB
TQly: 98%
TSNR: 14dB

Thanks a lot for your efforts!

**Comment by pkendall64** [comment]
Thanks for all the details. I've gone through my collection of receivers and tested the BETAFPV lite and the Vantac and I have found that although the BETAFPV worked perfectly fine for me on you setting, the Vantac is not giving any telemetry back at all!
So that gives me something to look for, and hopefully this will clue us in to the problem.

**Comment by pkendall64** [comment]
I think I've found the problem!
The RX is using LBT as well, which means that if it thinks the channel is in use it will skip sending telemetry. The problem is worse on 150Hz because that particular mode has the longest on-air-time when transmitting and I think the RX is seeing RSSI on the channel and is skipping the telemetry send!

I noticed this because I initially had the RX compiled as ISM rather than LBT and there was no problem. Once I compiled the RX with LBT the problem raised its head instantly.

**Comment by froqstar** [comment]
The LQ displayed in the OSD only dips down to 97 or so when this problem occurs, so the TX seems to be unaffected by the problem?

Doesn't the TX/RX also only check the RSSI *before* transmitting, so the actual transmission time shouldn't make a difference since it comes after checking?
To me this sounds like the RX is picking the "wrong" point in time to check whether the channel is busy? 

If the problem is indeed on the RX, then your EdgeTX sync PR shouldn't have made a difference and it was just placebo on my part? I also did a testflight right now on 250Hz and I had the problem again, with the PR version on the TX. So just placebo/luck.

In the meantime, if I want to be EU compliant, a possible workaround would be to only use LBT firmware on the TX (as RQly seems unaffected) and ISM on the RX with the telemetry power limited to 10mW?

**Comment by pkendall64** [comment]
I did a lot more reading and testing last night and there are a couple of bugs in the LBT code.
1. When selecting 10mW the RX still does LBT. If the RX only has 10mW then it does not do LBT.
2. There is no compensation for the LNA on amplified RXes, so the level clear-channel code is too sensitive i.e. it's checking for an RSSI 12dB higher than it should!
I've got fixes for these bugs, but it still does not fix the issue with 150Hz. And I know it's timing based because if I change the LoRa coding rate from `LI 4/7` to `LI 4/6` which gives us a shorter on-air-time, the 150Hz mode is solid!

**Comment by pkendall64** [comment]
Can I get some testing and feedback on PR #1870 please. Hopefully this fixes the issues you guys are seeing with LBT mode.

**Comment by froqstar** [comment]
As commented in the PR, the fix looks like it is a fix indeed :) 
Simulator testing will hopefully follow in the evening.

Again thanks so much for looking into this!

**Comment by pkendall64** [comment]
> As commented in the PR, the fix looks like it is a fix indeed :) Simulator testing will hopefully follow in the evening.
> 
> Again thanks so much for looking into this!

You're more than welcome. Thanks for testing and creating such a good bug-report that made it reproducible.

**Comment by nightflasher** [comment]
I had the same issues before, I've just changed the tlm_report_interval_ms to 200LU and everything is fine. 
![Screenshot_20221009-222700](https://user-images.githubusercontent.com/3342605/194778117-4e158ce4-4513-47a3-aee1-9c368cb5da7a.jpg)

**Comment by froqstar** [comment]
@nightflasher your problem is most likely a separate problem that also affects ISM firmware and will be fixed with EdgeTX 2.8.

**Comment by Belly3D** [comment]
I am also having this issue.
Zorro Internal ELRS 3.0 ISM
100mW static
150Hz
Std Telem Ratio (tried higher ratios to no effect)
Hybrid switch
Default TLM Report Interval
BetaFPV nano receiver 3.0 ISM (100mW telemetry)

Getting the telemetry lost/recovered loop after a couple mins into a flight with good RSSI even when flying only 20m away.

**Comment by pkendall64** [comment]
There is a problem with 150Hz and LBT, in that there is not enough time window given the OTA parameters used for 150Hz. So the best option is to use 250Hz or the new 100Hz Full mode if you really need the range.

**Comment by CptLuki** [comment]
Interesting. I have exactly same behaviour as Belly3D and it is also not LBT. 

Tango 2 + Ghost Lite ELRS 3.0 ISM
250mW static
250Hz
Std Telem Ratio (tried higher ratios to no effect)
Hybrid switch
Default TLM Report Interval
Matek R24S 3.0 ISM (100mW telemetry)

Exactly same that once in the air getting this tlm lost/recovered loop like 10m away. Basically doing circles around myself. 

I noticed that both of us use receiver with LNA+PA. I wonder if this has something to do with it. There is no issue in 2.5.1. And again this is in ISM domain.

**Comment by pkendall64** [comment]
More changes have been added to the PR and it would be good if we could get some testing and feedback.

**Comment by froqstar** [comment]
@pkendall64 from your comments on the PR I understand that all RF modes (including FLRC) need re-testing, correct? 
Does it make sense to test 150Hz as well or is that a lost cause?

**Comment by pkendall64** [comment]
> @pkendall64 from your comments on the PR I understand that all RF modes (including FLRC) need re-testing, correct? Does it make sense to test 150Hz as well or is that a lost cause?

Yes, all modes should work now, and should be tested.

**Comment by Sekilsgs2** [comment]
But why all prs for 2.4 - im have troubles with 900 too - some times many telemetry lost , with 2.5.1 im never seen this. Any comments?

**Comment by pkendall64** [comment]
> But why all prs for 2.4 - im have troubles with 900 too - some times many telemetry lost , with 2.5.1 im never seen this. Any comments?

Because this is a ticket about LBT which is only supported on 2.4 currently.
Some of the changes in the PR will also help 900Mhz, but that has not been my focus as I've been trying to fix the problems reported in the ticket, which is LBT issues.

**Comment by Sekilsgs2** [comment]
> > But why all prs for 2.4 - im have troubles with 900 too - some times many telemetry lost , with 2.5.1 im never seen this. Any comments?
> 
> Because this is a ticket about LBT which is only supported on 2.4 currently. Some of the changes in the PR will also help 900Mhz, but that has not been my focus as I've been trying to fix the problems reported in the ticket, which is LBT issues.

Have one separate issue for 868 devices - please read and comment - why 2x have stable link but with 3.x we have many troubles - maybe problems in timings - changed in 3x ?

**Comment by Berlinologe86** [comment]
i have the same problem and a friend too 1.setup: frsky xlite+happymodel ex24pro on edgetx2.7 rx is a betafpv clone(150,250hz)tlm std.output power dynamic and static 500/1000mw tested 2. setup jumper tpro on edgetx2  .7 rx are original betafpv nano/lite modules(150-250hz) output power static 500/1000mw ans dynamic. Team 2.4

**Comment by pkendall64** [comment]
> i have the same problem and a friend too 1.setup: frsky xlite+happymodel ex24pro on edgetx2.7 rx is a betafpv clone(150,250hz)tlm std.output power dynamic and static 500/1000mw tested 2. setup jumper tpro on edgetx2 .7 rx are original betafpv nano/lite modules(150-250hz) output power static 500/1000mw ans dynamic. Team 2.4

Ok, so can you test the PR #1870 to see if it fixes the problem for you and report on the PR with your findings please.

**Comment by Berlinologe86** [comment]
But we have flashed ism

**Comment by froqstar** [comment]
@Berlinologe86 can you try updating to EdgeTX 2.8 and test again? It includes a fix for handset/module communication.
Alternatively you can try setting the telemetry report interval in the module ELRS  firmware options to 200, which should also improve telemetry reliability.

**Comment by BorisDess** [comment]
Issue encountered as well with TX16S MKII and GEPRC nano SE, both flashed with ELRS 3.0.

**Comment by Berlinologe86** [comment]
I have test ist today edgetx2.8 rc3 with The Same settings. telemetry lost is still there.  I noticed that despite a dbm of -64, my jumper then has to boost to 500mw at a distance of less than 200 meters🙄Von meinem iPhone gesendetAm 19.10.2022 um 06:55 schrieb Boris D. ***@***.***>:﻿
Issue encountered as well with TX16S MKII and GEPRC nano SE, both flashed with ELRS 3.0.

**Comment by pkendall64** [comment]
> I have test ist today edgetx2.8 rc3 with The Same settings. telemetry lost is still there.  I noticed that despite a dbm of -64, my jumper then has to boost to 500mw at a distance of less than 200 meters🙄Von meinem iPhone gesendetAm 19.10.2022 um 06:55 schrieb Boris D. ***@***.***>:﻿ Issue encountered as well with TX16S MKII and GEPRC nano SE, both flashed with ELRS 3.0. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

This has not been released yet! Did you flash the PR for testing?

**Comment by atagunov** [comment]
Not much knowledge/time to test custom builds but I'm seeing the issue with 3.0.1 ExpressLrs on BetaFpv LightRadio 3 Pro with ExpressLrs 2.4 GHz internal module + Matek 24 RX I'm having a telemery lost loop with the quad just sitting on my table a few centemeters from the RX. REGULATORY_DOMAIN_EU_CE_2400, TLM_REPORT_INTERVAL set to 100LU.

**Comment by nigerninja** [comment]
Hi, 
Thanks to the ELRS team looking at this.
I also have the same issue with the telemetry lost/recovered endless loop:

TX: Radiomaster Zorro EdgeTX 2.7.0, internal elrs
RX: BetaFPV ELRS Lite
ELRS v3.0.1, 150 Hz (1:32, 1:16), 250Hz (1:128)
TX Power 100mW Dynamic Off EU_CE_LBT

For what it's worth, just got a quad and spent the whole day setting up and getting familiar with BF and didn't start getting that loop until how at least 3 - 4 hours after. Initially thought I messed up something in BF but saw similar reports online. I'll try an ISM build in a bit.

Thanks.

**Comment by nigerninja** [comment]
A quick update, ISM works perfectly no telemetry losses in the last hour or so.

Thanks.

**Comment by tfranzel** [comment]
Can confirm that updating from **3.0.1** to **3.1** fixed the issue. no more "Telemetry lost/telemetry recovered". thanks a lot :heart: 

TX: Radiomaster Zorro EdgeTX 2.7.1, internal elrs
RX: Radiomaster EP1 
ELRS v3.1 regulatory domain EU CE

**Comment by Dosclic98** [comment]
Having the same issue on the ISM regulatory domain version, but seems less present and with telemetry at 1:4, 500Hz and 250mW it happens just at range, while on version 2.5 I never had any issue.

OS: EdgeTX 2.8.0
TX: BetaFPV 2.4GHz Micro TX module 
RX: Happymodel EP1
ELRS v3.0.1 regulatory domain ISM

**Comment by j-keiter** [comment]
> Can confirm that updating from **3.0.1** to **3.1** fixed the issue. no more "Telemetry lost/telemetry recovered". thanks a lot heart
> 
> TX: Radiomaster Zorro EdgeTX 2.7.1, internal elrs RX: Radiomaster EP1 ELRS v3.1 regulatory domain EU CE

How do I upgrade to ELRS 3.1.  I only see 3.0.1 in the Releases?  I saw the 3.1 label on this page but don't know what it means?

**Comment by pkendall64** [comment]
3.1 had a nasty bug caused by the base platform on some Windows systems. 3.1.1 will be released very soon. If you are willing to test, then flash branch 3.x.x-maintenance.

**Comment by j-keiter** [comment]
> 3.1 had a nasty bug caused by the base platform on some Windows systems. 3.1.1 will be released very soon. If you are willing to test, then flash branch 3.x.x-maintenance.

Nope!  I installed 3.x.x.x-maintenance on both Happymodel ES24TX Pro 2400TX transmitter module and my Matek 2400 RX R24D receiver.  Power on everything looks good for about 30s then Sensor lost, no more flight controller telemetry and it never recovers.  I have to cycle power on rcvr to get FC telemetry back but again after 20-30s I get sensor lost.

**Comment by pkendall64** [comment]
> > 3.1 had a nasty bug caused by the base platform on some Windows systems. 3.1.1 will be released very soon. If you are willing to test, then flash branch 3.x.x-maintenance.
> 
> Nope! I installed 3.x.x.x-maintenance on both Happymodel ES24TX Pro 2400TX transmitter module and my Matek 2400 RX R24D receiver. Power on everything looks good for about 30s then Sensor lost, no more flight controller telemetry and it never recovers. I have to cycle power on rcvr to get FC telemetry back but again after 20-30s I get sensor lost.

The Matek R24D has capacitors next to the 52Mhz xtal which should not be there and cause the RX to lose link.
Could you ask on discord in the #help-and-support channel and I'm sure people there will provide information/help.

**Comment by pkendall64** [comment]
> I just finished connecting a Happy Model EP2 receiver and flashing 3.x.x-maintenance to it. It worked for about 60s then sensor lost and no more flight controller telemetry. Receiver still works. I get receiver telemetery eg. 1RSS 2RSS etc but no FC telemetry. So both happymodel and matek receivers exhibit same issue.

I've flashed a HM ES24 Pro TX and an EP2 with the 3.x.x (LBT enabled) connected to a JB F4 flight controller and have had FC telemetry for the last 40 minutes.  I have it set to 500Hz 1:16 telemetry ratio. CRSF baud rate is 3.75M FYI. Did you ask on discord like I said, because I haven't seen this issue on the channel.

**Comment by j-keiter** [comment]
> > I just finished connecting a Happy Model EP2 receiver and flashing 3.x.x-maintenance to it. It worked for about 60s then sensor lost and no more flight controller telemetry. Receiver still works. I get receiver telemetery eg. 1RSS 2RSS etc but no FC telemetry. So both happymodel and matek receivers exhibit same issue.
> 
> I've flashed a HM ES24 Pro TX and an EP2 with the 3.x.x (LBT enabled) connected to a JB F4 flight controller and have had FC telemetry for the last 40 minutes. I have it set to 500Hz 1:16 telemetry ratio. CRSF baud rate is 3.75M FYI. Did you ask on discord like I said, because I haven't seen this issue on the channel.

Discord cuts off part of your post.  The only way for me to read your post is click the post link which brings me back to github.  I will ask on Discord as you suggested after trying all your suggestions. I've been using the non-LBT(Listen Before Talk) version of firmware. In other words I'm using the international version. I'm trying to avoid using the EU LBT version of firmware as it limits power to 100mW but I will eventually to see of this dropped FC telemetry issue goes away.  I've been changing packet rate, telemetry ratio tx power, module baud rate, etc.  Nothing works.

**Comment by MartinHugh** [comment]
I am getting a Telemetry Lost loop with 3.1.1. (just flashed to a Matek P24-P6)
Are there any circumstances where I should be expecting this?

**Comment by pkendall64** [comment]
When this happens it it sometimes required to fully erase the flash before flashing.
Try using my web flasher https://pkendall64.github.io/elrs-web-flasher/ and on the last page after it's connected to the device check the option to erase flash.

**Comment by pkendall64** [comment]
They are ESP8285 so you can't really "brick" them. You might have to bridge the boot pad/press the boot button when powering and try UART flashing. Sometimes the esptool just doesn't connect and you have to re-power the device and try again.

**Comment by MartinHugh** [comment]
Thanks will try that. Though it is not a quick process to remove the RXs from the aircraft and set them up for UART flashing.  There is a big difference between these particular RXs and the EP1/RX1 which all updated fine.  Will dig out my FTDI adapter and see if I can flash directly. Thanks for your response.

**Comment by MartinHugh** [comment]
OK reporting back.  At some point this might be better raised as a new issue, but the 'no telemetry' loop is at the heart of this.

I attempted many times to flash from the ELRS Configurator, but it complained it could not open the COM port. 
The COM port was correct, TX/RX were wired correctly, the boot pad was held pressed before power up

I eventually tried ESPHome-flasher, that did report some issue with the COM port, but said it was going into erase mode, it then did flash the firmware.

I was now able to connect ELRS Configurator over wifi and noticed that the erase process had wiped the model number and PWM settings (but not the bind phrase?).  I reset those and attempted to connect the TX to the RX.

It worked for a moment and then started cycling 'telemetry lost'

Using 
TX16S with HappyModel TX24 on LBT 3.1.1.
Matek P24-P6

Flashing DIY DIY_2400_RX_PWMPEX-3.1.1

Any thoughts, should I raise this as a separate issue ?

So I can now bind again, but am back to

**Comment by pkendall64** [comment]
@MartinHugh perhaps comment on issue #1988 which seems to be the same problem you are having.

**Comment by MartinHugh** [comment]
@pkendall64 Many thanks for reading and for your suggestion. I will comment on that issue.

**Comment by CptLuki** [comment]
@pkendall64 after long time I updated from 2.5.1 to 3.2.1 to see the situation. Telemetry lost/recovered loop still present. Starts right after arming and quad sitting 2m away. But this is NOT LBT. Was flashed with ISM domain. Can this be isolated to Ghost module somehow? Or Tango 2 radio FW? But 2.5.1 works perfect.

Specs:
Tango 2 + Ghost Lite ELRS 3.2.1 ISM
250mW static
250Hz
Std Telem Ratio (tried also 1:16)
Hybrid switch
Default TLM Report Interval
Matek R24S 3.2.1 ISM (100mW telemetry)

**Comment by R5fan** [comment]
Im seeing the same as @CptLuki. I flashed my 1000mW betafpv transmitter to 3.2.1 ISM, as well as my betaftp AIO receiver.

I tried various power settings from 25 to 500mW, with and without dynamic power, various update frequencies, I also played with TLM_REPORT_INTERVALS_MS, but so far nothing helps. I will try downgrading the firmware and report back if that solves it.

Im new to ELRS.  One thing I was surprised by was that even at close range my receiver isnt reporting very high RSSI values (through betafpv OSD).  Flying in my garden at a few to a few 10s of meters, Im seeing 60-70%, rarely more, even if I force higher tx power.

**Comment by R5fan** [comment]
Parallel discussion here:
https://github.com/ExpressLRS/ExpressLRS/issues/608

There it is suggested to change the baudrate of the radio from 400K to 115200 or enable "onebit". Not sure what the latter means?, but changing the baudrate so far seems to work. Not sure what Im losing with the lower baudrate, but its probably not a big deal for me. Ill test more and report back.
