### ISSUE TITLE
Jhemcu ELRS SP24S incompatible with  Jumper AION TX?

### ISSUE THREAD

**Issue by Dist0rtion** [ExpressLRS/ExpressLRS#1838]
## Current Behavior

I have a Radiomaster TX16S with the Happymodel ES24TX module, with current ExLRS firmware (3.0.0)
And I have a Jumper T-Pro with the Happymodel ES24TX module, also latest firmware. - Both are running EdgeTX

As receiver I use the Jhemcu ELRS SP24S (Ceramic Antenna)

Now to my problem.
I can connect with the Happymodel ES24TX without problems with the receiver, but with the T-Pro and the Jumper AION TX module I can not connect, it will not bind.

I have tried different settings (packet size, output power, etc) on the ExLRS module but without success, I can not connect the Jhemcu ELRS SP24S receiver to the AION TX module.

I have other ExLRS receivers from Happymodel, GepRC, Matek, and with these the AION module works without problems.

## Details
I also tried changing the firmware on the receiver.
The DIY version and in the Configurator specific setting for the Jhemcu ELRS SP24S.

## Your Environment
- TX hardware:  Jumper AION TX / Happymodel ES24TX
- RX hardware: Jhemcu ELRS SP24S
- Handset model: Jumper T-Pro / Radiomaster TX16S
- OpenTX version (including nightly number): EdgeTX
- ExpressLRS version (TX & RX MUST MATCH): 3.0.0
- Packet Rate:
- Telemetry Ratio:
- user_defines:

**Comment by pkendall64** [comment]
This is a quality issue with the JHEMCU receivers. They have used an under spec'd crystal oscillator and it will not bind to many different transmitter modules. This is also duplicate if #1229
