### ISSUE TITLE
Script Syntax Error - elrsV3 Lua:489

### ISSUE THREAD

**Issue by skunkwurk** [ExpressLRS/ExpressLRS#1864]
This issue is easy to replicate.   When I enable WiFi using V3lua, I get the syntax error in the image.  If I enable WiFi using v2lau, it works fine.  Take a look at the pic, thanks in advance for the support. 

Setup:
- Radio - TX16S MK2
- Radio firmware: 2.8.0
- ES24TX Pro Micro ExpressLRS TX on ver 3.0.0 SM2G4 8aa1b0
- I downloaded the firmware and the lua using configurator v1.5
 
![IMG_4590](https://user-images.githubusercontent.com/114449107/193375979-712fc386-ddf7-4dd5-a39c-e5b0ab27eb92.JPG)

**Comment by skunkwurk** [comment]
Has anyone had a chance to look at this?  I can provide a copy of the script or other details.

**Comment by pkendall64** [comment]
You would be better to ask on discord in the #help-and-support channel as this is not a bug with the Lua script, as many users have this on their radios and have no problem. I'd suggest going to the web-ui on the TX module and clearing all settings and trying again.

**Comment by skunkwurk** [comment]
Hi, thanks for the suggestion.  I'll try to ask in the support channel.  I have cleared the TX. It works fine on V2, it crashed when using V3 lua only.  It's def behaving like a bug.

**Comment by skunkwurk** [comment]
Is this still the link?  https://discord.gg/expresslrs 

I keep getting invalid.

**Comment by pkendall64** [comment]
Try this https://discord.gg/dS6ReFY seems discord is having issues with our custom link!

**Comment by skunkwurk** [comment]
Thanks.  I was able to find the support group and we resolved the issue.  I had to
 bump up the baud rate.
