### ISSUE TITLE
ES24TX Pro 2400 failed to upgrade to V3.0

### ISSUE THREAD

**Issue by ac2022cv** [ExpressLRS/ExpressLRS#1868]
Tranranis Q7Xs Access
OpenTX version:  2.3.15-otx (1004ef7c)
HappyModel ES24TX_Pro_Series_2400_TX

Wifi/Web page Upgrade failed twice.   
1st popup error message:   Targets Mismatch current target: HAPPYMODEL_ES24TX_PRO_SERIES_24_TX.  Flashing the wrong firmware may lock or damage your device. button "flash anyway" "cancel".
2nd popup error message after I chick on "flash anyway":   Force update Bad Size Given.

I have used the same device category: Happymodel 2.4 GHz and Device: HM ES24TX Pro Series 2400 TX upgrade to 2.5.1.  Configurator generation of .bin file was success.

**Comment by pkendall64** [comment]
There are instructions in the release notes about what to do if you get "Bad Size Given".
The best place to ask for help if you run into issues is discord, on the #help-and-support channel, then folk there are really friendly and knowledgable.
