### ISSUE TITLE
Wrong TX power is set on boot

### ISSUE THREAD

**Issue by SunjunKim** [ExpressLRS/ExpressLRS#1877]
## Current Behavior
When Max power is set lower than the `power_default` defined in the hardware descriptor, it's set to the default power on boot instead of the set Max power.

## Steps to Reproduce

1. Set the Max power to the minimum power available in Lua script, and disable dynamic power
2. Power cycle
3. Observe the output power (using RF meter), which is set to `power_default` instead of the set power in the Lua.

## Your Environment
- TX hardware: ESP32 2.4g 1W module (min power 25 mW)
- RX hardware: Not relevant 
- Handset model: TX16S, TX12
- OpenTX version (including nightly number): >ETX 2.7
- ExpressLRS version (TX & RX MUST MATCH): master (bad7d1)
- Packet Rate: Not relevant 
- Telemetry Ratio: Not relevant 
- user_defines: Not relevant

PS. I don't have time to investigate this issue in near future, so I just report it here for now

**Comment by MartinHugh** [comment]
Assuming I understand the scenario you are describing : 
I think this is expected behaviour when you turn the TX on *after* the RX.

The rationale, I imagine, is that if you have failsafed and then reestablishe connection, you want the power to be at the maximum permitted.  This is in contrast to when you turn the TX on *before* the RX when you will have minimum power.

**Comment by SunjunKim** [comment]
> Assuming I understand the scenario you are describing : I think this is expected behaviour when you turn the TX on _after_ the RX.
> 
> The rationale, I imagine, is that if you have failsafed and then reestablish connection, you want the power to be at the maximum permitted. This is in contrast to when you turn the TX on _before_ the RX when you will have minimum power.

I appreciate your effort, but your comment is not relevant to this issue.
