### ISSUE TITLE
ExpressLRS configurator Build Error - compilinf terminated : xtensa-esp32-elf-g++: fatal error: no input files

### ISSUE THREAD

**Issue by ArpyOblonk** [ExpressLRS/ExpressLRS#1887]
## Current Behavior

ExpressLRS failed to build. Already uninstall and reinstal several time also with "clear platformio dependencies" & "clear firmware Files". 

Any solution for this?

## Steps to Reproduce

Compiling .pio\build\HappyModel_ES24TX_2400_TX_via_WIFI\src\common.cpp.o
Compiling .pio\build\HappyModel_ES24TX_2400_TX_via_WIFI\src\dynpower.cpp.o
xtensa-esp32-elf-g++: fatal error: no input files
compilation terminated.
Compiling .pio\build\HappyModel_ES24TX_2400_TX_via_WIFI\src\hal\hal_stm32.cpp.o
xtensa-esp32-elf-g++: fatal error: no input files
compilation terminated.
*** [.pio\build\HappyModel_ES24TX_2400_TX_via_WIFI\src\common.cpp.o] Error 1
Compiling .pio\build\HappyModel_ES24TX_2400_TX_via_WIFI\src\rxtx_common.cpp.o
*** [.pio\build\HappyModel_ES24TX_2400_TX_via_WIFI\src\dynpower.cpp.o] Error 1
xtensa-esp32-elf-g++: fatal error: no input files
compilation terminated.
*** [.pio\build\HappyModel_ES24TX_2400_TX_via_WIFI\src\hal\hal_stm32.cpp.o] Error 1
xtensa-esp32-elf-g++: fatal error: no input files
compilation terminated.
*** [.pio\build\HappyModel_ES24TX_2400_TX_via_WIFI\src\rxtx_common.cpp.o] Error 1
========================= [FAILED] Took 39.14 seconds =========================

Environment                         Status    Duration
----------------------------------  --------  ------------
HappyModel_ES24TX_2400_TX_via_WIFI  FAILED    00:00:39.138
==================== 1 failed, 0 succeeded in 00:00:39.138 ====================

1.

2.

3.

4.

## Your Environment

- TX hardware: HHappyModel_ES24TX_2400
- RX hardware:  - 
- Handset model: -
- OpenTX version (including nightly number)
- ExpressLRS version (TX & RX MUST MATCH): -
- Packet Rate: -
- Telemetry Ratio: -
- user_defines:

**Comment by pkendall64** [comment]
This question would be best asked in the #help-and-support channel on discord and I'm sure the friendly folk there will get you sorted. I'm going to close this as it's not a software bug.
