### ISSUE TITLE
My Betafpv PWM Rx signal lost

### ISSUE THREAD

**Issue by Tonampoae** [ExpressLRS/ExpressLRS#1890]
My beta fpv pwm rx i use firmware of nano rx version 3.0.0 to fly fpv, signal lost and fall from a distant area about 330 feet how do fix it.

**Comment by pkendall64** [comment]
Please join discord and ask in the #help-and-support channel. Opening an issue like this with no information is not going to get you any help. If you ask in the #help-and-support channel the friendly folk there will be more than willing to help you diagnose resolve the issue.
