### ISSUE TITLE
Unified_ESP32_2400_TR target on rx_vtx

### ISSUE THREAD

**Issue by jurgelenas** [ExpressLRS/ExpressLRS#1902]
It looks like it should be Unified_ESP32_2400_RX?

Permalink: https://github.com/ExpressLRS/ExpressLRS/blob/bad7d1a6deaa1196311b04134c9878e82be6af43/src/hardware/targets.json#L536

**Comment by pkendall64** [comment]
Thanks @jurgelenas, I updated the target validator PR to detect this and fixed it in that PR as well.
