### ISSUE TITLE
Micro 2.4Ghz Tx USB fail

### ISSUE THREAD

**Issue by Hex-Davis** [ExpressLRS/ExpressLRS#1907]
My Micro Tx no longer connects to my computer. After plugging in, device manager shows no change in connections, and the OLED doesn’t turn on.

This happened after trying to update the firmware. First I got the “bad size” message, so did the repartition flash and now it not working.

 I applied power with a 2s battery, tried connecting through the transmitter and the USB port. Wi-Fi doesn’t work as the device isn’t powered up? The dip switches are off with the exception of 3 and 4.

**Comment by pkendall64** [comment]
It would be better if you ask in the #help-and-support channel on Discord and I'm sure the friendly folk there can help you out. The issue tracker on github is more for software bugs. Thanks.
