### ISSUE TITLE
RX automatically restart after Android browser refreshes(F5) the page (3.0.1)

### ISSUE THREAD

**Issue by CCNUI** [ExpressLRS/ExpressLRS#1920]
## Current Behavior

I recently bought a Matek pwm receivers and updated to v3.0.1 official. Once I use Android phone to connect to  ExpressLRS_RX WiFi, opened 10.0.0.1. The receiver will close WiFi and Reboot after I press refresh(F5) button on browser and finished page load.

## Steps to Reproduce

0.Flash to MATEK_2400_RX_PWM-3.0.1 via WIFI with default setting without bind phrase

1.Power on Matek PWM receiver

2.Bind to TX

3.Open RX Wifi by TX stript

4.Join ExpressLRS_RX Wifi by Android phone

5.Open Web Browser and go to 10.0.0.1

6.Press Refresh(F5) button on browser after page loading

7.Now receiver automally Reboot and connect to TX normally

## Details

Maybe add an "Reboot" button on the Second page. And cancel automally Reboot after page loading.  Because if I use “Save & Reboot" button on the first page. It maybe set  UID or binding_phrase by misoperation.

## Your Environment

- TX hardware: BETAFPV 2400 TX Micro 1000mW
- RX hardware: Matek 2400 RX PWM
- Handset model: Redmi Note 9 Pro
- OpenTX version (including nightly number) edgetx-tx16s 2.7.1 (a55aff02)
- ExpressLRS version (TX & RX MUST MATCH): 3.0.1 official

- Android version: 12 SKQ1.211006.001
- Browser version: Microsoft Edge(Android) 104.0.1293.63

**Comment by pkendall64** [comment]
Can you please ask for help on the discord #help-and-support channel, as this is not a bug in the firmware as many users have this and other devices and this problem does not occur.
