### ISSUE TITLE
Happymodel ES915TX/RX

### ISSUE THREAD

**Issue by DangerD1024** [ExpressLRS/ExpressLRS#1925]
For TX there's no option to flash by UART using USB port inside
![image](https://user-images.githubusercontent.com/4560434/199205349-82d25d5a-0c79-430d-a07d-93cd5a02a4cd.png)
For RX no option to flash using WIFI however it starts WIFI hotspot
![image](https://user-images.githubusercontent.com/4560434/199205517-b8ed190e-22be-4e23-a825-16f143b3fff5.png)
Tried to build for ES900RX and upload it, but it shows error: `Update error: ERROR[10]: Magic byte is wrong, not 0xE9`
How can i update firmware for it? I don't have STLink and betaflight FC...

**Comment by pkendall64** [comment]
Please ask on discord in the #help-and-support channel. I think you'll find that you are choosing the wrong device to flash.
