### ISSUE TITLE
Constant Failsafes in Ardupilot with V3.0.1!

### ISSUE THREAD

**Issue by AaryanL** [ExpressLRS/ExpressLRS#1927]
## Current Behaviour

After 6-7 min from start Ardupilot reports repeating short FS every couple of minutes!
![Screenshot_1](https://user-images.githubusercontent.com/84386055/199529924-c1f089e2-433c-40ac-8335-214ebf297279.png)

## Steps to Reproduce

1. Just switch all on and wait )

## Details

1. Why is it the problem with ELRS - because if I use this setup and change only one thing - ELRS FW version to 2.5.1 - NO ANY FS any more, with exactly the same settings.
2. Problem disappears if Telemetry ratio is higher than 1:4 ( 1:2 and 1:4 - problem exists with Packet rate = 500 ).
3. Problem disappears if Packet rate <= 150 ( and Telemetry ratio = 1:2 ).
4. Absolutely ALL HW were replaced with the similar one and the problem reproduced.

## Your Environment

- Omnibus F4V3 + GPS at SERIAL3
- Arducopter 4.3.0 all default settings except of SERIAL1 SERIAL_PROTOCOL = 23, RC_OPTIONS = 800

- Taranis X9 lite
- OpenTX version 2.3.15
- ExpressLRS version 3.0.1 
- Matek RX with removed caps, link freq test passed

![ELRS](https://user-images.githubusercontent.com/84386055/199531982-71bb6cc9-913a-4eeb-aaa9-4439b2e27004.png)
![Screenshot_31](https://user-images.githubusercontent.com/84386055/199531981-afe65cad-76e3-431f-8bf8-47ec7f4bcb8a.png)
![Screenshot_32](https://user-images.githubusercontent.com/84386055/199531991-2b44ad9a-5e1e-475e-be8c-e5ef3565c0b9.png)

**Comment by pkendall64** [comment]
Why have you raised another ticket? Please add this information to the other ticket and well close this one.

**Comment by AaryanL** [comment]
Because I've closed the old one. It has a lot of useless info concerning the issue. 

> Why have you raised another ticket? Please add this information to the other ticket and we'll close this one.

**Comment by pkendall64** [comment]
It is better to leave the original ticket open and add this information to it as it shows the history of information gathering and things that have already been tried.

**Comment by AaryanL** [comment]
Done.
