### ISSUE TITLE
When servosFailsafe occurs, the pwm output of somOnOff mode is incorrect

### ISSUE THREAD

**Issue by JumperShao** [ExpressLRS/ExpressLRS#1935]
## Current Behavior

When servosFailsafe occurs, the pwm output of somOnOff mode is incorrect

## Steps to Reproduce

1. set one PWM channel mode to OnOff

2. tune off the transmitter

3. the OnOff channel start output the PWM signal.

## Possible Solution (Not obligatory)

modify the servosFailsafe() like this:

static void servosFailsafe()
{
    constexpr unsigned SERVO_FAILSAFE_MIN = 988U;
    for (unsigned ch=0; ch<servoMgr->getOutputCnt(); ++ch)
    {
        const rx_config_pwm_t *chConfig = config.GetPwmChannel(ch);
        // Note: Failsafe values do not respect the inverted flag, failsafes are absolute
        uint16_t us = chConfig->val.failsafe + SERVO_FAILSAFE_MIN;
        // Always write the failsafe position even if the servo never has been started,
        // so all the servos go to their expected position

		// JumperShao Test, 2022.9.21
		if ((eServoOutputMode)chConfig->val.mode == somOnOff)
			servoMgr->writeDigital(ch, us > 1500U);
		else
			servoMgr->writeMicroseconds(ch, us / (chConfig->val.narrow + 1));
		
    }
}

## Your Environment

- TX hardware:  Jumper AION NANO 2400 TX
- RX hardware:  MATEK 2400 RX PWM
- Handset model: Jumper T-Pro
- OpenTX version (including nightly number) 2.3.15
- ExpressLRS version (TX & RX MUST MATCH): 3.0.0/3.0.1
- Packet Rate: 
- Telemetry Ratio:
- user_defines:

**Comment by pkendall64** [comment]
This is already fixed in master, which will become 3.1 in coming days/weeks

**Comment by JumperShao** [comment]
Great!
