### ISSUE TITLE
Not able to Flash QK NANO RX 2400 with ELRS V3

### ISSUE THREAD

**Issue by satyagupta** [ExpressLRS/ExpressLRS#1950]
Not able to flash QK Nano Receivers with target QK NANO RX with ELRS v3.0

Try to build using elrs configurator with Target QK NANO RX (QuadKopters > QK NANO Rx)

![image](https://user-images.githubusercontent.com/443536/202076238-66fe0f76-6adf-4a0d-bf0c-c7e45add643f.png)

Works fine with V2.0 but not with V3.0

**Comment by pkendall64** [comment]
We've fixed this and it will be released in 3.1, which should hopefully be very soon.

**Comment by satyagupta** [comment]
Thanks @pkendall64 i hope it comes out sooner

Users are not able to flash thinking its a hardware issue and moving to different hardware :(

**Comment by pkendall64** [comment]
> Thanks @pkendall64 i hope it comes out sooner
> 
> Users are not able to flash thinking its a hardware issue and moving to different hardware :(

We are talking about this week. We noticed this the other day and I wrote a new verifier that runs on the github build so this should not happen again.

**Comment by satyagupta** [comment]
Excellent, you guys are best!

**Comment by satyagupta** [comment]
Any update on this guys?!

**Comment by deadbytefpv** [comment]
> Any update on this guys?!

https://github.com/ExpressLRS/ExpressLRS/pull/1922

I think this can be closed now.. :D
