### ISSUE TITLE
LUA Script error on PWM Receiver

### ISSUE THREAD

**Issue by gjhaynes** [ExpressLRS/ExpressLRS#1955]
## Current Behavior

Viewing the Rx parameters of a Matek R24-P6 on a TX16S using the ExpressLRS script results in a script error
## Steps to Reproduce

1. Flash the Rx with ELRS v3.1.0

2. Execute the ExpressLRS LUA script (v3) on the TX16S

3. Choose "Other Devices and select the ELRS+PWM 2400RX

4. At the point where Output Mapping should be displayed, a script error occurs: 

![screen-2022-11-20-100638](https://user-images.githubusercontent.com/27730604/202882151-5fe227b2-1fbd-47a2-ba4b-9d6dfa20a395.jpg)

## Details

The problem appears related to the new feature in ELRS 3.1.0 that displays channel mapping for PWM receivers

Unable to view Rx properties or edit channel mapping from the handset using the ELRS script

No changes to boilerplate

## Your Environment

- TX hardware: Happymodel ES24TX Pro 1000mW Micro ExpressLRS 2.4GHz ELRS TX
- RX hardware: Matek R24-P6
- Handset model: RadioMaster TX16S
- EdgeTX version (including nightly number): 2.8 RC4
- ExpressLRS version (TX & RX MUST MATCH): 3.1.0
- Packet Rate: 400K (error persists if rate is changed)
- Telemetry Ratio: 1:16 (error persists if ratio is changed)
- user_defines:

**Comment by paulkidd68** [comment]
I'm Getting the same error on a Radiomaster TX16S with a BetaFPV PWM receiver too.

**Comment by ajjjjjjjj** [comment]
It might be related - I found out that "Output mode" menu item is not sending last 2 bytes in packet so unit "\0" is not existent.

**Comment by pkendall64** [comment]
Hi there, we have a PR in place if you'd like to test and provide feedback. #1962

**Comment by jurgelenas** [comment]
@pkendall64 should we close this? It was fie din #1962
