### ISSUE TITLE
No channels on R9MM after update to 3.1

### ISSUE THREAD

**Issue by macgyverek** [ExpressLRS/ExpressLRS#1957]
## Current Behavior

After update R9M and R9MM to 3.1 working only telemetry.  Stick movement not changing a channel values. After all I returned to 3.01 and all working without issue. 

## Steps to Reproduce

1. Flash R9M and R9MM to 3.1

2. Turned on and off model match, becasue ist a mismatch model info

3. Open Betaflight configurator and check channel movment. Not working. 

4. Back only R9MM to 3.01 - channels are working. 

## Your Environment

- TX hardware: R9M
- RX hardware: R9MM
- OpenTX version (including nightly number): up to date
- ExpressLRS version (TX & RX MUST MATCH): 3.1
- Packet Rate: 200Hz
- Telemetry Ratio: 32Hz

**Comment by pkendall64** [comment]
Wwe are aware of this problem and it is fixed in 3.x.x-maintenance branch. There will be a 3.1.1 release shortly to fix this.
