### ISSUE TITLE
ExpressLRS v3.0.1 sends different rc data without user command which is causing disarm and motor glitch momentarily

### ISSUE THREAD

**Issue by ckflight** [ExpressLRS/ExpressLRS#1960]
Today i have updated my HappyModel ES24TX, HappyModel EP1 2400 RX to 3.0.1 and Taranis QX7 to latest OpenTX version. 

Besides having "not enough space" error during wifi update (i have updated by using usb interface), receiver gets different data sometimes. I am not touching to Taranis QX7 and it is standing still but it receives different values. 

The parsed crsf data output can be seen from the first picture. This sudden change in the received data causes drone to do glitch like behaviour or even crash.

I have tried other output rates such as 250, 500, D500, F500 and result is the same also faster update rate causes failsafe telemetry loss. I had no issues when i was using versions around 2.1.0

I am a drone specialist and i get the screenshots from my flight controller code parallel to betaflight and the below picture is the usb debug output of raw crsf rc data where min value is 880 when no usefull data is received since crsf protocol is calculating channel data by ((x) * 5 / 8 + 880) equation. Failsafe condition is set when the received signal is weaker then -120dBm which is indicated by crsf link statistics frame as well.

The RC channel order is Roll, Pitch, Yaw, Throttle, Aux1, 2, 3... and failsafe flag at last.

**I will write some code to get rid of this unwanted data but maybe this can be a bug so i wanted to report it by opening an issue.**

**Later update after further investigation: Some data is different because of failsafe (check the second screenshot where last bit is 1 which means failsafe) but others are different even if the failsafe flag is 0. So after update i think the uplink is more fragile** 

![Untitled](https://user-images.githubusercontent.com/61315249/203100889-67b68b04-5d77-4967-9b98-3b51e4c5d986.png)
![Untitled](https://user-images.githubusercontent.com/61315249/203124109-ee22273f-b9b5-4f58-ae74-ea514579b49b.png)

**Comment by AlexKlimaj** [comment]
Did you figure out what was causing this? I am seeing it on 3.1.2

![image](https://user-images.githubusercontent.com/2019539/212409843-6a215417-2da5-41c3-ae7e-6e55e583ed62.png)

**Comment by ckflight** [comment]
Hi, it is definitly software related because i did not have any issue when i was using elrs version 2 firmware. I think the link quality in version 3 is bad and it has a failsafe for a moment As a solution on my flight controller software i simply reject the corrupt data. The corrupt data has for example 900 as a aux value which should be 1000 to 2000 so when it send such data the code ignores. And there is 10 15 packets every second like that. The corrupt data has same format and values so you can observ them by ploting received data.
