### ISSUE TITLE
QX7 Lua 3.1.1 betafpv micro tx

### ISSUE THREAD

**Issue by Kasg04** [ExpressLRS/ExpressLRS#1989]
## Current Behavior
lua script is freeze on loading

When tring to run lua script v3 its freeze on loading
## Steps to Reproduce
After upgrade betafpv micro tx to 3.1.1 , i cant run lua script v3

1.

2.

3.

4.

## Your Environment

- TX hardware:micro tx betafpv
- RX hardware: 
- Handset model: qx7
- OpenTX version (including nightly number) latest
- ExpressLRS version (TX & RX MUST MATCH): 3.1.1
- Packet Rate:25p
- Telemetry Ratio:1:2
- user_defines:

**Comment by stevewitwitty** [comment]
I had a problem similar to this, I had to change the baud rate to 400k. Originally it was set to 115k and lua script froze. After I changed the baudrate to 400k it worked fine. Maybe worth a try

**Comment by Kasg04** [comment]
I reduce the refresh rate to 100mhz and every thing is working right now

**Comment by Kasg04** [comment]
> Joshua Bardwell has a video covering errors like this. See link and go to approx 10.30 on video: [Bardwell video express LRS](https://youtu.be/cyILQqxPpZI)

Thamk You!
