### ISSUE TITLE
Connected but no stick input

### ISSUE THREAD

**Issue by noflightgame** [ExpressLRS/ExpressLRS#2008]
I got a new tx12s radio with betafpv 1-watt micro module. Upon receiving the radio I'm guessing the internal module is dead or non-responsive, says failed header packet when trying to flash. I was able to use the external module to connect to the receiver & to use lua script, both module & receiver have the latest firmware update. In lua script I have a "C" showing I'm connected, but when setting up beta flight it is displaying no valid receiver signal. Any help is greatly appreciated, I also have X-12 AIO for my whoop & it's also experiencing the same issue. Please help!!

**Comment by pkendall64** [comment]
Please ask on the discord server in the #help-and-support channel.
