### ISSUE TITLE
Add Happymodel EPW5 2400 PWM Target

### ISSUE THREAD

**Issue by Mkorho** [ExpressLRS/ExpressLRS#2048]
Happymodel EPW5 is still using DIY_2400_RX_PWMP target.
EPW5 was released in DEC 29, 2021.
https://www.happymodel.cn/index.php/2021/12/29/happymodel-expresslrs-elrs-epw5-2-4ghz-5ch-pwm-rc-receiver-for-fixed-wing/

**Comment by Dtran54** [comment]
Something to note is the EPW5 is being discontinued.

**Comment by Stemplar42** [comment]
I have EPW5, and not binding well. The RX connect with TX, but a few seconds after, disconnect and re connect. I dont unbricking and dont have any solution. Do you have any alternative?. Thanks

**Comment by Dtran54** [comment]
> I have EPW5, and not binding well. The RX connect with TX, but a few seconds after, disconnect and re connect. I dont unbricking and dont have any solution. Do you have any alternative?. Thanks

What firmware version and TX hardware?

**Comment by geoffsim** [comment]
I have the same issue with this RX. I had already updated my TX (BETAFPV 1W) to allow me to use the new modes with a differente rx. The probem persists even if I update to the latest rx firmware, which seems to report as "Generic ESP8285 5xPWM 2.4Ghz RX". I will try downgrading to see if an earlier version works...
