### ISSUE TITLE
Add Mateksys R24-P6 2400 PWM Target

### ISSUE THREAD

**Issue by Mkorho** [ExpressLRS/ExpressLRS#2049]
Mateksys ELRS-R24-P6 PWM Is still using DIY_2400_RX_PWMP_EX target.
http://www.mateksys.com/?portfolio=elrs-r24-p6

This receiver needs the firmware gzip compression in order to update via WIFI to v3.1.2

**Comment by pkendall64** [comment]
Gzipping uploads via wifi has been added in 3.2.0

**Comment by JyeSmith** [comment]
It doesnt look like we have hardware samples to support and add this target.
