### ISSUE TITLE
2.4 slim tx and X9 lite

### ISSUE THREAD

**Issue by alexdibi** [ExpressLRS/ExpressLRS#205]
for the X9 lite the stl is not good ... the pcb can be cut out on the edges (yellow lines on the image)?
![IMG_20201103_130351.jpg](https://user-images.githubusercontent.com/52356568/97983505-afd2cf00-1dd5-11eb-9dd5-b24c685dc5c9.jpg)

**Comment by phobos-** [comment]
Actually, the PCB can be made even smaller if you moved one of the components to the other side. Not sure if this would be feasible. Did you test if it works at least?

**Comment by brandonrc** [comment]
Closing this issue because there are smaller slim boards. 

https://github.com/ExpressLRS/ExpressLRS/tree/master/PCB/2400MHz/TX_SX1280_Super_Slim
