### ISSUE TITLE
Radiomaster Boxer - 3.2.0

### ISSUE THREAD

**Issue by Kendo1985** [ExpressLRS/ExpressLRS#2056]
## Current Behavior

Having a right nightmare.
Anyone know why the boxer freezes when I go into the elrs.
It was working on the latest firmware for a short while and now all of a sudden it gets stuck here on the loading screen.
Video is attached
Thanks

## Steps to Reproduce

1.

2.

3.

4.

## Your Environment

- TX hardware:
- RX hardware:
- Handset model:
- OpenTX version (including nightly number)
- ExpressLRS version (TX & RX MUST MATCH):
- Packet Rate:
- Telemetry Ratio:
- user_defines:

**Comment by Kendo1985** [comment]
https://user-images.githubusercontent.com/122646718/214732393-19ef396b-3cbe-47e0-9528-1e0649c9add5.MOV

**Comment by pkendall64** [comment]
The best place to ask for help is on discord in the #help-and-support channel. You will get a much faster resolution there rather back and forth in a github issue.

**Comment by Kendo1985** [comment]
> back

No joy as of yet, been on the discord for about 6 hours straight trying to resolve.

**Comment by SunjunKim** [comment]
This happens when the radio is not communicating with the internal module properly.

If the module is soft-bricked, you can try EdgeTX passthrough update (which should work always).
If you've configured everything right and it's still happening, it might be a hardware issue.

**Comment by 534002646** [comment]
I have the same problem as you, did you solve it?

**Comment by Kendo1985** [comment]
> I have the same problem as you, did you solve it?

Yes. Open Model Menu (MDL key)
press Page > key once
scroll down to Internal RF, change it from Off to CRSF. Let me know if it works.

**Comment by GioMBG** [comment]
Hi Kendo1985,
after going around for hours You resolved my loading... stuck
m a n y - t h a n k s !
