### ISSUE TITLE
v3.2.0 on DIY 2.4Ghz E28 and I2C OLED telemetry value not working

### ISSUE THREAD

**Issue by mikebolou** [ExpressLRS/ExpressLRS#2065]
## Current Behavior

DIY 2.4Ghz E28 the I2C OLED do not update the TLM value. Updates all the other values but is stack with 1:2 TLM.
## Steps to Reproduce
Change telemetry ratio with Lua 3.2.0, I2C oled won't update the value, shows only 1:2 TLM

## Your Environment

- TX hardware: DIY 2.4 E28
- RX hardware:
- Handset model: TX16s
- EDGETX version (including nightly number) 2.8
- ExpressLRS version (TX & RX MUST MATCH): 3.2.0
- Packet Rate: F1000
- Telemetry Ratio: Race

**Comment by pkendall64** [comment]
Just tested with a Ranger (which has an OLED) and it works for me. The TLM rate does flip to 1:2 when it starts communicating with an RX and then after a small period (1 second?) it goes back to the configured rate. And I can see this happening on the OLED when I make changes via the Lua script.
