### ISSUE TITLE
Incorrect Model ID Value Causing Unexpected Checkbox Selection (ExpressLRS 3.0.1)

### ISSUE THREAD

**Issue by edernucci** [ExpressLRS/ExpressLRS#2077]
**Description:**
**HappyModel** is unintentionally setting the model id value to 0 instead of the standard value of 255 used by other manufacturers. As a result, the javascript that interprets whether the checkbox should be selected or not does not understand the value 0 and leaves the checkbox selected without user interaction, causing the firmware update with the model match feature enabled.

**Steps to Reproduce:**

Set the model id value to 0
Observe the behavior of the checkbox in the javascript

**Expected Result:**
The checkbox should not be selected without user interaction.

**Actual Result:**
The checkbox is selected without user interaction.

**Impact:**
This issue can cause unintended firmware updates with the model match feature enabled, leading to potential compatibility issues.

**Solution:**
The company should change the model id value to the standard value of 255 to resolve this issue.

![3d7e7a3a-fd59-4342-9fb9-76fa11092f82](https://user-images.githubusercontent.com/6978683/218289768-cd55f69b-34da-44aa-82f3-cb2deaa8daa4.png)
![7dfc5b51-85ec-4f61-8429-dffc5911ee76](https://user-images.githubusercontent.com/6978683/218289771-c5dccb5d-b0b3-4623-8c3a-395218f94c2f.png)

**Comment by edernucci** [comment]
**Update:** After further testing, we have realized that this issue may also affect other manufacturers as long as they are on version 3.0.1, leading us to believe that the issue is in this version.

**Impact:**
This issue could potentially impact not just HappyModel but other manufacturers as well who are using version 3.0.1. This could cause unintended firmware updates with the model match feature enabled for a larger number of users, leading to compatibility issues.

![dbf72267-36ff-4eea-b762-e93ced029ce1](https://user-images.githubusercontent.com/6978683/218289952-ccb1e7e3-08b8-4a9e-8080-fa1d48e64da2.png)

**Comment by iscarelli** [comment]
Exactly same behavior here.

3.0.1 has Model ID set as 0 and activating Model Match.

[]'s
Ismael

**Comment by pkendall64** [comment]
I'm not really sure what the problem is here. I've flashed a device with 3.0.1, with a full erase and the default is that Model match is disabled. I can enable it and enter a value of 0 and save and it remembers that it is enabled with a 0 matched model. This is a valid configuration.
Perhaps happy model have done some testing and are shipping out with model match enabled?
