### ISSUE TITLE
5 way button no longer brings up menu on OLED screen when TX is armed

### ISSUE THREAD

**Issue by kenny000666** [ExpressLRS/ExpressLRS#2081]
## Current Behavior

On the ELRS BetaFPV Micro TX with OLED Screen and 5 way button. 
Long pressing the 5 way button on firmware > 3.0 after TX has armed no longer allows the TX to navigate. In firmwares 2.x, long pressing the 5 way button at any time allows navigating the TX OLED menus. 

If TX is not connected to Radio, and is powered on its own, the TX will boot up with no handset (Not Armed). Long pressing the 5 way button at this point allows navigating the OLED screen. 

I believe something has caused this to regress? Possibly the introduction of the Armed screen? 

## Steps to Reproduce

1. Power on Radio with TX connected. TX will show Armed screen.
Currently mine shows
[     !      Armed    !     ]
Ver:     3.2.0
150Hz          1 : 4
25mW          TLM

3. Long press the 5 way button, OLED screen content does not change

4. Power on TX using USB C and not connected to Radio. TX will show No Handset on screen.

5. Long press the 5 way button, OLED screen will change to the menu, allowing navigating through Transmission, Power, BLE etc etc.

## Possible Solution (Not obligatory)

N/A

## Details

My device is not OpenTX, it does not support LUA, so without the ability to navigate through the menu, using the OLED screen and 5 way button, i am unable to control the TX

## Your Environment

- TX hardware: Betafpv Micro ELRS TX 1w
- RX hardware: N/A
- Handset model: TBS Tango
- OpenTX version (including nightly number) N/A
- ExpressLRS version (TX & RX MUST MATCH): 3.2
- Packet Rate: N/A
- Telemetry Ratio: N/A
- user_defines: N/A

**Comment by pkendall64** [comment]
It's a safety feature. We've done it this way intentionally.
