### ISSUE TITLE
RadioMaster TX16S Mk2 internal ELRS TX module and TX uplink power Betaflight OSD element not working

### ISSUE THREAD

**Issue by banem78** [ExpressLRS/ExpressLRS#2085]
## Current Behavior

Betaflight is reporting 0mW in TX uplink power OSD element when using internal ELRS module on RadioMaster TX16S Mk2.
When I tested this with my other  ELRS TX modules (RadioMaster Ranger Micro or Jumper T-Lite v2 internal ELRS module) OSD shows the correct value. 

## Steps to Reproduce

1. Enable TX uplink power OSD element in BF Configurator on the drone.
2. On TX16S set Model to use internal TX. 

## Details

ELRS LUA script on the controller reports the correct value (25mW to 250mW), only OSD element reads 0mW.
It's the same on both analog and DJI (WFT.OS) systems.
The OSD element work OK with other TX modules, reports correct power level value.

## Your Environment

- TX hardware: RadioMaster TX16s Mk2 internal ELRS 2.4GHz module
- RX hardware: various 2.4GHz RX modules (BetaFPV, Flywoo, Radiomaster, Matek)
- Handset model:
- OpenTX version (including nightly number) EdgeTX 2.7.1
- ExpressLRS version (TX & RX MUST MATCH): 3.2.0 (tested with 3.1.2 also)
- Packet Rate: 250Hz and 500Hz
- Telemetry Ratio: standard
- user_defines:

**Comment by ot0tot** [comment]
Do you have switch mode set to Wide in the ELRS lua when using the TX16S internal ELRS module? Tpwr will not work if switch mode is set to Hybrid. 
https://www.expresslrs.org/software/switch-config/#hybrid-and-wide-switch-configuration-modes
