### ISSUE TITLE
Wifi mode on TX Module enabling permanently

### ISSUE THREAD

**Issue by rotorgeeks** [ExpressLRS/ExpressLRS#2096]
## Current Behavior
After enabling wifi mode in TX module once thru LUA it remained permanently enabled, preventing normal connection to RX.  Power cycling had no effect.

## Steps to Reproduce

1.  Flash Happymodel ES24 TX to 3.2.0 , no wifi options checked for the flash (i.e. Auto Wifi on Interval or any home wifi settings).  

2.  Enable TX wifi thru LUA using ELRS V3 script

3.  Connect via wifi (WebUI) to confirm.  Exit wifi mode and/or power cycle radio.

4.  Check to see if TX module connects to RX.  If no connection, attempt to change packet rate - it will reject the change.  Confirm Wifi is still enabled by checking for available networks on pc or other device.

## Possible Solution (Not obligatory)

WebUI showed WiFi "auto on" interval set to 0.  Change it to any other value.

## Details
verified on multiple TX modules

## Your Environment

- TX hardware: Happymodel ES24 TX
- RX hardware: Happymodel EP1, Matek R-24-P, Matex R-24-P6
- Handset model: FrSKY X9 Lite
- OpenTX version:  2.3.15
- ExpressLRS version: 3.2.0
- Packet Rate: 50, 150, 250
- Telemetry Ratio: 1:4, 1:32
**- user_defines:** 
-DRegulatory_Domain_ISM_2400
-DMY_BINDING_PHRASE="xxxxxxxxxxx"
-DUART_INVERTED
-DFAST_SYNC

**Comment by SunjunKim** [comment]
I tried the described procedure but could not reproduce the problem (tried on a Radiomaster Ranger Micro).
Flashed the TX on v3.2 with WiFi auto on disabled, activated WiFi on Lua, power cycle, and it returns to normal as expected.

Perhaps could you demonstrate the exact procedure on a video?
