### ISSUE TITLE
EP2 reboot 

### ISSUE THREAD

**Issue by boris-gu** [ExpressLRS/ExpressLRS#2097]
## Current Behavior
The receiver restarts: the LED starts flashing and the remote loses connection. After a few seconds, the connection is restored. After a few more seconds, the connection is cut off again. And so endlessly

## Steps to Reproduce

To reproduce the problem, you need to assemble the firmware with parameters as in the screenshot. The problem occurs when changing baud rate to 115200. TX (I use Namimno) should have Packet Rate of 500Hz.  
![Снимок экрана от 2023-02-23 22-50-50](https://user-images.githubusercontent.com/44787162/221015759-242b95e5-57cd-4901-b963-85cc21450b9e.png)

## Possible Solution (Not obligatory)

I do not know how this is related, but when I change TX Packet Rate to 150Hz, everything works fine.

## Details

I connected the EP2 to the arduino and, among the raw data, received the following message (occurs every time the receiver loses connection)  
```
--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Soft WDT reset

>>>stack>>>

ctx: cont
sp: 3ffffda0 end: 3fffffc0 offset: 01a0
3fffff40:  000042c4 3fff2e80 3fff2ecc 40202f15  
3fffff50:  140cc80e 00000001 3fff09e8 40201a06  
3fffff60:  3ffe85d0 3fff0984 000042c4 40201d44  
3fffff70:  00000000 3fff0700 3fff0984 4020193e  
3fffff80:  00000000 00000000 00000001 401024c8  
3fffff90:  3fffdad0 00000000 3fff4a64 3fff4a78  
3fffffa0:  3fffdad0 00000000 3fff4a64 40211034  
3fffffb0:  feefeffe feefeffe 3ffe89e0 40103885  
<<<stack<<<
--------------- CUT HERE FOR EXCEPTION DECODER ---------------

 ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x4010f000, len 3460, room 16 
tail 4
chksum 0xcc
load 0x3fff20b8, len 40, room 4 
tail 4
chksum 0xc9
csum 0xc9
v0007a7e0
~ld
ExpressLRS Module Booting...
Setting ISM2G4 Mode
```

## Your Environment

- Namimno 2.4GHz Flash:
- Happymodel EP2:
- Taranis QX7 (with cross mod) and Radiomaster TX12:
- OpenTX 2.3.15-otx
- ExpressLRS 3.2:
- Packet Rate 500 and 150:
- Telemetry Ratio 1:128:
- user_defines:
  ```
  -DRegulatory_Domain_ISM_2400
  -DMY_BINDING_PHRASE="testtesttest"
  -DLOCK_ON_FIRST_CONNECTION
  -DAUTO_WIFI_ON_INTERVAL="20"
  -DRCVR_UART_BAUD="115200"
  -DFAST_SYNC
  ```

**Comment by pkendall64** [comment]
If you try and run the RX baud rate at 115k and 500Hz I think you find that the serial buffer is overflowing on the receiver.
At 500Hz the packets are being sent too fast for a 115k baud rate to keep up.
