### ISSUE TITLE
Telemetria

### ISSUE THREAD

**Issue by Giuseppebixler** [ExpressLRS/ExpressLRS#2099]
## Steps to Reproduce

1.I have a problem with my taranis qx7 on which I mount a betafpv elrs module.
 For a few days now, when I connect the lipo to my fc, the connection between my radio and the receiver immediately takes place but immediately after it falls, but if I disconnect the lipo and quickly reconnect it, it connects stably to the radio.  I have noticed that if I increase the telemetry data rate up to 1:2 the problem no longer occurs.  On the radio I have openTx and I only have the software change.  What can it depend on?

2.

3.

4.

## Your Environment

- TX hardware:
- RX hardware:
- Handset model:
- OpenTX version (including nightly number)
- ExpressLRS version (TX & RX MUST MATCH):
- Packet Rate:
- Telemetry Ratio:
- user_defines:

**Comment by schugabe** [comment]
Can you please edit your post and add the details in the "your environment" section?

**Comment by pkendall64** [comment]
Closing as no new information provided
