### ISSUE TITLE
Dynamic power not reacting correctly with 2 radios (True Diversity)

### ISSUE THREAD

**Issue by neuhausj** [ExpressLRS/ExpressLRS#2109]
## Current Behavior

Currently ELRS always favor one radio and only falls back to the second one when bad or no packet is received from this radio.
This happens even if the second radio has better signal.
It looks like dynamic power is currently reacting based on the active radio.

## Steps to Reproduce

With a True Diversity receiver, remove the antenna of the main radio and walk to lose the signal and observe the radio switching.

In this example 1RSS has an antenna and 2RSS has no antenna:
Radio1 (with antenna): min -78dB / max -32dB
Radio2 (no antenna): min -115dB / max -68dB

Note:
*  the amount of switching, even if radio 1 has a much better signal all along (no increase in power would be required).
* Also note the switching to the radio2 (no antenna) at the end, when we walk back toward the receiver.

![image](https://user-images.githubusercontent.com/182152/223867241-1b5222e0-b08c-41ff-8c84-f42672d535ac.png)

This is the corresponding power output:
* When radio 2 (without antenna) is in use, the power raises to 100mW (max).
![image](https://user-images.githubusercontent.com/182152/223867421-82dd943e-ce74-43f0-8e79-a03744f17b6e.png)

Here is a video showing the issue: https://discord.com/channels/596350022191415318/950918956779208754/1083070023016402975

Another linked issue is that the RSSI is only reported for the active radio.

## Possible Solutions

A few solutions are possible:
Option 1. Change the read order of the radios to always read the active radio first. 
In the previous case, it would have mean only the first radio switch (to the one with antenna) would have occured. The receiver would have then stayed on this radio as long as no bad packet was received and the second radio had a valid packet.
Dynamic power will also adapt to the best link available in this case.
Solution is not optimal as we still don't have the signal data (RSSI/SNR) of the second radio. 

Option 2: Get both radio RSSI/SNR to adjust dynamic power accordingly. Take the first valid data that comes.

## Your Environment

- TX hardware: Ghost module
- RX hardware: DIY PWM True Diversity receiver
- Handset model: Tx16S
- OpenTX version (including nightly number): EdgeTx 2.8
- ExpressLRS version: 3.2.0
- Packet Rate: F500 and 150Hz were tested
- Telemetry Ratio: 1:16
- user_defines:

**Comment by neuhausj** [comment]
Following discussions on Discord, the best approach would be to always read packets from both radios to have their signal status (RSSI / SNR).

This info can then be used to:
* adapt dynamicaly the power based on the best link of the 2 receivers
* choose the correct antenna to send back telemetry info

**Comment by SunjunKim** [comment]
Guys I updated a revised version of my previous RSSI update PR in `true_diversity_rssi_update` branch. Feel free to test it. Currently only 2.4g TD receivers are covered.

It should be able to update 1RSSI/2RSSI whenever each radio gets the packet, and SNR (which has only a single field) will display the better one.

This is more consistent with the behavior of antenna diversity receivers I believe..

https://github.com/ExpressLRS/ExpressLRS/tree/true_diversity_rssi_update

**Comment by SunjunKim** [comment]
I found the current `true_diversity_rssi_update` implementation is nonsense even though it looks like working fine..
As ProcessRFPacket() is called only once at the first packet, and the other radio's packet will be processed in the next ProcessRFPacket() call, which compares the packets in two different index... 

I'll update it to be right later, and let you know then.

**Comment by SunjunKim** [comment]
Now the bug in the branch is patched
**Feel free to test this now, but take the risk of experimental firmware (aka assume some unexpected failure)**
https://github.com/ExpressLRS/ExpressLRS/tree/true_diversity_rssi_update

**Comment by neuhausj** [comment]
> Now the bug in the branch is patched **Feel free to test this now, but take the risk of experimental firmware (aka assume some unexpected failure)** https://github.com/ExpressLRS/ExpressLRS/tree/true_diversity_rssi_update

Just small feedback: I did a few bench tests + around 5-6h of flights on 3 different planes/receivers and it works as expected.
Telemetry also looks improved (as it uses the "best" antenna/radio).
Dynamic power seems to work as well, even if it rarely goes up when flying LOS. 

Here some flight logs>
![image](https://user-images.githubusercontent.com/182152/227933723-95a1a63e-19db-4cbd-81b4-73b2efdd0fb6.png)
![image](https://user-images.githubusercontent.com/182152/227933778-28dbdb76-18ae-4dd0-a504-c3dd2269bf9c.png)
![image](https://user-images.githubusercontent.com/182152/227933908-1ca8850a-9d06-4c3a-86e2-141d267b64fa.png)
