### ISSUE TITLE
sbus refractor

### ISSUE THREAD

**Issue by secretman28** [ExpressLRS/ExpressLRS#2133]
## Current Behavior
cant compile, setting the power(eu ism etc) un available on the configurator if i use the original github from the original coder all work #1

cant compile cannot choose the region power spec

## Steps to Reproduce
try to build the refractor for a rx

Warning! `src_filter` configuration option in section [env:native] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:AXIS_THOR_2400_TX_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:AXIS_THOR_2400_RX_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:Frsky_TX_R9M_via_STLINK] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:Frsky_TX_R9M_LITE_PRO_via_STLINK] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:Frsky_RX_R9MM_R9MINI_via_STLINK] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:Frsky_RX_R9SLIM_via_BetaflightPassthrough] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:Frsky_RX_R9SLIMPLUS_via_BetaflightPassthrough] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:Frsky_RX_R9MX_via_STLINK] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:Jumper_RX_R900MINI_via_BetaflightPassthrough] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:HappyModel_TX_ES915TX_via_STLINK] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:HappyModel_TX_ES900TX_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:HappyModel_RX_ES915RX_via_STLINK] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:HappyModel_ES24TX_2400_TX_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:HappyModel_ES24TX_Pro_Series_2400_TX_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:BETAFPV_900_TX_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:BETAFPV_900_TX_MICRO_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:BETAFPV_900_RX_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:BETAFPV_2400_TX_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:BETAFPV_2400_TX_MICRO_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:BETAFPV_2400_RX_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:GHOST_2400_TX_via_STLINK] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:GHOST_ATTO_2400_RX_via_STLINK] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:NamimnoRC_VOYAGER_900_TX_via_STLINK] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:NamimnoRC_VOYAGER_900_OLED_TX_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:NamimnoRC_VOYAGER_900_RX_via_STLINK] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:NamimnoRC_VOYAGER_900_ESP_RX_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:NamimnoRC_FLASH_2400_TX_via_STLINK] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:NamimnoRC_FLASH_2400_OLED_TX_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:NamimnoRC_FLASH_2400_RX_via_STLINK] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:NamimnoRC_FLASH_2400_ESP_RX_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:FM30_TX_via_STLINK] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:FM30_RX_MINI_via_STLINK] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:FM30_RX_MINI_AS_TX_via_STLINK] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:HGLRC_Hermes_2400_TX_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:QuadKopters_JR_2400_TX_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:DIY_900_TX_TTGO_V1_SX127x_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:DIY_900_TX_TTGO_V2_SX127x_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:DIY_900_TX_ESP32_SX127x_E19_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:DIY_900_TX_ESP32_SX127x_RFM95_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:DIY_900_RX_ESP8285_SX127x_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:DIY_900_RX_HUZZAH_RFM95W_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:DIY_900_RX_PWMP_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:DIY_2400_TX_ESP32_SX1280_Mini_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:DIY_2400_TX_ESP32_SX1280_E28_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:DIY_2400_TX_ESP32_SX1280_LORA1280F27_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:DIY_2400_TX_ESP8285_SX1280_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:DIY_2400_RX_ESP8285_SX1280_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:DIY_2400_RX_PWMP_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:DIY_2400_RX_STM32_CCG_Nano_v0_5_via_STLINK] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:DIY_BLE_JOYSTICK_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:MATEK_2400_RX_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:iFlight_900_TX_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:iFlight_2400_TX_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Warning! `src_filter` configuration option in section [env:iFlight_2400_RX_via_UART] is deprecated and will be removed in the next release! Please use `build_src_filter` instead
Processing HappyModel_EP_2400_RX_via_BetaflightPassthrough (platform: espressif8266@3.2.0; board: esp8285-8285; framework: arduino)
--------------------------------------------------------------------------------
Library Manager: Installing ottowinter/ESPAsyncWebServer-esphome @ ^1.3.0
Unpacking
Library Manager: ESPAsyncWebServer-esphome@1.3.0 has been installed!
Library Manager: Resolving dependencies...
Library Manager: Installing ESPAsyncTCP-esphome
Unpacking
Library Manager: ESPAsyncTCP-esphome@1.2.3 has been installed!
Verbose mode can be enabled via `-v, --verbose` option
UID bytes: 226,146,152,0,172,139
***Building for ESP8266/ESP8285 Platform
AUTO_WIFI_ON_INTERVAL = ON
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/esp8285-8285.html
PLATFORM: Espressif 8266 (3.2.0) > Generic ESP8285 Module
HARDWARE: ESP8266 160MHz, 80KB RAM, 1MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 @ 3.30002.0 (3.0.2) 
 - tool-esptool @ 1.413.0 (4.13) 
 - tool-esptoolpy @ 1.30000.201119 (3.0.0) 
 - toolchain-xtensa @ 2.100300.210717 (10.3.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 71 compatible libraries
Scanning dependencies...
Dependency Graph
|-- ESPAsyncWebServer-esphome @ 1.3.0
|   |-- ESPAsyncTCP-esphome @ 1.2.3
|   |-- Hash @ 1.0
|   |-- ESP8266WiFi @ 1.0
|-- SX1280Driver
|   |-- logging
|   |-- SPI @ 1.0
|-- CONFIG
|   |-- EEPROM
|   |   |-- logging
|   |   |-- EEPROM @ 1.0
|   |   |-- Wire @ 1.0
|   |-- logging
|   |-- OTA
|   |   |-- CRSF
|   |   |   |-- CRC
|   |   |   |-- CrsfProtocol
|   |   |   |   |-- CRC
|   |   |   |-- MSP
|   |   |   |   |-- logging
|   |   |   |-- TelemetryProtocol
|   |   |   |-- DEVICE
|   |   |   |   |-- helpers
|   |   |   |   |-- logging
|   |   |   |   |-- SX1280Driver
|   |   |   |   |   |-- logging
|   |   |   |   |   |-- SPI @ 1.0
|   |   |   |-- FIFO
|   |   |   |   |-- logging
|   |   |   |-- helpers
|   |   |   |-- logging
|   |-- POWERMGNT
|   |   |-- DAC
|   |   |   |-- Wire @ 1.0
|   |   |   |-- helpers
|   |   |   |-- logging
|   |   |-- SX1280Driver
|   |   |   |-- logging
|   |   |   |-- SPI @ 1.0
|-- CRC
|-- CRSF
|   |-- CRC
|   |-- CrsfProtocol
|   |   |-- CRC
|   |-- MSP
|   |   |-- logging
|   |-- TelemetryProtocol
|   |-- DEVICE
|   |   |-- helpers
|   |   |-- logging
|   |   |-- SX1280Driver
|   |   |   |-- logging
|   |   |   |-- SPI @ 1.0
|   |-- FIFO
|   |   |-- logging
|   |-- helpers
|   |-- logging
|-- BUTTON
|   |-- DEVICE
|   |   |-- helpers
|   |   |-- logging
|   |   |-- SX1280Driver
|   |   |   |-- logging
|   |   |   |-- SPI @ 1.0
|   |-- logging
|   |-- POWERMGNT
|   |   |-- DAC
|   |   |   |-- Wire @ 1.0
|   |   |   |-- helpers
|   |   |   |-- logging
|   |   |-- SX1280Driver
|   |   |   |-- logging
|   |   |   |-- SPI @ 1.0
|-- DEVICE
|   |-- helpers
|   |-- logging
|   |-- SX1280Driver
|   |   |-- logging
|   |   |-- SPI @ 1.0
|-- LED
|   |-- DEVICE
|   |   |-- helpers
|   |   |-- logging
|   |   |-- SX1280Driver
|   |   |   |-- logging
|   |   |   |-- SPI @ 1.0
|   |-- CrsfProtocol
|   |   |-- CRC
|   |-- POWERMGNT
|   |   |-- DAC
|   |   |   |-- Wire @ 1.0
|   |   |   |-- helpers
|   |   |   |-- logging
|   |   |-- SX1280Driver
|   |   |   |-- logging
|   |   |   |-- SPI @ 1.0
|   |-- logging
|-- WIFI
|   |-- DEVICE
|   |   |-- helpers
|   |   |-- logging
|   |   |-- SX1280Driver
|   |   |   |-- logging
|   |   |   |-- SPI @ 1.0
|   |-- CONFIG
|   |   |-- EEPROM
|   |   |   |-- logging
|   |   |   |-- EEPROM @ 1.0
|   |   |   |-- Wire @ 1.0
|   |   |-- logging
|   |   |-- OTA
|   |   |   |-- CRSF
|   |   |   |   |-- CRC
|   |   |   |   |-- CrsfProtocol
|   |   |   |   |   |-- CRC
|   |   |   |   |-- MSP
|   |   |   |   |   |-- logging
|   |   |   |   |-- TelemetryProtocol
|   |   |   |   |-- DEVICE
|   |   |   |   |   |-- helpers
|   |   |   |   |   |-- logging
|   |   |   |   |   |-- SX1280Driver
|   |   |   |   |   |   |-- logging
|   |   |   |   |   |   |-- SPI @ 1.0
|   |   |   |   |-- FIFO
|   |   |   |   |   |-- logging
|   |   |   |   |-- helpers
|   |   |   |   |-- logging
|   |   |-- POWERMGNT
|   |   |   |-- DAC
|   |   |   |   |-- Wire @ 1.0
|   |   |   |   |-- helpers
|   |   |   |   |-- logging
|   |   |   |-- SX1280Driver
|   |   |   |   |-- logging
|   |   |   |   |-- SPI @ 1.0
|   |-- helpers
|   |-- HWTIMER
|   |   |-- logging
|   |-- logging
|   |-- POWERMGNT
|   |   |-- DAC
|   |   |   |-- Wire @ 1.0
|   |   |   |-- helpers
|   |   |   |-- logging
|   |   |-- SX1280Driver
|   |   |   |-- logging
|   |   |   |-- SPI @ 1.0
|   |-- SX1280Driver
|   |   |-- logging
|   |   |-- SPI @ 1.0
|   |-- DNSServer @ 1.1.1
|   |   |-- ESP8266WiFi @ 1.0
|   |-- ESP8266mDNS @ 1.2
|   |   |-- ESP8266WiFi @ 1.0
|   |-- ESP8266WiFi @ 1.0
|   |-- ESPAsyncWebServer-esphome @ 1.3.0
|   |   |-- ESPAsyncTCP-esphome @ 1.2.3
|   |   |-- Hash @ 1.0
|   |   |-- ESP8266WiFi @ 1.0
|-- EEPROM
|   |-- logging
|   |-- EEPROM @ 1.0
|   |-- Wire @ 1.0
|-- FHSS
|   |-- SX1280Driver
|   |   |-- logging
|   |   |-- SPI @ 1.0
|   |-- logging
|-- helpers
|-- HWTIMER
|   |-- logging
|-- logging
|-- LQCALC
|-- MSP
|   |-- logging
|-- OTA
|   |-- CRSF
|   |   |-- CRC
|   |   |-- CrsfProtocol
|   |   |   |-- CRC
|   |   |-- MSP
|   |   |   |-- logging
|   |   |-- TelemetryProtocol
|   |   |-- DEVICE
|   |   |   |-- helpers
|   |   |   |-- logging
|   |   |   |-- SX1280Driver
|   |   |   |   |-- logging
|   |   |   |   |-- SPI @ 1.0
|   |   |-- FIFO
|   |   |   |-- logging
|   |   |-- helpers
|   |   |-- logging
|-- PFD
|-- POWERMGNT
|   |-- DAC
|   |   |-- Wire @ 1.0
|   |   |-- helpers
|   |   |-- logging
|   |-- SX1280Driver
|   |   |-- logging
|   |   |-- SPI @ 1.0
|-- StubbornReceiver
|-- StubbornSender
|-- Telemetry
|   |-- CrsfProtocol
|   |   |-- CRC
|   |-- CRSF
|   |   |-- CRC
|   |   |-- CrsfProtocol
|   |   |   |-- CRC
|   |   |-- MSP
|   |   |   |-- logging
|   |   |-- TelemetryProtocol
|   |   |-- DEVICE
|   |   |   |-- helpers
|   |   |   |-- logging
|   |   |   |-- SX1280Driver
|   |   |   |   |-- logging
|   |   |   |   |-- SPI @ 1.0
|   |   |-- FIFO
|   |   |   |-- logging
|   |   |-- helpers
|   |   |-- logging
|-- TelemetryProtocol
|-- Servo @ 1.0.2
Building in release mode
PLATFORM : 'espressif8266'
BUILD ENV: 'HAPPYMODEL_EP_2400_RX_VIA_BETAFLIGHTPASSTHROUGH'
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\src\common.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\src\options.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\src\rx_main.cpp.o
Generating LD script .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\ld\local.eagle.app.v6.common.ld
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib92b\ESPAsyncTCP-esphome\AsyncPrinter.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib92b\ESPAsyncTCP-esphome\ESPAsyncTCP.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib92b\ESPAsyncTCP-esphome\ESPAsyncTCPbuffer.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib92b\ESPAsyncTCP-esphome\SyncClient.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib92b\ESPAsyncTCP-esphome\tcp_axtls.c.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\libec0\Hash\Hash.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib4ac\ESP8266WiFi\BearSSLHelpers.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib4ac\ESP8266WiFi\CertStoreBearSSL.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib4ac\ESP8266WiFi\ESP8266WiFi.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib4ac\ESP8266WiFi\ESP8266WiFiAP.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib4ac\ESP8266WiFi\ESP8266WiFiGeneric.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib4ac\ESP8266WiFi\ESP8266WiFiGratuitous.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib4ac\ESP8266WiFi\ESP8266WiFiMulti.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib4ac\ESP8266WiFi\ESP8266WiFiSTA-WPS.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib4ac\ESP8266WiFi\ESP8266WiFiSTA.cpp.o
Archiving .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\libec0\libHash.a
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib4ac\ESP8266WiFi\ESP8266WiFiScan.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib4ac\ESP8266WiFi\WiFiClient.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib4ac\ESP8266WiFi\WiFiClientSecureBearSSL.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib4ac\ESP8266WiFi\WiFiServer.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib4ac\ESP8266WiFi\WiFiServerSecureBearSSL.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib4ac\ESP8266WiFi\WiFiUdp.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib4ac\ESP8266WiFi\enable_wifi_at_boot_time.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib746\ESPAsyncWebServer-esphome\AsyncEventSource.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib746\ESPAsyncWebServer-esphome\AsyncWebSocket.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib746\ESPAsyncWebServer-esphome\SPIFFSEditor.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib746\ESPAsyncWebServer-esphome\WebAuthentication.cpp.o
Archiving .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib92b\libESPAsyncTCP-esphome.a
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib746\ESPAsyncWebServer-esphome\WebHandlers.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib746\ESPAsyncWebServer-esphome\WebRequest.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib746\ESPAsyncWebServer-esphome\WebResponses.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib746\ESPAsyncWebServer-esphome\WebServer.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib6ea\logging\logging.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib9dc\SPI\SPI.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib1ef\SX1280Driver\SX1280.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib1ef\SX1280Driver\SX1280_hal.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\libbac\EEPROM\EEPROM.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\libac8\Wire\Wire.cpp.o
In file included from .pio\libdeps\HappyModel_EP_2400_RX_via_BetaflightPassthrough\ESPAsyncWebServer-esphome\src\SPIFFSEditor.cpp:1:
.pio\libdeps\HappyModel_EP_2400_RX_via_BetaflightPassthrough\ESPAsyncWebServer-esphome\src\SPIFFSEditor.h:16:101: warning: 'SPIFFS' is deprecated: SPIFFS has been deprecated. Please consider moving to LittleFS or other filesystems. [-Wdeprecated-declarations]
   16 |     SPIFFSEditor(const String& username=String(), const String& password=String(), const fs::FS& fs=SPIFFS);
      |                                                                                                     ^~~~~~
In file included from .pio\libdeps\HappyModel_EP_2400_RX_via_BetaflightPassthrough\ESPAsyncWebServer-esphome\src/ESPAsyncWebServer.h:27,
                 from .pio\libdeps\HappyModel_EP_2400_RX_via_BetaflightPassthrough\ESPAsyncWebServer-esphome\src\SPIFFSEditor.h:3,
                 from .pio\libdeps\HappyModel_EP_2400_RX_via_BetaflightPassthrough\ESPAsyncWebServer-esphome\src\SPIFFSEditor.cpp:1:
C:\Users\SecretPc\.platformio\packages\framework-arduinoespressif8266\cores\esp8266/FS.h:275:15: note: declared here
  275 | extern fs::FS SPIFFS __attribute__((deprecated("SPIFFS has been deprecated. Please consider moving to LittleFS or other filesystems.")));
      |               ^~~~~~
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\libf22\EEPROM\elrs_eeprom.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\libfd4\CRC\crc.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\libb84\CrsfProtocol\dummy.c.o
Archiving .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib6ea\liblogging.a
Archiving .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib4ac\libESP8266WiFi.a
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib56f\MSP\msp.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\libd7d\TelemetryProtocol\dummy.c.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib6f2\helpers\dummy.c.o
Archiving .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\libb84\libCrsfProtocol.a
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib07a\DEVICE\device.cpp.o
Archiving .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib1ef\libSX1280Driver.a
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib124\FIFO\FIFO.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib6a6\CRSF\CRSF.cpp.o
Archiving .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib6f2\libhelpers.a
Archiving .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\libd7d\libTelemetryProtocol.a
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib6a6\CRSF\devCRSF.cpp.o
Archiving .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\libbac\libEEPROM.a
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib73e\OTA\OTA.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\libbb1\DAC\DAC.cpp.o
Archiving .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib9dc\libSPI.a
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib74f\POWERMGNT\POWERMGNT.cpp.o
Archiving .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\libac8\libWire.a
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib91f\CONFIG\config.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib4fc\BUTTON\devButton.cpp.o
Archiving .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\libf22\libEEPROM.a
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib052\LED\devLED.cpp.o
Archiving .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\libfd4\libCRC.a
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib052\LED\devRGB.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib9ff\HWTIMER\ESP32_hwTimer.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib9ff\HWTIMER\ESP8266_hwTimer.cpp.o
lib\CRSF\CRSF.cpp:879:6: error: no declaration matches 'void CRSF::sendRawMSPFrameToFC(uint8_t*, uint8_t, uint8_t, bool)'
  879 | void CRSF::sendRawMSPFrameToFC(uint8_t *mspPayload, uint8_t mspPayloadSize, uint8_t type, bool hasHeader = true)
      |      ^~~~
lib\CRSF\CRSF.cpp:879:6: note: no functions named 'void CRSF::sendRawMSPFrameToFC(uint8_t*, uint8_t, uint8_t, bool)'
In file included from lib\CRSF\CRSF.cpp:1:
lib\CRSF\CRSF.h:24:7: note: 'class CRSF' defined here
   24 | class CRSF
      |       ^~~~
lib\CRSF\CRSF.cpp:932:6: error: no declaration matches 'void CRSF::sendRawFrame(uint8_t, uint8_t, const void*, uint8_t)'
  932 | void CRSF::sendRawFrame(uint8_t addr, uint8_t type, const void *payload, uint8_t length)
      |      ^~~~
lib\CRSF\CRSF.cpp:932:6: note: no functions named 'void CRSF::sendRawFrame(uint8_t, uint8_t, const void*, uint8_t)'
In file included from lib\CRSF\CRSF.cpp:1:
lib\CRSF\CRSF.h:24:7: note: 'class CRSF' defined here
   24 | class CRSF
      |       ^~~~
Archiving .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib56f\libMSP.a
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib9ff\HWTIMER\STM32_hwTimer.cpp.o
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\libac9\DNSServer\DNSServer.cpp.o
lib\POWERMGNT\POWERMGNT.cpp: In static member function 'static void POWERMGNT::SetPowerCaliValues(int8_t*, size_t)':
lib\POWERMGNT\POWERMGNT.cpp:95:10: warning: variable 'isUpdate' set but not used [-Wunused-but-set-variable]
   95 |     bool isUpdate = false;
      |          ^~~~~~~~
*** [.pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib6a6\CRSF\CRSF.cpp.o] Error 1
Compiling .pio\build\HappyModel_EP_2400_RX_via_BetaflightPassthrough\lib598\ESP8266mDNS\ESP8266mDNS.cpp.o
========================= [FAILED] Took 12.42 seconds =========================

Environment                                      Status    Duration
-----------------------------------------------  --------  ------------
HappyModel_EP_2400_RX_via_BetaflightPassthrough  FAILED    00:00:12.416
==================== 1 failed, 0 succeeded in 00:00:12.416 ====================

add the setting of region power available in the configurator 

## Your Environment
win10

**Comment by pkendall64** [comment]
The branch/PR has been merged into master, just choose the master branch from configurator.

**Comment by pkendall64** [comment]
If you need help with this, please ask on discord rather than opening a ticket.
