### ISSUE TITLE
BLE Joystick, CH8 not mapped to axis.

### ISSUE THREAD

**Issue by ksmigrod** [ExpressLRS/ExpressLRS#2136]
With new BLE Joystick code (master CE_LBT 29d581) my Radiomaster Zorro (EdgeTX v2.8.1) does not send CH8 to computer.

I've tried mapping S2 slider and SC three way switch to CH8. CH8 is displayed correctly on Zorro's builtin display, but it is "0" on Bluetooth. I've tried Linux (with Intel Corp. AX210 Bluetooth), Windows 11 (with Asus USB BT-500) and an Android 13 phone. On each device axis CH1 to CH7 work, and buttons CH9 - CH12 also work, but CH8 does not.
The same switches and sliders work when moved to CH5 - CH7.

**Comment by pkendall64** [comment]
With 3.x.x-maintenance (upcoming 3.2.1) I set up a model in EdgeTX with channels 1-4 on the sticks, channels 5-8 on switches.
Connected via BLE to Mac, went into Liftoff and calibrated the sticks, moved to the buttons section and I could change the reset action to any of the four assigned switches. So this does not appear to be a problem with ELRS BLE code.

**Comment by mmilata** [comment]
Running into the same issue with ExpressLRS 3.5.2 & EdgeTX 2.11.4. Channels as follows:

<img width="128" height="64" alt="Image" src="https://github.com/user-attachments/assets/63aed229-8519-4067-aa02-7808b850b012" /> <img width="128" height="64" alt="Image" src="https://github.com/user-attachments/assets/4f3915de-c0ee-4de0-a1a8-86d42e6f63f8" /> <img width="128" height="64" alt="Image" src="https://github.com/user-attachments/assets/785a2fbf-651d-4740-9b31-5c11f6ce180b" />

With EdgeTX USB joystick (mode: classic) I can see 8 axes and moving "S2" moves "Axis 7":
<img width="656" height="620" alt="Image" src="https://github.com/user-attachments/assets/33ba5e48-e831-42d3-b1bb-466d2b1819d0" />

With ExpressLRS BLE joystick I can see 9 axes but moving "S2" does nothing, and nothing moves "Axis 7" nor "Axis 8". Axes 0-6 work as expected. Buttons work as expected both over USB and BLE.
<img width="417" height="620" alt="Image" src="https://github.com/user-attachments/assets/e01a685a-34f1-4c77-b485-9a7b59c74db7" />

Any advice what to look for?

**Comment by mmilata** [comment]
However I can see the number change in `hid-recorder` - S2 changes the second "Slider":
```
# ReportID: 3 / Button: 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 
#             | X:  16393 | Y:  16393 | Z:     19 | Rz:     19 | Rx:     19 | Ry:  16393 | Slider:  16613 ,  16393 
#             | Hat switch:    0 
E: 000033.134817 20 03 00 00 09 40 09 40 13 00 13 00 13 00 09 40 e5 40 09 40 00
```
It's a little bit suspicious that both have the same usage in HID descriptor (0x36 Slider), perhaps this confuses linux? https://github.com/lemmingDev/ESP32-BLE-Gamepad/blob/master/BleGamepad.cpp#L424-L432

EdgeTX USB has "Dial" usage for the last axis:
```
#  Button: 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 | X:   1024 | Y:   1023 | Z:      0 | Rx:   1024 | Ry:      0 | Rz:      0 | Slider:   1035 | Dial:   1006 | Battery Strength:  100 
E: 000001.684807 20 00 00 00 00 04 ff 03 00 00 00 04 00 00 00 00 0b 04 ee 03 64
```

Gonna try changing `0x36` to `0x37` [here](https://github.com/lemmingDev/ESP32-BLE-Gamepad/blob/master/BleGamepad.cpp#L432) once I figure how to build this.

**Comment by mmilata** [comment]
Ok so I've tested that the following patch to `ESP32-BLE-Gamepad` fixes this on Linux.
```patch
--- a/BleGamepad.cpp
+++ b/BleGamepad.cpp
@@ -427,9 +427,9 @@ void BleGamepad::begin(BleGamepadConfiguration *config)
 
     if (configuration.getIncludeSlider2())
     {
-      // USAGE (Slider)
+      // USAGE (Dial)
       tempHidReportDescriptor[hidReportDescriptorSize++] = 0x09;
-      tempHidReportDescriptor[hidReportDescriptorSize++] = 0x36;
+      tempHidReportDescriptor[hidReportDescriptorSize++] = 0x37;
     }
 
     // INPUT (Data,Var,Abs)
```
Unfortunately it makes Liftoff lose the calibration data (due to different number of axes?) which sounds like bad news for backwards compatibility.

Need to test this on Mac, perhaps it handles report descriptors differently - that would explain the [inability to reproduce](https://github.com/ExpressLRS/ExpressLRS/issues/2136#issuecomment-1493159918).

**Comment by mmilata** [comment]
MacOS 26.1:
- on 3.6.2 I can't see CH8
- with the patch I can

Only tested on https://hardwaretester.com/gamepad
