### ISSUE TITLE
Jumper T-PRO is not flashing 3.x.x versions

### ISSUE THREAD

**Issue by Sautenich** [ExpressLRS/ExpressLRS#2141]
## Current Behavior

The Jumper is not able to update the ELRS module through Wi-Fi. I flash according to the guide here: https://www.expresslrs.org/quick-start/transmitters/aion-internal/
I did both with repartitioner file and without. Also, i've tried different approaches: flashing from 2.5.2, made it with OpenTx and EdgeTx. The flashing from 10.0.0.1 was always finished, but jumper was continuing to run Wi-Fi Update[x] for the infinite time. Lua scripts are working good with 2.5.2, and stopping to work with 3.x.x. 

## Environment

- TX hardware: Jumper T-PRO 
- RX hardware: Internal ELRS Module
- OpenTX version (including nightly number): EdgeTX(2.8.1 Flying Dutchman)
- ExpressLRS version (TX & RX MUST MATCH): 3.2.0

## Steps to reproduce
- Flashing from ELRS 2.x.x to 3.x.x.

thx

**Comment by pkendall64** [comment]
I found that flashing via EdgeTX passthrough works better for this. Just plug in USB (with the radio powered on), select USB Serial (VCP) then from configurator choose EdgeTxPassthrough as the flashing method, fill in your details (bind phrase etc) and Build and Flash.

This kind of question is better asked on discord BTW as it's not a bug. I verified I could flash mine and it works.
