### ISSUE TITLE
3.2.1 DIY_2400_RX_PWMP_via_UART losing and regaining connection

### ISSUE THREAD

**Issue by kolins-cz** [ExpressLRS/ExpressLRS#2156]
## Current Behavior

RC link is established, works for a moment (cca 1s) then link is lost. After two moments (2-3s?) link is regained and lost again. Repeats indefinitely. Receivers seems to NOT reboot in the process.

## Steps to Reproduce

1. Compile **3.2.1** for `DIY_2400_RX_PWMP_via_UART` target in latest configurator, upload

2. Link establishes and is lost immediately. Repeats

## Possible Solution (Not obligatory)

Downgrading RX to 3.1.2 solved the issue!

## Details

I have not tried different Packet rates and Telemetry Ratios. Not sure if it is OK to mix different versions, but it appears to workaround the issue.

## Your Environment

- TX hardware: BetaFPV MicroTx
- RX hardware: Matek R24-P6
- Handset model: Jumper T18
- OpenTX version (including nightly number) 2.3.15-otx
- ExpressLRS version (TX & RX MUST MATCH): 3.2.1
- Packet Rate: 333Hz Full
- Telemetry Ratio: 1:4
- user_defines:

`-DRegulatory_Domain_ISM_2400
-DMY_BINDING_PHRASE="verysecret"
-DLOCK_ON_FIRST_CONNECTION
-DAUTO_WIFI_ON_INTERVAL="30"
-DHOME_WIFI_SSID="kolin"
-DHOME_WIFI_PASSWORD="supersecret"
-DDISABLE_STARTUP_BEEP`

In `/hardware.html ` I have remapped two PWM pins (GPIO1, GPIO3) to output CRSF. It works well and should not be cause of the issue

**Comment by JyeSmith** [comment]
Do you mind also testing 3.2.0.

**Comment by kolins-cz** [comment]
> Do you mind also testing 3.2.0.
Tested:
3.2.0 works as supposed
3.2.1 dropping connection repeatedly

Hope this helps

**Comment by finkalexander** [comment]
I can confirm the behavior.

I used a RM Zorro (EdgeTX 2.8.2) flashed the internal ELRS module with 3.2.1 LBT, and two PWM receivers (Matek R24-P6 and BetaFPV Micro PWM) both flashed with 3.2.1 LBT. Both show the same directly starting after power on (~1s): dropping and reconnecting in a cycle.

The LED of the RXs is flashing when the connection ist lost.

I flashed both RXs with the 3.2.0 LBT and leave the Zorro on 3.2.1 LBT and the connection is stable even over 30min (telemetry looking fine). Flashed the RXs back to 3.2.1 LBT and the issue came back.

I also tried it with a Matek R24-D with 3.2.1 LBT and the link was stable. So it seems to be an issue with the PWM RXs.

Looks nearly the same as the issue: #1988

If I can help with any further investigation, I would be happy :-)

**Comment by pkendall64** [comment]
What you are doing is not really supported in anything less than master (3.3.0). Could you please test master.
On the master branch you do not need to make changes to the hardware.html page. You can select on the PWM page in Lua or WebUI "Serial TX/RX" for pins that support it. You can also choose the serial protocol to use.

**Comment by finkalexander** [comment]
Sorry, I don't understand it, what is not supported? At least from my side, I have never changed any hardware.html page. I only upgraded the RXs and TXs from 3.2.0 LBT to 3.2.1 LBT.

**Comment by pkendall64** [comment]
> Sorry, I don't understand it, what is not supported? At least from my side, I have never changed any hardware.html page. I only upgraded the RXs and TXs from 3.2.0 LBT to 3.2.1 LBT.

The remapping that the OP said in his description.

**Comment by pkendall64** [comment]
Would you mind flashing using the web-flasher https://pkendall64.github.io/elrs-web-flasher/
It uses the firmware that has been built on github. We have seen issues when using platformio (used under the hood with Configurator) on certain platforms before and it's the PWM devices that seem to show the issues.
This is part of the reason to move to cloudbuilds!

**Comment by RadekRadekP** [comment]
I am sorry, i have tried the web flasher, but I could not connect to my RX betatpf micro. Message "no device found"

**Comment by kolins-cz** [comment]
> Would you mind flashing using the web-flasher https://pkendall64.github.io/elrs-web-flasher/ It uses the firmware that has been built on github. We have seen issues when using platformio (used under the hood with Configurator) on certain platforms before and it's the PWM devices that seem to show the issues. This is part of the reason to move to cloudbuilds!


Well, just to be sure there is no mess in the receiver I have first run this:
` python -m esptool --port COM22 --chip auto erase_flash`

Then web flasher failed to communicate with my target. Not sure why (I am using original FTDI FT232H chip and Microsoft Edge), so I used this command:
`python -m esptool --no-stub --port COM22 --chip auto write_flash 0x00000 'D:\temp222\firmware.bin' --flash_size detect --flash_mode dio`

And version 3.2.1 downloaded from web flasher runs well.  I have even tried to modify my layout in `/hardware.html` and it does not break anything (I just moved pins 1 and 3 from PWM output to CRSF Serial Pins).

So after all, this really seems like a bug in Platformio

**Comment by RadekRadekP** [comment]
I have tried web flasher with serial port downloading and now RX betaftp micro seems running 3.2.1 smoothly. 
So probably the problem is caused by ELRS configurator.
 Is it possible give us some guide how to download firmware to RX through web flasher with using wifi? I am slightly lost with it.

**Comment by finkalexander** [comment]
After the hints from you, I've build (ELRS Configurator) the 3.2.1 LBT firmware on my Linux (Debian 11) and flashed the BetaFPV Micro PWM RX. The settings were exactly the same as I used on the prev. tests, but the firmware was build on Windows 11. I used WIFI to flash.

Now the interessting part: The 3.2.1 LBT firmware build on Linux works without any issue, I got a stable connection. :-)

**Comment by RadekRadekP** [comment]
I have probably found the way with ELRS configurator running on windows 11. 
I went to support menu. 
Chosen "CLEAR PLATFORMIO DEPENDECES" then "CLEAR FIRMWARE FILES". 
Then I have built and flashed through WIFI and voila my BETAFPV micro is running ELRS 3.2.1 smoothly. And the same good result wirth RX BETAFPV nano. Hopefuly the issue can be solved by resetting ELRS Cofigurator that way.

**Comment by pkendall64** [comment]
It's a weird platformio bug, that seems to jump around platforms, but mainly affects windows. We are hoping that along with the 3.3 release, there will be a new configurator that will use the binaries built on github rather than using platformio for released versions, possibly even for github branches and pull-requests.

**Comment by hprobst** [comment]
> > Do you mind also testing 3.2.0.
> 
> Tested: 3.2.0 works as supposed 3.2.1 dropping connection repeatedly
> 
> Hope this helps

I had the same issue with the BETAFPV micro and the **Happymodel ExpressLRS ELRS EPW6 TCXO 2.4GHz** receiver. I also **downgraded to 3.2.0 and it works** with both receivers.

**Comment by JyeSmith** [comment]
I also came across this when testing a PWMP on the weekend.  A clear and reflash fixed everything.

_shakes fist at PIO_

**Comment by howels** [comment]
Same issues with Matek R24-P6, repeated connection drops.

**Comment by Stormdad** [comment]
> Same issues with Matek R24-P6, repeated connection drops using 3.2.1

Same receiver same issue, flashing down to 3.2.0 works as it should.

**Comment by PetrSovis** [comment]
Same issue here on JHEMCU ELRS-2G4-P
3.2.0 works fine (at least it seems to)

**Comment by dingrgh** [comment]
I had the same problem with the Matek R24-P6 receiver - dropping and regaining connection at about once a second. This is with the recommended DIY_2400_RX_PWMPEX firmware on v3.2.1 and v3.2.0. I had to downgrade to v3.1.2 to get it to work.

Inrestingly, the flash was dome with ExpressLRS configurator which allowed me to write the firmware without errors. However, if I attempted to flash from the Access Point landing page, it would not allow the flash with a warning that the file size was too large.

**Comment by howels** [comment]
> I had the same problem with the Matek R24-P6 receiver - dropping and regaining connection at about once a second. This is with the recommended DIY_2400_RX_PWMPEX firmware on v3.2.1 and v3.2.0. I had to downgrade to v3.1.2 to get it to work.
> 
> Inrestingly, the flash was dome with ExpressLRS configurator which allowed me to write the firmware without errors. However, if I attempted to flash from the Access Point landing page, it would not allow the flash with a warning that the file size was too large.

I had to flash 3.2.0 with FTDI to get it working

**Comment by Stormdad** [comment]
> > I had the same problem with the Matek R24-P6 receiver - dropping and regaining connection at about once a second. This is with the recommended DIY_2400_RX_PWMPEX firmware on v3.2.1 and v3.2.0. I had to downgrade to v3.1.2 to get it to work.
> > Inrestingly, the flash was dome with ExpressLRS configurator which allowed me to write the firmware without errors. However, if I attempted to flash from the Access Point landing page, it would not allow the flash with a warning that the file size was too large.
> 
> I had to flash 3.2.0 with FTDI to get it working

I was having the same issue with the same rx. Clearing platformio dependencies and firmware files from within the configurators support tab seems to have resolved the issue, I am now running 3.2.1 just fine.

**Comment by howels** [comment]
> > > I had the same problem with the Matek R24-P6 receiver - dropping and regaining connection at about once a second. This is with the recommended DIY_2400_RX_PWMPEX firmware on v3.2.1 and v3.2.0. I had to downgrade to v3.1.2 to get it to work.
> > > Inrestingly, the flash was dome with ExpressLRS configurator which allowed me to write the firmware without errors. However, if I attempted to flash from the Access Point landing page, it would not allow the flash with a warning that the file size was too large.
> > 
> > 
> > I had to flash 3.2.0 with FTDI to get it working
> 
> I was having the same issue with the same rx. Clearing platformio dependencies and firmware files from within the configurators support tab seems to have resolved the issue, I am now running 3.2.1 just fine.

Strange. I tried this and got the same issue here. Staying on 3.2.0 for now.

**Comment by Vlady789** [comment]
I've had the same problem with multiple receivers. The receivers would bind and then immediately unbind and so on and so on. I did as  RadekRadekP propose at ELRS configurator - support tab "CLEAR PLATFORMIO DEPENDECES" then "CLEAR FIRMWARE FILES". I then recreated and uploaded the FW. This fixed the problem for all my receivers (Happamodel, Mateksys,...)

**Comment by tromax14** [comment]
I have same Issues.
My stuff
BetaFPV Nano RF module TX and BetaFPV Micro receiver PWN (5channel)

Betafpv ELRS Nano Module TX 2.4Ghz firmware 3.2.1 and Betafpv Micro 2400 PWM firmware 3.2.1 
Doesn't work

Betafpv ELRS Nano Module TX2.4Ghz firmware 3.2.1 and DIY 2400 PWM firmware 3.2.1
Doesn't work

Betafpv ELRS Nano Module TX 2.4Ghz firmware 3.2.1 and DIY 2400 PWM firmware 3.2.0
Work

I used ELRS Configurator 1.5.9 with windows 10 and Flash via Wifi

**Comment by dingrgh** [comment]
I can confirm that selecting "CLEAR PLATFORMIO DEPENDENCIES" and "CLEAR FIRMWARE FILES" in the Support tab in ExpressLRS Configurator before building and flashing will fix this problem. My receiver is the Matek R24-P6.
