### ISSUE TITLE
DIY 900 RX TTGO V1 SX127x - display, serial, binding issues.

### ISSUE THREAD

**Issue by FlackMonkey** [ExpressLRS/ExpressLRS#2158]
## Current Behavior

I try to bind using same BINDING_PASSPHRASE a pair of TTGO V1 SX127x.

After flashing DIY 900 **TX** TTGO V1 SX127x:
1. OLED displays:  logo -> No handset -> WIFI name, password, IP
2. Wifi ExpressLRS TX works

After flashing DIY 900 **RX** TTGO V1 SX127x:
1. OLED display shows nothing
2. Wifi ExpressLRS RX works
3. Serial monitor  shows strange symbols(baud rate 115200) : $�$�����5�5�����������$�$�����5�5

![image](https://user-images.githubusercontent.com/8100723/230062780-16890d83-7c4b-4931-ad0e-78a10398f385.png)

## Steps to Reproduce

Configurator -> git branch -> master -> DIY 900 MHz -> DIY 900 RX TTGO V1 SX127x -> Flashing Method: UART

## Expected Behavior for RX

1. OLED display shall show meaningful info
2. Serial monitor shall print meaningful info

**Comment by pkendall64** [comment]
As the error message on the OLED says, you have no handset connected and it's not getting any CRSF packets.
In this case the TX will not start the RF and will not try connecting to the RX.
On the RX side, if you change the baud rate to 420000, you should see a start up message. You might need to connect to it with a decent serial converter as I think the build in USB does not like that baud rate.
