### ISSUE TITLE
[Windows 10] BLE Joystick Channel Centers Incorrect

### ISSUE THREAD

**Issue by bfahrenfort** [ExpressLRS/ExpressLRS#2160]
## Current Behavior

On v3.2.1, on the internal ELRS module for a TX16S MkII, all exposed channels are at 50% in Windows when at 0% in hardware and EdgeTX.

## Steps to Reproduce

1. Install STM32 driver to enable flashing

2. Connect TX16S internal to ELRS Configurator and flash with EdgeTxPassthrough

3. Connect ELRS's BLE Joystick to Windows

4. Test the channels in Control Panel's "set up USB game controllers" (photos are on 3.2.1 and 3.01, respectively)
![axes at incorrect centers, 3.2.1](https://i.imgur.com/Pp8hK2b.png)
![axes at center, 3.0.1](https://i.imgur.com/8r1heb3.png)

## Details

This occurred on the first flash from 3.0.1 (factory) to 3.2.1. Reflashing did not solve the issue. I've tried with both the factory lua script and the lua script from the configurator for 3.2.1. In 3.0.1 before flashing, the problem did not occur. ~~I haven't tried downgrading yet.~~ The issue is never present in 3.0.1. 

## Your Environment

- TX hardware: TX16S MkII internal ELRS module
- RX hardware: Windows 10 laptop
- EdgeTX version (including nightly number): 2.7.1(a55aff02)
- ExpressLRS version (TX & RX MUST MATCH): 3.2.1 (8dbbdb)
- Packet Rate: F1000(-104dBm)
- Telemetry Ratio: 1:128

**Comment by pkendall64** [comment]
There have been updated in version 3.3 which will be out "real-soon-now". I have tested on windows 10 and the controls react as expected.
