### ISSUE TITLE
No error when target does not match during wifi update

### ISSUE THREAD

**Issue by jurgelenas** [ExpressLRS/ExpressLRS#2189]
I was able to flash Vantac Lite TX firmware to Radiomaster Ranger 2.4 GHz without any confirmations when using latest configurator nightlies on master.

![image](https://user-images.githubusercontent.com/1081265/235347891-227eafae-ef66-40ef-984a-f374cd7ea238.png)

Does it fail silently or just proceed with the update anyway?

**Comment by pkendall64** [comment]
This has actually been a problem for some time. It's because we use the PIO target name and now all the targets are actually the same thing. We need to use the json path as the target so we can verify using that instead in future.
