### ISSUE TITLE
No build target for BetaFPV ELRS Micro Receiver

### ISSUE THREAD

**Issue by RobertoD91** [ExpressLRS/ExpressLRS#2214]
There is no target for "Betafpv ELRS Micro Receiver" (official link: https://betafpv.com/collections/expresslrs-series-accessories/products/elrs-micro-receiver ).

BetaFPV's documentation is outdated and only covers ExpressLRS v2.

~~The targets "BETAFPV Nano 2400 RX" and "BETAFPV PWM 2400 RX" don't work.~~

The target "BETAFPV Nano 2400 RX" don't work

The targets "DIY 2400 RX PWMP" and "BETAFPV PWM 2400 RX" seems to work, tested only with PWM servos

**Comment by RobertoD91** [comment]
Maybe I should have opened the issue on ExpressLRS/ExpressLRS-Configurator.

If I understand correctly, `BETAFPV PWM 2400 RX` is an alias for `DIY 2400 RX PWMP`

**Comment by pkendall64** [comment]
`BETAFPV PWM 2400 RX` is the correct target. So we'll close this ticket.
