### ISSUE TITLE
Check frequency correction on true diversity / gemini system

### ISSUE THREAD

**Issue by SunjunKim** [ExpressLRS/ExpressLRS#2221]
Just a point for future discussion:

* Given the antenna alternation (#2002), it's possible that TX and RX's Radio1&Radio2 may not be correctly paired in Gemini mode.
* If we can ensure that every Gemini TX&RX on the market uses a shared TCXO, this issue may not occur.
* We need to re-examine how the frequency correction functions (`FreqCorrection` and `FreqCorrection_2`) work on the 900M TD RX.

**Comment by pkendall64** [comment]
@SunjunKim do you want to keep this open?

**Comment by SunjunKim** [comment]
> @SunjunKim do you want to keep this open?

Antenna alternation was dropped. so it's safe to be closed ATM.
