### ISSUE TITLE
First 4 channels are inactive

### ISSUE THREAD

**Issue by Romeo84095** [ExpressLRS/ExpressLRS#2233]
## Current Behavior

First 4 channels are inactive (using betaflight).
I use: ExpressLRS receiver, Jumper T-Pro tx

## Steps to Reproduce

1. Connect RX to F4 flight controller

2.Set up as described at
https://www.expresslrs.org/quick-start/receivers/configuring-fc/

3.Just faced with issue. See screenshot
[https://i.postimg.cc/SNcmmnbD/Scr002.jpg](https://i.postimg.cc/SNcmmnbD/Scr002.jpg)

## Your Environment

- Jumper T-Pro with latest Edge TX software + external ExpressLRS Transmitter with latest firmware:
- Express LRS receiver with latest firmware .
I also tried to use FRSky XP+ receiver - the same
BUT: before i used FrSky TX - and all was OK. So i think problem with radio maybee or tx
- Handset model:
- Edge TX - latest
- ExpressLRS version: latest
- Packet Rate:
- Telemetry Ratio: default
- user_defines: default

**Comment by pkendall64** [comment]
I've just test this on my T-Pro and everything works as expected.
For a help and support you should join discord and ask in the #help-and-support channel and I'm sure the friendly folk there will get you sorted.
