### ISSUE TITLE
HiYOUNGER TX2G4 2400 TX  upgrade from 2.5.2 to 3.2.1 that not connection with TX16S

### ISSUE THREAD

**Issue by lhh6688** [ExpressLRS/ExpressLRS#2235]
HiYOUNGER TX2G4 2400 TX  upgrade from 2.5.2 to 3.2.1 that not connection(not  LUA ) with TX16S

**Comment by pkendall64** [comment]
For help in regards to issues like this, you should join discord and ask in the #help-and-support channel.
