### ISSUE TITLE
Problem when running multiple receivers with Radiomaster ER5A receiver

### ISSUE THREAD

**Issue by thbossum** [ExpressLRS/ExpressLRS#2248]
I run two Radiomaster ER5A receivers to get enough channels. One receiver must then run with telemetry turned off.

The receiver without telemetry have only 10-20 meters range, but the other one has "normal" range. If the receiver without telemetry runs alone, range is then "normal". I learned that a Radiomaster ER5A with telemetry on will affect the range on any other receiver running without telemetry. I have at least tried some Mateksys receivers and got same problem when they run witout telemetry together with the ER5A with telemtry on. When I turn it around using for example a Mateksys receiver with telemetry turned on, no other receivers running without telemetry seems to be affected at all, including the Radiomaster ER5A.

I think there is a bug in the firmware for the ER5A receiver causing this.
I almost crashed my plane because of this...

TX Hardware:
I am running FlySky NV14 transmitter (with power mods) with Happymodel ELRS 2.4GHz Slim Pro nano module

- Transmitter firmware: EdgeTX 2.8.4 and ELRS 3.2.1

Receivers included in my testing all running ELRS 3.2.1:
3x Radiomaster ER5A, 1x Mateksys PWM 6 ch, 1x Mateksys PWM 5 ch, 1x Mateksys R24-D and Mateksys R24-S

- Packet Rate: 333Hz, 8  channel mode, Receiver ID: on
- Telemetry Ratio: Std.

**Comment by mawzthefinn** [comment]
Would recommend trying current firmware (3.3.x or 3.4.1) and seeing if the issue remains.
