### ISSUE TITLE
Wrong "rf profile" value in link Statistic" packages (0x14) for Packet Rate 50

### ISSUE THREAD

**Issue by m-rik-prog** [ExpressLRS/ExpressLRS#2261]
In the "Link Statistic" packages (0x14) in "rf_profile" you actually use the value 2 for Packet Rate 50 (Channels Frame rate at 50Hz), a value that TBS has been using for years for Frame rate 150fps, instead the value 3 should be used since it is unused for your 50Hz frame rate transmission.
Currently this causes a conflict in automatic frame rate settings, protocol recognition and fades calculation.

**Comment by pkendall64** [comment]
We are not TBS or Crossfire. The values we use match the rates that we have in ELRS.
