### ISSUE TITLE
LiteRadio 3 Pro - not compiling Betaflight script

### ISSUE THREAD

**Issue by odixxx** [ExpressLRS/ExpressLRS#2276]
when trying to compiling  Betaflight Setup script - Syntax Error

![20230627_100823](https://github.com/ExpressLRS/ExpressLRS/assets/12283233/7b123c98-6c3d-4fa3-b7b4-10d706f2fcb5)

My setup:
Betaflight TX Lua Scripts 1.7.0
Betaflight 4.4.2
EdgeTX v2.8.4

ps. on another radio X9D Plus everything works fine!

**Comment by jurgelenas** [comment]
It looks like you have not copied every file from betaflight lua files bundle.

You need to place all these directories inside your `SCRIPTS` directory:

![image](https://github.com/ExpressLRS/ExpressLRS/assets/1081265/347a3c11-73eb-4318-a7ec-4bc90a14f969)

Also, this is ExpressLRS Configurator repository and we have very little to do with Betaflight LUA scripts over here.

I suggest you to follow installation guide: https://github.com/betaflight/betaflight-tx-lua-scripts#installing

Happy Flying!
