### ISSUE TITLE
Matek ELRS R24-P PWM receiver looses connection every 5 secs on ELRS 3.2.1

### ISSUE THREAD

**Issue by Kaggen67** [ExpressLRS/ExpressLRS#2277]
## Current Behavior

Matek ELRS R24-P PWM recievier looses connection every 5 secs on ELRS 3.2.1 (behaviour seems similar or the same as issue #1988). Using REGOLATORY_DOMAIN_ISM_2400.

## Steps to Reproduce

I'm using Radiomaster Zorro using EdgeTX 2.8.4 with internal ELRS module.

1. Flashing TX (Radiomaster Zorro) with ELRS 3.2.1 using ELRS configurator.

2. Flashing receiver Matek ELRS-R24-P PWM with ELRS 3.2.1 using REGOLATORY_DOMAIN_ISM_2400, LOCK_ON_FIRST_CONNECTION using ELRS configurator.

3. Bind TX and RX and connect a servo to test.

4. Get telemetry lost and connection lost and the led on the receiver start to blink. The servo doesn't respond. After about 2-5 seconds it connects again, and after 5-10 seconds i get another connection and telemetry lost. ...and so it continues...

## Possible Solution (Not obligatory)

The solution for now is to use 3.2.0 on the RX.

I flashed the receiver with ELRS 3.2.0 with the exact same settings in ELRS configurator. Still using 3.2.1 on the TX. No changes on either the radio or the receiver regarding power, packet rates or telemetry ratio, and it works flawlessly. I tested, using 10mW power,  for about 20 minutes with different distances between RX and TX and didn't get a single lost connection or telemetry lost.

## Details

I tried to fiddle with the settings in the ELRS lua script settings on both the radio and the receiver, different packet rates (lowering them) different Telemetry ratio and different power. Nothing helped (still the same problem). When i flashed the RX with 3.2.0 everything worked ok. Still using 3.2.1 on the radio. So something seems broken in 3.2.1 at least for Matek R24-P PWM receiver.

Unfortunatly i have no other ELRS PWM receiver to test. I have a Matek R24-S ELRS receiver (for quads) and that didn't have this problem with the 3.2.1 firmware. Seems only to affect the PWM receiver.

It very much looks like the issue #1988 (with 3.1.1 version). Although i updated from 2.5.1 so i havent used the 3.1.1 version. 2.5.1 also worked fine for me on this same receiver.

## Your Environment

- TX hardware: Radiomaster Zorro with EdgeTX 2.8.4 and built in ELRS module with 3.2.1
- RX hardware: Matek ELRS R24-P PWM with ELRS 3.2.1
- Handset model: EdgeTX 2.8.4
- ExpressLRS version (TX & RX MUST MATCH): 3.2.1
- Packet Rate: Same problems no matter which rate. Tested 50 to 500.
- Telemetry Ratio: Tested all inc. std
- User defines:

-DRegulatory_Domain_ISM_2400
-DMY_BINDING_PHRASE="XXXXXXX"
-DLOCK_ON_FIRST_CONNECTION
-DAUTO_WIFI_ON_INTERVAL="60"
-DFAST_SYNC

**Comment by dingrgh** [comment]
This is the same issue documented in #2156. 

The fix is to select "CLEAR PLATFORMIO DEPENDENCIES" and "CLEAR FIRMWARE FILES" in the Support tab in ExpressLRS Configurator before building and flashing.
