### ISSUE TITLE
DIY Tx power will not go beyond 25mw when built using FCC mode 3.3RC2

### ISSUE THREAD

**Issue by asudhir1947** [ExpressLRS/ExpressLRS#2285]
## Current Behavior
I can select the TX power all the way upto 250mw on my DIY tx module, sitting inside a Frsky XLite, using the regular v3.0 Lua

I updated to 3.3 RC2 and the TX power would not go beyond 25mw, flashed back to 3.2.1 and I can select power all the way upto 250mw
## Steps to Reproduce
Update the DIY Tx module to RC2
Run Lua
Initially the Lua says error on the power level, but I can then change it to 25mw or 10mw and set it there.

1.

2.

3.

4.

## Details

 Issue does not affect me as I normally use 25Mw, but I dont want to be stuck there
 No

## Your Environment

- TX hardware: DIY Elrs TX module with build suggestion from tweetfpv
- RX hardware: happymodel ep1
- Handset model: frsky xlite
- OpenTX version (including nightly number)
- ExpressLRS version (TX & RX MUST MATCH): 
- Packet Rate: 500hz
- Telemetry Ratio: 1:128
- user_defines: None

**Comment by pkendall64** [comment]
I would say that you have flashed the wrong target. The DIY Mini does only 10 and 25mW.
You may be looking for the DIY E28 target.
I can't tell though because you have not given exact information about the target i.e. the target name you flashed from configurator.

**Comment by asudhir1947** [comment]
Hi, you are right, I used the DIY Mini, that is the only target that supports ESP32 SX1280 and can also confirm I see mini in the elrs lua script, would the E28 target be good enough for my target ? I built the tx using the tutorial from tweetfpv, so not sure if the E28 would be good enough

**Comment by pkendall64** [comment]
If you previously had 250mW then you are probably after this target
![Screenshot 2023-07-05 at 3 02 22 PM](https://github.com/ExpressLRS/ExpressLRS/assets/512740/56fc01f7-6d6d-410a-bf62-6500f834f8a2)

**Comment by asudhir1947** [comment]
Thank you that worked, able to change output power level to 250mw now once again
