### ISSUE TITLE
BetaFPV SuperP 14Ch Receiver wrong Voltage reading (RxBt)

### ISSUE THREAD

**Issue by 3DRacer** [ExpressLRS/ExpressLRS#2296]
The Voltage reading at VBAT/6s Pin is mutch to high. The ADC also seems to be at the end at about 8.4V. Higher values don't change anything anymore. BetaFPV does not seem to mean 6s LiPo at all.

Device: BetaFPV SuperP 14Ch Receiver
elrs 3.3.0-RC2

**Comment by pkendall64** [comment]
https://github.com/ExpressLRS/ExpressLRS/assets/512740/5f5cbff5-f22a-4113-8bb2-6894428b2d66

Heres a video showing the SuperP going from 25V to 3V input on the VBAT pins. Note that the receiver is not powered by the VBAT connector.

**Comment by 3DRacer** [comment]
Thanks for the video. I tested in same condition. My receivers have an HW issue. I will contact betafpv. I bought several of these directly from there shop. all have same behavior.

![20230709_081458](https://github.com/ExpressLRS/ExpressLRS/assets/42546574/44b97006-672a-481d-9586-c9e31d812c2f)
![20230709_081410](https://github.com/ExpressLRS/ExpressLRS/assets/42546574/bce7b327-dbb6-48fc-b960-4325d2907711)
![20230709_081343](https://github.com/ExpressLRS/ExpressLRS/assets/42546574/69f5f191-d77e-406d-a411-c95507afca94)

**Comment by pkendall64** [comment]
Can you start the receiver in wifi mode and go the `/hardware.html` page and verify that the options for VBAT are as expected.
![IMG_0401](https://github.com/ExpressLRS/ExpressLRS/assets/512740/f083df8d-8081-435e-b72c-59db465c0b95)

**Comment by 3DRacer** [comment]
![grafik](https://github.com/ExpressLRS/ExpressLRS/assets/42546574/5ff00b76-928b-4b12-8a90-60dde66d2ecb)

**Comment by 3DRacer** [comment]
I suspect wrong resistors in the ADC divider. Can someone please measure the resistance between VBAT and GND on their SuperP? Mine are all 77.8 KΩ.

here again all values of the HW side

![grafik](https://github.com/ExpressLRS/ExpressLRS/assets/42546574/920dd9b3-1e9f-43f9-b408-fb868dcde830)

**Comment by pkendall64** [comment]
I spoke with BETAFPV today and the values we have used here are based on the samples we were sent, and in the production unit the resistor values have changed.
You could just change the `285` in the scale to `64` and I think that will be closer. We will have to get some new devices so we can properly calibrate them.

**Comment by 3DRacer** [comment]
I set the VBat scale value to 64. This produces an output of 162 Volts at 8.00V on the VBAT. I then played with the values on VBat scale and the value 1280 fits best.
Thus, VBAT and telemetry between 0.60V and 8.00V fits well.
BUT: Voltages above approx. 8 volts are not recorded by the ADC. The original problem still exists.

**Comment by 3DRacer** [comment]
thanks man. you made my day. short test before sleeping time shows it work. Changes of values up to 25 Volts at VBAT Pin. Tomorrow i will find out optimal values for span. Thanks a lot

**Comment by pkendall64** [comment]
> thanks man. you made my day. short test before sleeping time shows it work. Changes of values up to 25 Volts at VBAT Pin. Tomorrow i will find out optimal values for span. Thanks a lot

You're welcome. BETAFPV are sending production units to the devs so we can calculate a proper set of calibration values. So I'll update this ticket once I get it.

**Comment by 3DRacer** [comment]
Here are my determined values for the SuperP.
Measurement results (Calibrated DVM):
VBAT ----- RxBt
 5.00V ---- 5.0
10.00V --- 10.0
15.00V --- 15.0
20.00V --- 20.0
24.00V --- 23.8
VBAT > 24 volts results in non-linear values.

![grafik](https://github.com/ExpressLRS/ExpressLRS/assets/42546574/e6b2b87c-3201-4970-84be-928c67a1f154)

**Comment by pkendall64** [comment]
Hi, I've received some production units from BetaFPV and performed the calibration and come up with some new values.
Added in PR #2307
