### ISSUE TITLE
RX will often automatically enter the BING state

### ISSUE THREAD

**Issue by YI-BOYANG** [ExpressLRS/ExpressLRS#2300]
In the process of using ELRS RX, the RX that has been bound often appears, and it will re-enter the bound state after power on again, that is, the LED will flash twice.
I can use TX to rebind, but RX will often get into the bind state later.

I wonder if there is a possibility that when I power on the plane, because of the bad plug contact, the plane actually generates several power pulses in a very short period of time, which mistakenly triggers the RX to enter the binding state?

**Comment by pkendall64** [comment]
Yes, that is quite possible. No fix this do NOT use traditional binding (via the transmitter) but enter the binding phrase on the receivers web-UI.

This problem has been seen by other users because of power brownouts on the model.
