### ISSUE TITLE
3.3.0 final release shows unclear version in LUA script

### ISSUE THREAD

**Issue by jiri-jirus** [ExpressLRS/ExpressLRS#2314]
Hello, after final release 3.3.0, lua script reports "3.x.x-maintenance EU868" for in lua script on my TX16s. (also on my ES24TX) This way, I dont know which version is loaded on module. I suppose this is not desired behaviour as I expect to see "3.3.0"

![unclear](https://github.com/ExpressLRS/ExpressLRS/assets/21183381/1b054d92-15dc-4d8b-984a-66218f0728db)

**Comment by pkendall64** [comment]
We are aware of this, there was a bit of an issue where the 3.x.x-maintenance branch was re-pushed to the repository after the 3.3.0 release with the same git hash so it overwrote the artifacts. They are 100% the same though.

**Comment by offer-shmuely** [comment]
maybe we can get 3.0.1 with the fix?
we do like to remember, in the future, what the version that we installed

**Comment by jiri-jirus** [comment]
> maybe we can get 3.0.1 with the fix? we do like to remember, in the future, what the version that we installed

probably 3.3.1
