### ISSUE TITLE
elrsV3.lua version 3.3.0 fails to load with 'Loading ???' showing on screen indefinitely

### ISSUE THREAD

**Issue by philipcllau** [ExpressLRS/ExpressLRS#2318]
## Current Behavior

Installed 3.3.0 version of elrsV3.lua to Frsky Taranis Xlite Pro(OpenTX-2.3.14). Executing the elrsV3.lua script results in screen Loading ??? indefinitely

## Steps to Reproduce
Download version 3.3.0 elrsV3 .lua script from ExpressLRS Configurator 1.6.0.
Copy elrsV3.lua via usb to Frsky Taranis Xlite Pro. Restart Frsky controller, then execute elrsV3.lua.

1.

2.

3.

4.

## Details

Went down the route of downgrading to version 3.2.1 elrsV3.lua. Downloaded and copied via usb to Frsky Taranis Xlite Pro. Executing elrsV3.lua works as expected

Upgrading receivers and transmitter to latest elrs version 3.3.0

## Your Environment

- TX hardware: HM ES24TX Slim Pro
- RX hardware: HM EP2 RX
- Handset model: Frsky Taranis Xlite Pro
- OpenTX version (including nightly number): 2.3.14-otx (1e09791a)
- ExpressLRS version (TX & RX MUST MATCH):
- Packet Rate: N/A
- Telemetry Ratio: N/A
- user_defines:

**Comment by pkendall64** [comment]
Please ask this question on our discord server in the #help-and-support channel. One of the helpful folk there will walk you through the steps you need to get this working.
