### ISSUE TITLE
Model Match greater than 14 hangs elrsV3.lua

### ISSUE THREAD

**Issue by analogsoftware** [ExpressLRS/ExpressLRS#2329]
## Current Behavior

Assigning a model match number greater than 14 hangs elrsV3.lua script, preventing further configuration of ELRS parameters. I do not know if it is the actual number "15" or the fact that I have 15 actual receivers configured - I presume it is the latter and the actual number is irrelevant as long as it is between 0-63.

## Steps to Reproduce

1. Create 14 ELRS models and verify you can access the elrsV3.lua script to configure parameters.

2. Create one more model, and elrsV3.lua hangs on open.

## Possible Solution (Not obligatory)

Disabling model match on the 15th model allows the elrsV3.lua script to open.

## Details

I have a total of 80 models on this transmitter, using various other protocols mostly DSMX and FrSky.

## Your Environment

- TX hardware: RadioMaster TX16S-II internal 4-in-1 + HM ES24TX Pro Micro TX module
- RX hardware: RadioMaster ER6-GV; Matek R24D
- Handset model:
- OpenTX version (including nightly number) EdgeTX 2.9.0-selfbuild
- ExpressLRS version (TX & RX MUST MATCH): TX: 3.3.0; RX: 3.3.0
- Packet Rate: 100Hz Full
- Telemetry Ratio: 1:8
- user_defines: none

**Comment by pkendall64** [comment]
I think theres something else going on here.
I've just created 15 models each with a different receiver id, and model match turned on in the Lua script and these no problem whatsoever.

There is another problem that could cause the Lua lockup, especially with external modules on 500Hz, could it be that this is your problem?

**Comment by analogsoftware** [comment]
PKendall64 - I think you may be right. Would this be Issue #2327 you are referring to?
I added another receiver and was able to document what is happening with screenshots.
I copied the previous model no. 15, Note Receiver ID is 0 and Status is 100Hz:
![screen-2023-07-28-034007](https://github.com/ExpressLRS/ExpressLRS/assets/7537405/08b671bc-3d11-41be-8d3b-bdef82600584)
Changed to ID 15 and Status is still 100 Hz:
![screen-2023-07-28-034024](https://github.com/ExpressLRS/ExpressLRS/assets/7537405/1b164245-1e1f-4a45-a992-fad155ea20ec)
Changed to ID 16 and Status is now 500 Hz:
![screen-2023-07-28-034033](https://github.com/ExpressLRS/ExpressLRS/assets/7537405/5ca843c8-2d37-4447-a1e6-0965bb353314)
Referring to Issue #2327 changed Baudrate to 115k:
![screen-2023-07-28-034058](https://github.com/ExpressLRS/ExpressLRS/assets/7537405/1b01dab4-216d-40be-a796-d3802c2c65c4)
I was now able to run the Lua script. Note Packet Rate is 100Hz and Model Match ID is 0 (should be 16):
![screen-2023-07-28-034133](https://github.com/ExpressLRS/ExpressLRS/assets/7537405/aabb31a7-1c0d-4cc7-b987-4d470fc27982)
Went back to External Module setup and changed Baudrate to 400 Hz:
![screen-2023-07-28-034209](https://github.com/ExpressLRS/ExpressLRS/assets/7537405/d370bd60-3658-48b2-bd29-9ad92a290e55)
Still able to run the Lua script but Model Match ID is still 0:
![screen-2023-07-28-034300](https://github.com/ExpressLRS/ExpressLRS/assets/7537405/574bc480-0564-4d9a-b6a4-5cc18d98712a)
I was distracted while working on receiver 15 and discovered the next step by accident. I power-cycled the transmitter
and when I ran the Lua script, after a delay, only the Packet Rate line displays with 500 Hz selected. For receiver 16 I timed the delay and it was 27 minutes:
![screen-2023-07-28-041746](https://github.com/ExpressLRS/ExpressLRS/assets/7537405/3de89a2c-2dd1-472f-9db7-081aa56b0b1b)
I changed Packet Rate to 100hz:
![screen-2023-07-28-041802](https://github.com/ExpressLRS/ExpressLRS/assets/7537405/06c19b2b-af23-43f3-953e-2622eec6b09d)
After changing to 100 Hz Packet Rate the remainder of the Lua script interface appears; note the Model Match ID is now 16. After this everything works as expected.
![screen-2023-07-28-041817](https://github.com/ExpressLRS/ExpressLRS/assets/7537405/b601527e-43f3-4780-bb33-4c349b9c6024)

I would not say this is a work around as waiting 27 minutes to be able to change the packet rate is not reasonable, but at least I was able to get these 2 latest receivers working. It appears there is some interaction somewhere which is setting Packet Rate to 500 Hz despite the interface showing 100 Hz.

**Comment by pkendall64** [comment]
Yes, when you change the receiver number the radio sends that to the module. The module then loads it's configuration for that number, the default rate is 500Hz, which should be limited by the baud rate. This last part is where the bug is that #2327 fixes.
Maybe we just leave the issue title, but I add a fixes comment to #2327
