### ISSUE TITLE
DIY 3.3 Targets

### ISSUE THREAD

**Issue by lesharodin** [ExpressLRS/ExpressLRS#2330]
Hi, could we please get DIY targets back to configurator?
Generic works fine but this confuses many users.

**Comment by pkendall64** [comment]
The ones that are actually DIY are labelled as such.
Te ones that were labelled as DIY but are generic as they are what we recommend as pin configurations for manufacturers have been renamed to Generic.
This will not be changed again.

**Comment by kindssss** [comment]
hallo how to upgrade firmware 2.5.2 for 3.0.0 with target device diy_2400_esp8285_sx1280? while the target device does not exist? 
please help thx

**Comment by pkendall64** [comment]
Choose these options
![Screenshot 2023-11-18 at 7 37 01 AM](https://github.com/ExpressLRS/ExpressLRS/assets/512740/a9705df5-2a93-4d9e-b156-3df45e924da6)

This question is really best asked on discord. If you have any further questions please ask in the #help-and-support channel there.
