### ISSUE TITLE
Lost WIFI function on TX and RX

### ISSUE THREAD

**Issue by Kallepitch** [ExpressLRS/ExpressLRS#2331]
## Expected Behavior
TX - After enabling WIFI Mode in LUA Script, TX-Module should establish a WIFI Network
RX - After powering up the RX should establish a WIFI network after 60 seconds

## Current Behavior
TX - No WIFI established
RX - No WIFI established

## Steps to Reproduce

Flashed TX and RX with Configurator 1.6.0 to FW-Version 3.2.0, encountering the described issue. After this, I rolled back the FW to 3.0.0 - issue is still exist.

## Your Environment

- Operating System and version:
- TX hardware: Radiomaster Ranger Micro
- RX hardware: Radiomaster EP1

**Comment by pkendall64** [comment]
I think you be best to ask on discord about this in the help-and-support channel.
If you have configured your device with your home wifi credentials then it will not create a access-point if it can connect to your home wifi. The LED will still goi into the fast-flashing mode showing that has gone into wifi mode.
