### ISSUE TITLE
HM ES900TX lost option to enable 500mW, 1W or 2W

### ISSUE THREAD

**Issue by jiri-jirus** [ExpressLRS/ExpressLRS#2347]
## Current Behavior

HM ES900TX lost option to enable 500mW, 1W or 2W. 
Lua script does not offer these values. Currently sold ES900TX has heatsink and fan installed, Happymodel also declares maximum output power of 33dBm (2W). 
Also, there is not option in ExpressLRS Configurator to "unlock higher power", so user has to go to /hardware.html and guess power level values.

## Steps to Reproduce
Start lua script and try to enable higher power than 250mW on HM ES900TX.

## Possible Solution (Not obligatory)
Enable higher power level values.

## Your Environment

- TX hardware: HM ES900TX with heatsink and fan (stock)
- RX hardware: HM ES900RX
- Handset model: RM TX16S
- OpenTX version (including nightly number). EdgeTX 2.8.4
- ExpressLRS version (TX & RX MUST MATCH): 3.3.0
- Packet Rate: 200Hz
- Telemetry Ratio: 1:32
- user_defines:

**Comment by darkshark2** [comment]
So no solution?

**Comment by pkendall64** [comment]
Yes, put the module into wifi mode. Go to /hardware.html page and change "High Power" to 1000mW and save the config.
This module is NOT a 2W module though, even back in 2.5 it was 1W max. This will get it so you can select up to 1W in the Lua until we fix the target definition.

**Comment by yblpoi** [comment]
ES900TX：
MCU:ESP32+ESP8285
Dimension: 55mm*39mm*11mm
Weight: 9.2gram (only the TX module)
Antenna connector: SMA
VCC input: 5~13v, Recommend 5v~9v
RF Frequency optional: 915mhz or 868mhz(EU)
Maximum Output Power: **<33dBm** (For >27dBm operation, we recommend add a fan for force cooling)
Wifi update firmware function for ES900TX would be available in a short time.

[official link](https://www.happymodel.cn/index.php/2021/02/19/expresslrs-module-es915tx-long-range-915mhz-transmitter-and-es915rx-receiver/)

This module can support 2W power transmission

**Comment by jiri-jirus** [comment]
> Yes, put the module into wifi mode. Go to /hardware.html page and change "High Power" to 1000mW and save the config. This module is NOT a 2W module though, even back in 2.5 it was 1W max. This will get it so you can select up to 1W in the Lua until we fix the target definition.

is this enough? power level value will be missing imho.

**Comment by pkendall64** [comment]
There is no power value for 2W and there never has been from looking at the history. The ES915TX, which is STM32 based on the other hand does have a 2W power output.

**Comment by jiri-jirus** [comment]
well, 1W should be sufficient.
