### ISSUE TITLE
Radiomaster ER8GV no ability to play vario

### ISSUE THREAD

**Issue by miggy1952** [ExpressLRS/ExpressLRS#2349]
![screenshot-2023-08-08-45772](https://github.com/ExpressLRS/ExpressLRS/assets/88764415/58e3d98c-7f6e-4f36-b584-1a583f5df20e)
![screenshot-2023-08-08-45737](https://github.com/ExpressLRS/ExpressLRS/assets/88764415/9bb4aa1c-e3b9-44b7-aa6b-8c111b941de5)
access to "play vario" in the telemetry sensor menu as in the second screen shot
No 
- TX hardware: FrSky X18S firmware 1.4.9, EU
- RX hardware: Radiomaster ER8GV running v 3.3.0
- Handset model:
- OpenTX version (including nightly number)
- ExpressLRS version (TX & RX MUST MATCH):
- Packet Rate: 100Hz Full
- Telemetry Ratio: 1:16

**Comment by miggy1952** [comment]
Thanks, I will post on the ETHOS GitHub

**Comment by miggy1952** [comment]
My Matek ELRS vario is working fine, maybe it IS an ELRS issue?

**Comment by miggy1952** [comment]
The working Matek one has a telemetry ID of 07 and the new not working Radiomaster has an id of 09 if that helps

**Comment by pkendall64** [comment]
ELRS is calculating the altitude and vertical speed and sending the data as `CRSF_FRAMETYPE_BARO_ALTITUDE` which is type 9.

**Comment by miggy1952** [comment]
OK but how does that help me to play the vario?

**Comment by pkendall64** [comment]
It doesn't help you I suppose. As was mentioned before it looks like it's an ETHOS issue.

**Comment by miggy1952** [comment]
[mawzthefinn](https://github.com/mawzthefinn) thought it was an ELRS issue

**Comment by Hiosl** [comment]
I am having the same issue with a ER6GV, ELRS V3.3 and a Radiomaster TX16S with EdgeTX 2.7.1. Telemetry shows the altitude but not VSPEED. Was working fine before, using the Matek Vario RX.

Tried setting the ID to 009 (instead of ID007), but then it only shows altitude.

**Comment by miggy1952** [comment]
Is it possible to change the sensor ID in the ER8GV? 

In ETHOS the sensor ID fields are "Greyed Out" and not available to edit.

**Comment by miggy1952** [comment]
[pkendall64](https://github.com/pkendall64) tells me that.

"If we change it ETHOS then we break EdgeTX. I think EdgeTX has a much bigger community. Perhaps a bug report for ETHOS is a better place to start."

[mawzthefinn](https://github.com/mawzthefinn) told me that:

That’s wrong on 2 levels.

It won’t break EdgeTX at all. The only thing that would happen is that the RM receiver would be using the same vario sensor ID as the Matek receiver. EdgeTX understands both already, ETHOS only knows the Matek ID.

You’ve already submitted the bug report. You were asking for an interim fix until ETHOS gets updated. Changing the RM sensor ID to match the Matek one is the interim fix. It shouldn’t break anything since you aren’t going to have both active at the same time.

There’s a third aspect, is ELRS so inflexible that it can’t change sensor ID’s as a configuration item? That’s really not a good thing since it doesn’T allow for multiples of the same sensor type (which has been supported in the FrSky ecosystem since S.Port was introduced in 2013).

**Comment by pkendall64** [comment]
So, my stance is it's still an ETHOS issue. The ER8GV has a barometer and we send the values as CRSF packet 9 which has both Altitude and Vertical Speed. 
This EdgeTX code show the parsing of the 0x09 packet.
https://github.com/EdgeTX/edgetx/blob/main/radio/src/telemetry/crossfire.cpp#L146-L163
And this shows the 0x07 packet.
https://github.com/EdgeTX/edgetx/blob/main/radio/src/telemetry/crossfire.cpp#L126-L128

Trying to cajole devs into making changes by saying the system is inflexible is not a way to get things moving.
By saying that ELRS is inflexible because it can't be configured to put the data on a different packet id, cuts both ways.
Is ETHOS so inflexible that it can't configure which packet it gets the data from?

**Comment by miggy1952** [comment]
Thanks for your help, looks like I should buy another Matek for my F5J fun!

I am just the guy in the middle, I believe everyone.

**Comment by miggy1952** [comment]
Looks like you were correct, he now say.
OK, that's a different sort of ID than sensor ID's (which are just bus ID's and should be assignable).

They're talking about data type ID's, which do require an ETHOS update, not a simple ID change.

This is mostly a misunderstanding, sensor ID seems to mean 2 different things in the two systems.
