### ISSUE TITLE
Mavlink awareness and injection

### ISSUE THREAD

**Issue by truglodite** [ExpressLRS/ExpressLRS#2375]
### Discussed in https://github.com/ExpressLRS/ExpressLRS/discussions/2374

<div type='discussions-op-text'>

<sup>Originally posted by **truglodite** August 21, 2023</sup>
Now that airport is working, it would be the cherry on top if elrs in airport mode could inject RSSI, LQI, etc into the mavlink stream. I mentioned this in the ardupilot forum, and of course there's not much they can do to help. I understand elrs devs are very busy with other priorities at the moment. I figured I'd submit this FR anyways, since there will likely be more requests as more users start to play with airport.

I'm lost when it comes to elrs code, but let me know if there's any testing I can help out with on this.</div>

**Comment by pkendall64** [comment]
Closing as there is an ongoing development where you can become involved in the #mavlink-rc discussion in the ELRS discord.
