### ISSUE TITLE
Unable to exit airport mode

### ISSUE THREAD

**Issue by MNS26** [ExpressLRS/ExpressLRS#2434]
## Current Behavior
when you enter airport mode there is no way to get out of it

## Steps to Reproduce

1. access web UI

2. setup airport

3. reboot

4. wait...

## Possible Solution (Not obligatory)
replace line 656 in `tx_main.cpp`
```c
webserverPreventAutoStart = true;
```
with a check for connection before forcing wifi mode off

## Details

this is only a issue with the TX modules

## Your Environment

- TX hardware: HM ex900TX in airport & boxer (RM TX16S insternal) 
- RX hardware: HM es900RX in airport & RP2
- Handset model: ---
- OpenTX version (including nightly number): ---
- ExpressLRS version (TX & RX MUST MATCH): ---
- Packet Rate: ---
- Telemetry Ratio: ---
- user_defines: ---

note: fields with `---` dont matter for this issue (since its airport wifi mode related)

**Comment by wvarty** [comment]
Working as expected.
If you enable airport, reboot, and wait, then there is no expectation that wifi will activate after a timeout. That would then prevent serial comms, which could happen at any time.
If you are trying to get out of airport on a tx module, you can either:
1. Plug it into a handset, and use the LUA to trigger wifi mode
2. If the tx has an OLED, navigate to wifi and trigger it there
3. If the tx has user buttons (like the ranger, super G, etc.) assign wifi to a long press, and press it.
Or if you're really stuck:
4. Reflash firmware with the "erase" option selected.
