### ISSUE TITLE
No SBUS output on lite receivers

### ISSUE THREAD

**Issue by vespassassina** [ExpressLRS/ExpressLRS#2439]
## Current Behavior

Lite receivers are not capable of sbus output

## Steps to Reproduce

Get a lite receiver (tested on both cyclone and betafpv lite receivers, same behaviour)
Install ELRS 3.3, configure passkey
Configure receiver to output SBUS

test with FC > no output
test with tester (Toolkitrc M7) > no output

## Details
same process enables sbus perfectly on both a BetaFPV Nano receiver and a Matek R24 pwm receiver
tried reflashing with ftdi: same behaviour
tried removing the pullup resistor on the lite receiver: same behaviour

need SBUS out for a very small proprietary FC, lite receiver was ideal for the extremely light weight

no

windows, elrs 3.3, elrs configurator 1.6

- TX hardware:
Radiomaster TX16 MK2 onboard TX, 2.4ghz ELRS

- RX hardware:
betafpv 2.4 lite receiver (flat antenna v2)
cyclonefov 2.4 lite receiver (tower antenna)

- Handset model:
radiomaster tx16s MK2

- OpenTX version (including nightly number)
edgetx 2.9 official

- ExpressLRS version (TX & RX MUST MATCH):
3.3

- Packet Rate:
333

- Telemetry Ratio:
- user_defines:

**Comment by pkendall64** [comment]
Closing as this is not an issue with ELRS. It seems to be an issue with the FC and the ToolkitRC M7
