### ISSUE TITLE
ExpressElrs 3.3.0 does not work with betaflight version 4.2.X

### ISSUE THREAD

**Issue by Gabyguay69FPV** [ExpressLRS/ExpressLRS#2461]
## Current Behavior

 ExpressElrs 3.3.0 does not work with betaflight version 4.2.X betaflight

## Steps to Reproduce

1. I have updated the tx and rx module to version 3.3.0 but the channel bars do not move in betaflight

2.

3.

4.

## Your Environment

Testing

- TX hardware: R9
- RX hardware:R9 mm
- Handset model:
- OpenTX version (including nightly number)
- ExpressLRS version (TX & RX MUST MATCH): yes 3.3.0
- Packet Rate:
- Telemetry Ratio:
- user_defines:

**Comment by pkendall64** [comment]
Please seek help on discord. Many users have ELRS3.3 working with Betaflight 4.2.
