### ISSUE TITLE
JHEF7DUAL board telemetry issues with betaflight 4.2.9 and ELRS 3.3 0

### ISSUE THREAD

**Issue by Gabyguay69FPV** [ExpressLRS/ExpressLRS#2465]
## Current Behavior

After updating the ELRS version to 3.3.0, several telemetry sensors have stopped working. JHEF7DUAL flight controller betaflight 4.2.9

## Steps to Reproduce

1.

2.

3.

4.

## Possible Solution (Not obligatory)
Return to version of ELRS 2.5.1 and betaflight 4.1.7-

With other controllers such as kakute and IFlight succex-e there have been no problems

## Your Environment

At home

flight controller JHEF7DUAL with betaflight 4.2.9
- TX hardware: R9mm(elrs)
- RX hardware:R9
- Handset model:
- OpenTX version (including nightly number)
- ExpressLRS version (TX & RX MUST MATCH): 3.3.0
- Packet Rate:
- Telemetry Ratio:does not apears all the elements
- user_defines:

**Comment by pkendall64** [comment]
Closing as this is old and should really be asked on discord if the issue persists
