### ISSUE TITLE
hehe, bricked my betafpv aio rx with repartitioner (wasn't updating to the latest firmware and didn't read it was only for transmitters)

### ISSUE THREAD

**Issue by xgg69** [ExpressLRS/ExpressLRS#2508]
so i bricked the receiver, tried updating thru betaflight and that didn't work, today found the elrs rx uart pads on the aio board and tried to update with an ftdi chip, that also doesn't seem to work... soo what can i do now?

fc/aio: betafpv 5a 1s aio with elrs uart receiver

i bought a new board for my meteor, but want to recover this one for some random projects

**Comment by schugabe** [comment]
Please join our discord for help during unbricking: https://discord.gg/expresslrs
