### ISSUE TITLE
RX wifi update issue

### ISSUE THREAD

**Issue by JarrodB92** [ExpressLRS/ExpressLRS#2512]
## Current Behavior
With both Radiomaster RP1 and Happymodel EP1 RX led is now dim after wifi update to 3.3.1  I built the update and flashed via wifi. Both receivers did not reboot after flashing and led stayed dim despite getting update succeeded message. Now both receivers do not fully light up and do not connect at all to the TX.

## Steps to Reproduce

1. build RX update for wifi

2.Flash via wifi

3.

4.

## Your Environment

- TX hardware: RadioMaster Ranger
- RX hardware:Happymodel EP1 & Radiomaster RP1
- Handset model:RadioMaster TX16s
- OpenTX version (including nightly number)
- ExpressLRS version (TX & RX MUST MATCH): 3.3.1
- Packet Rate:
- Telemetry Ratio:
- user_defines:

**Comment by pkendall64** [comment]
Please as on discord in the #help-and-support channel and I'm sure the friendly folk there will help you out.

**Comment by JarrodB92** [comment]
Hi Paul, I was able to solder the boot pads and perform a betaflight
passthrough and successfully update them. I’ve just never seen the issue
that I posted happen.

**Comment by pkendall64** [comment]
This issue happens every now and then when the receiver is re-powered before the LED has resumed normal blinking pattern after a flash.
