### ISSUE TITLE
MSP_SET_RX_CONFIG targeted to the Receiver is sent to the FC

### ISSUE THREAD

**Issue by rotorflight** [ExpressLRS/ExpressLRS#2549]
## Current Behavior

The FC (Rotorflight) sometimes receives an MSP command (MSP_SET_RX_CONFIG) which is not coming from the LUA scripts (or any other configuration software). This MSP command is corrupting the FC config.

## Steps to Reproduce

Change model match configuration. Either enable/disable it or change model id.

## Possible Solution (Not obligatory)

Don't send this MSP command to the FC.

## Details

It appears the received MSP is not in the format expected by Rotorflight (or Betaflight).
The payload is only two bytes. 10 and another number. Looks like ELRS Tx is sending 
this for updating the model id with model match. The Rx seems to have code to use
this information.

It appears it is not intended for the FC at all.

## Your Environment

This has happened to many people with different setups.
ELRS 3.3.x and Rotorflight-20240105.

**Comment by pkendall64** [comment]
Can you test with the PR that was created for this. You will need to flash the TX module as the packet now has the destination set to the receiver now.
