### ISSUE TITLE
TX12 elrs and ep1 bind problem if I turn on the receiver first

### ISSUE THREAD

**Issue by capblack** [ExpressLRS/ExpressLRS#2581]
Hello, I have a TX12 elrs with several EP1 receivers and version 3.30. If I turn on the receiver first, the link is not established. I think this is a problem if I am flying and the connection is interrupted. Is this on purpose or is it a bug?
thank you so much

## Your Environment

- TX hardware:
- RX hardware:
- Handset model:
- OpenTX version (including nightly number)
- ExpressLRS version (TX & RX MUST MATCH):
- Packet Rate:
- Telemetry Ratio:
- user_defines:

**Comment by pkendall64** [comment]
Please ask on discord in the #help-and-support channel.
I have confirmed than power on a receiver first, then powering the radio a connection is made.
The only place this could be a problem is if you have left the receiver for long enough that it goes into wifi mode.
