### ISSUE TITLE
EdgeTX fonts mismatch in lua script backpack options

### ISSUE THREAD

**Issue by sanj3k** [ExpressLRS/ExpressLRS#2599]
When selecting AUX channel for DVR start I can't see the arrows after the AUX channels but some weird symbols. 

## Steps to Reproduce

Open 3.3.2 Lua script on a monochrome bw display controller and inside backpack options sweep through the options

https://streamable.com/16ql93

## Possible Solution (Not obligatory)

In the discord it was said there is a hardcoded approach to pull the symbols means someone needs to have a look and rearrange

## Details

It should be only a cosmetic problem but not hurt functionality will try it out later today

## Your Environment

- TX hardware: Radiomaster Ranger Nano 2.4G
- RX hardware: not relevant
- Handset model: Frsky X-Lite 2018
- EdgeTX version 2.9.4 2024-02-12
- ExpressLRS version (TX & RX MUST MATCH): 3.3.2

**Comment by pkendall64** [comment]
Works with the latest version of the Lua script on Radiomaster Zorro.
Download from https://raw.githubusercontent.com/ExpressLRS/ExpressLRS/master/src/lua/elrsV3.lua
Can you test and report back.
