### ISSUE TITLE
3.3.2: TLM Lost - TLM Recovered endless loop

### ISSUE THREAD

**Issue by xQeptr** [ExpressLRS/ExpressLRS#2608]
## Current Behavior

Hi folks, after long time not flying, I updated my BETAFPV Micro TX (1W) to 3.3.2 .. not sure which version was flashed before..
I also updated my BETAFPV Nano RX to the same version.
Got this issue as well with SuperD RX. 

I checked old posts and played around with several values, like Baudrate etc. But its still flapping.

Domain: ISM

- TX hardware: BETAFPV Micro TX (1W) 
- RX hardware: BETAFPV SuperD RX 
- Handset model: Flysky Nirvana
- OpenTX version (including nightly number): v2.9.4
- ExpressLRS version (TX & RX MUST MATCH): 3.3.2
- Packet Rate: 250Hz, 333HZ Full, 500Hz, ...
- Telemetry Ratio: std, 1:2, 1:4, ...
- user_defines: -

![image](https://github.com/ExpressLRS/ExpressLRS/assets/35378517/79c5e4ec-2e2b-4abe-8de1-81ad9de921a5)

**Comment by mha1** [comment]
what's your baud rate set to on the handset?
