### ISSUE TITLE
Screen flashes unexpectedly when running elrsV3 Lua script

### ISSUE THREAD

**Issue by RC-SOAR** [ExpressLRS/ExpressLRS#2669]
## Current Behavior

When running elrsV3 script on my TX16S under OpenTX 2.3.15, the screen flashes rapidly after each click or scroll increment, which is distracting.  Video here:

https://youtu.be/WO_e5PuhHwU?si=PkAvhA9-y2YpKBXa

The actual link with the rx works fine.

Is there a Lua fix for this?

(I notice that the "configure Crossfire" script in the Tools menu provides similar functionality and doesn't suffer from the flashing issue.)

## Steps to Reproduce

1. Go to OpenTX Tools menu
2. Run ELRSv3 script

## Your Environment

RM TX16S
OpenTX 2.3.15
Ranger Micro external ELRS 3.3.0

**Comment by pkendall64** [comment]
This looks like an openTX bug as this does not happen on EdgeTX with the same Lua script.

**Comment by RC-SOAR** [comment]
Further data point... version 3.2 works fine (after selecting '3.2' release in the configurator and downloading the script). So an incompatibility has crept in with 3.3 script. 
It would be great if this were investigated as there are still many OTX users out there.

**Comment by aerostarlegacy** [comment]
Hello! This is effecting me as well.

**Comment by JyeSmith** [comment]
OTX is no longer maintained or supported.  The fix here is to update to EdgeTX.

**Comment by RC-SOAR** [comment]
Confused, as ELRS apparently supports OpenTX 2.2.12 or newer as in:
https://www.expresslrs.org/quick-start/transmitters/tx-prep/#internal-expresslrs-modules
The closing of this issue appears to contradict this.

In the meantime, I worked around this by using the 3.2 script (as advised on Discord). Seems to work, but I have no idea what's changed.

**Comment by pkendall64** [comment]
The changes from the 3.2 script are basically to add support for Ardupilot and some optimisations to reduce memory usage for memory limited radios, some fixes to better support configuration of PWM receivers and reducing screen update so it loads faster (this was because of change in the EdgeTX graphical library).
So if the older version works for you then just keep using it.

**Comment by RC-SOAR** [comment]
Thanks Paul. Given that there are still lots of OTX users out there it would be great if compatibility were maintained if poss, though I appreciate it's an increased maintenance burden for you guys.

**Comment by aerostarlegacy** [comment]
@RC-SOAR - can you post a link to that 3.2 script here so others might find it?

**Comment by RC-SOAR** [comment]
@aerostarlegacy I downloaded it via the Configurator, after selecting the 3.2 target.

**Comment by CapnBry** [comment]
> Given that there are still lots of OTX users out there it would be great if compatibility were maintained if poss

Why are they still on OTX? EdgeTX is available for all OTX targets. OpenTX is dead and EdgeTX has replaced it.

**Comment by RC-SOAR** [comment]
OTX on a TX16S is **much** more productive when dealing with setups with 60 or so mixers as is not uncommon with sailplane setups like my [F5J template](https://rc-soar.com/edgetx/setups/esoarplus/index.php)

**Comment by mha1** [comment]
What does you mean by productive?

**Comment by RC-SOAR** [comment]
> What do you mean by productive?

The menus in OTX are denser, so less scrolling and swiping, and the mixers menu caters well for complex setups.
The Mixers menu in ETX is especially awkward to manage with large numbers of mixers - the UI is slow and tedious. It's as if ETX was designed primarily for use with FCs. 
All this applies to the colour screen radios only, the non-touch mono screen interface is fine.

**Comment by macgyverek** [comment]
Added fix on my repo for that issue: https://github.com/macgyverek/ExpressLRS-LUA-OpenTx

**Comment by RC-SOAR** [comment]
Thanks for this. Out of interest, can you point to the corrected lines of code?

**Comment by macgyverek** [comment]
Yes, no problem: 
![LUA Fix](https://github.com/user-attachments/assets/2a18d137-a67c-477a-826d-6a86456a8d02)

**Comment by RC-SOAR** [comment]
It would be nice if the fix could be applied to the production version. Any chance?

**Comment by CapnBry** [comment]
> It would be nice if the fix could be applied to the production version. Any chance?

Nope, because making that change absolutely _crushes_ performance on EdgeTX. It redraws the whole screen every update which is crazy slow on EdgeTX to the point it takes 2-3x longer for the list to load.

**Comment by macgyverek** [comment]
But you can use version checker and write if/else for edgetx, opentx. But I know...developers are very stubborns ;)

**Comment by CapnBry** [comment]
> But you can use version checker and write if/else for edgetx, opentx. But I know...developers are very stubborns ;)

There's incredibly low RAM available on many platforms the lua runs on. Having the script try to detect and run two different ways is a waste of resources that it doesn't have. 

Feels more like someone could just update their supported hardware to a version of EdgeTX and resolve this themselves, but users are very stubborns about solving their own problem ;)  And why doesn't the Configurator support Windows Me?! 😆

**Comment by macgyverek** [comment]
EdgeTx it's crappy for user with colour screen without touch screen...like x10s, x12s... It's a very good radio, not "Chinese" Jumper...

More information are showed on screen with OpenTX. 
It's not update decision....if edgetx will make a screen (GUI) like in opentx, I will update today.
