### ISSUE TITLE
[V3.4.0-RC1-3] Wi-Fi turns on with AUTO_WIFI_ON_INTERVAL disabled

### ISSUE THREAD

**Issue by anti-vaxxer** [ExpressLRS/ExpressLRS#2699]
with V3.4.0-RC1-3 Wi-Fi turns on after 60 seconds although AUTO_WIFI_ON_INTERVAL was unchecked when flashing.

I tested on
HappyModel EP Dual 2.4GHz RX
HappyModel ES900 Dual RX

I flashed back to 3.3.2 which restored proper behavior.

**Comment by JyeSmith** [comment]
Confirm, and a Configurator issue has been opened.

**Comment by jurgelenas** [comment]
Fixed in https://github.com/ExpressLRS/ExpressLRS-Configurator/commit/4b22ae8edc69d7829a33d4901c34e88dd39e3259
