### ISSUE TITLE
Add BAYCKRC 2.4GHz 5xPWM RX

### ISSUE THREAD

**Issue by Mkorho** [ExpressLRS/ExpressLRS#2708]
Target for "BAYCHRC 2.4GHz 5xPWM RX".

![S0c5c979d10d7464781272cd0ae5a983b1](https://github.com/ExpressLRS/ExpressLRS/assets/39406583/7694db44-6a36-445c-9d46-51e70ef86160)

**Comment by JyeSmith** [comment]
BAYCKRC are in contact and have chosen not to add a target for this Rx.

**Comment by rngtng** [comment]
I have this device, what target should I select in the Configurator?

**Comment by komodev** [comment]
I have used HappyModel 2.4ghz EPW6 and EPW5 targets on BAYCK RC PWM 5ch and 6ch receivers without problems, same chip on the board I think. Also used that fw on Matek R24-P6 PWM rx/, both work flawless, still fly them regularly.

I suggest you use `"HappyModel EPW5 2.4g PWM RX"` target and you will see, easy life...
Let me know how it goes and if you need any help flashing it, I will follow this thread now.

**Comment by rngtng** [comment]
Thanks @komodev - this worked like a charm!

**Comment by komodev** [comment]
@rngtng You are very welcome my friend, told you it's an easy fix for a lot of PWM's that use same or similar chip, Matek too ;)
Enjoy
