### ISSUE TITLE
after reboot rp1 reciver went into bind mode 

### ISSUE THREAD

**Issue by petterm77** [ExpressLRS/ExpressLRS#2715]
## Current Behavior

after flight i changed battery and the reciver rp1 went into bind mode by it self.
had to go into the reciver via wifi hot spot and put in the bind phrase again to get it to connect to the transmitter

## Steps to Reproduce

1.

2.

3.

4.

## Your Environment

 out in the field flying

- TX hardware:  radiomaster ranger tx
- RX hardware: radiomaster rp1
- Handset model: radiomaster tx-16s mkii
- OpenTX version edgetx 6.10 rc3
- ExpressLRS version (TX & RX MUST MATCH): 3.4 on both
- Packet Rate: 250 hz
- Telemetry Ratio:  std
- user_defines:

**Comment by SunjunKim** [comment]
Can you try update v3.4.1?

**Comment by pkendall64** [comment]
I think this is related to #2751, could you test the PR #2755 and report back in the PR please.
