### ISSUE TITLE
I'd like to add these DIY_900_RX_ESP8285_SX127x firmware to the ExpressLRS Configurator ground station

### ISSUE THREAD

**Issue by YangChen1234** [ExpressLRS/ExpressLRS#2722]
## Current Behavior

There is currently no such DIY_900_RX_ESP8285_SX127x  target 

## Steps to Reproduce

1.
![QQ截图20240521162550](https://github.com/ExpressLRS/ExpressLRS/assets/89179705/1c214a6e-2311-4b76-aa44-318ec5bc3f20)

2.
![QQ截图20240521161332](https://github.com/ExpressLRS/ExpressLRS/assets/89179705/3b21c22c-614a-42db-b4ab-5392f8c127cc)

**Comment by pkendall64** [comment]
Is this a a receiver from a reputable manufacturer you are trying to flash. If it is then there should be a supported target, unless of course this is a receiver from a manufacturer that does not participate in the project.

If it truly is DIY hardware then you can build and flash from VScode with platformIO.
