### ISSUE TITLE
[3.4.0, 3.4.1, 3.4.2, 3.4.3] Wifi not work at (older) HM ep1

### ISSUE THREAD

**Issue by 3DRacer** [ExpressLRS/ExpressLRS#2733]
in 3.3.2 and earlier, wifi starts at my older HM ep1 (with yellow LED) by switching it on by LUA or wait for the 60s timeout without connection to transmitter.

it does not after flashing 3.4.0 or 3.4.1, 3.4.2 or 3.4.3. It blinking fast for about 1 sec, than it restarts.

## Your Environment

- TX hardware: HM ES24pro
- RX hardware: HM ep1
- Handset model: TX16s
- OpenTX version (including nightly number)
- EdgeTX version (TX & RX MUST MATCH): 2.11.0
- Packet Rate: 500
- Telemetry Ratio:
- user_defines:

**Comment by 3DRacer** [comment]
now I tested with newer HM ep1 with green LED and TCXO and wifi works as aspected. The problem only exists with my older HM ep1.

**Comment by pkendall64** [comment]
You might want to try reflashing and select the erase flash option then flash again. This has been known to help in the past.

**Comment by 3DRacer** [comment]
> You might want to try reflashing and select the erase flash option then flash again. This has been known to help in the past.

Unfortunately, that hasn't changed anything. I'll stay on 3.3.2 with these receivers for now.

**Comment by pkendall64** [comment]
I would say that only thing that we've done that could affect the older HM EP1 (with the underspec'd regulator) is that we increased the RF power of the wifi section for better connection stability and it could be too high for these old devices.

**Comment by 3DRacer** [comment]
hello Paul.
Thanks for pointing me in this direction. But in http://elrs_rx.local/hardware.html I don't see any difference between 3.4.2 and 3.3.2. Both have a power value of 13. My idea of ​​reducing this value on a new ep1, reading it out and playing it into my older ep1 won't work. Could you make me a 3.4.2 with the previous rf power? Unfortunately I still have more than 10 older ep1s in my copters.  I've never had any problems with too weak wifi so far.

BR

**Comment by pkendall64** [comment]
No, the wifi power not the radio power. This is hard-coded.
https://github.com/ExpressLRS/ExpressLRS/blob/master/src/lib/WIFI/devWIFI.cpp#L1163 and
https://github.com/ExpressLRS/ExpressLRS/blob/master/src/lib/WIFI/devWIFI.cpp#L1184

**Comment by 3DRacer** [comment]
That will be it. It remains to be considered whether more stable WiFi (?) or compatibility is more important. So the older HM ep1 and ep2 will remain on V3.3.2. Perhaps the release page should be corrected under "Who should NOT update from V3.3?".

**Comment by TommyV6** [comment]
I got almost 8 old EP1. Is it time to throw them all away?

**Comment by 3DRacer** [comment]
Just as a suggestion. A new device "HM ep1/ep2 first series". With reduced Wifi range. As I already wrote. Wifi has never been a problem. I use a small wifi repeater at my desk.

**Comment by TommyV6** [comment]
In my case, the range of the EP1 was okay; nothing better is needed for programming. But now, none of my EP1s ever start the WiFi. After 60 seconds, they reset and enter BIND mode. I have to desolder them and program them via UART. It's too much trouble for me.

**Comment by DNAcz** [comment]
I confirm the same symptoms with wifi at EP1/EP2. I have never had a problem with wifi range. I stay on 3.3.2. It is possible that not only EP is affected but also other Rx. Returning to the previous settings would solve this problem.

**Comment by TommyV6** [comment]
This solution is working for my I added 100uf 6.3V electrolytic capacitor and I`t working. I`s there any way to fix this without this modification ?

**Comment by 3DRacer** [comment]
> This solution is working for my I added 100uf 6.3V electrolytic capacitor and I`t working. I`s there any way to fix this without this modification ?

I did it like pkendall64 described. The wifi transmission power reduced to the old value “13”. Attached is my customized devWIFI.ccp from V3.4.3. You have to remove the .gif extension
![devWIFI cpp](https://github.com/ExpressLRS/ExpressLRS/assets/42546574/b58acb7b-15ed-4f5e-99b1-1d8776ff7eee)

**Comment by TommyV6** [comment]
This fix will be in next release ?
