### ISSUE TITLE
Receiver change output format

### ISSUE THREAD

**Issue by chphoto80** [ExpressLRS/ExpressLRS#2748]
## Current Behavior

Yesterday, I set my Adiomaster RP1 to SBUS output format. Everything OK, my MSH Brain unit recognize input signal. Today, I power on radio and heli, but Brain not recognize input signal. I connect to EP1 by WiFi and check output protokol. Protocol was set to CRSF. I set SBUS and Brain recognize signal. I dont know, why protocol was changed (not by my).

## Steps to Reproduce

1.

2.

3.

4.

## Your Environment

- TX hardware: Happymodel ES24 TX Slim Pro
- RX hardware: Radiomaster RP1
- Handset model: FrSky X20 Pro, ETHOS
- OpenTX version (including nightly number) ----- ETHOS
- ExpressLRS version (TX & RX MUST MATCH): 3.4.1 - both Rx Tx
- Packet Rate:
- Telemetry Ratio:
- user_defines:

**Comment by pkendall64** [comment]
I think this is also related to #2751 and a potential fix is in #2755. If you could test and comment on #2755 that would help.
