### ISSUE TITLE
BR1/BR3 WiFi not work on 3.4.2

### ISSUE THREAD

**Issue by zyren** [ExpressLRS/ExpressLRS#2757]
We have tested all transmitters and receivers with firmware version 3.4.2, and the conclusions are as follows:

All 2.4GHz TX: WiFi works normally.

All 2.4GHz RX: WiFi works normally.

All 900MHz TX: WiFi works normally.

All 900MHz RX (BR1/BR3): WiFi does not work. Despite attempting to activate WiFi in various ways (via Lua, holding a button for 5 seconds, waiting for 60 seconds), the receiver's light flashes rapidly indicating WiFi mode is correctly activated, but the SSID: ExpressLRS RX cannot be found.

**Comment by pkendall64** [comment]
Tested on BR1 and BR3 here and they both work fine. Perhaps try eraseing before flashing.

**Comment by pkendall64** [comment]
More information was added to #2760
