### ISSUE TITLE
Mavlink-rc branch jumper t20v2

### ISSUE THREAD

**Issue by pepelillo** [ExpressLRS/ExpressLRS#2758]
Hello. Newbee in elrs world, very interested in using mavlink within elrs, and want to test this branch, but scared if someting goes wrong and brick (or someting similar) my brand new t20. Is there a safe way to test the branch and go back to the main branch?.

Any guide to test this mavlink branch? Is It necessary to flash the Rx also?

Thanks

**Comment by pkendall64** [comment]
It would be best to join discord and ask questions in the #mavlink-rc channel for this.
