### ISSUE TITLE
Flysky TX Modules Support

### ISSUE THREAD

**Issue by richardclli** [ExpressLRS/ExpressLRS#2778]
The following Flysky TX modules will be supported:

1. IRM301 The internal module of Flysky EL18 radio
2. FRM303 The external module by Flysky

Will work with Flysky to develop a port of ELRS firmware which is compatible with their stock TX bootloader, so that they can provide a tool to flash their TX modules to ELRS firmware, or flash back to their stock AFHDS3 firmware.

**Comment by JyeSmith** [comment]
@richardclli please use our current discord group chat to discuss.  As you are aware ELRS is not looking to add or support new STM hardware.  STM support will be removed in the future.

**Comment by pfeerick** [comment]
Thanks for putting this up Richard. It will be good to see the internal RF on the EL18 having an ELRS option, as well being able to use the higher power FRM303 module for that also.

**Comment by richardclli** [comment]
> @richardclli please use our current discord group chat to discuss. As you are aware ELRS is not looking to add or support new STM hardware. STM support will be removed in the future.

Yes, understood, however we can still have some fun in the meantime ^.^

**Comment by richardclli** [comment]
It is done, check it out int he following link:

https://github.com/richardclli/Flysky-ELRS
