### ISSUE TITLE
Reminder to add BLE Joystick shortcut on the customizable buttons on the Ranger, Bandit etc.

### ISSUE THREAD

**Issue by NorgeSquad** [ExpressLRS/ExpressLRS#2796]
^

**Comment by JyeSmith** [comment]
@NorgeSquad can you please test this PR https://github.com/ExpressLRS/ExpressLRS/pull/2842

**Comment by NorgeSquad** [comment]
Hi! Yes sure! Im not that good technical. so where can I find the 
download? :)

**Comment by mha1** [comment]
It got merged into master. Just use the Configurator with tab GIT BRANCH selected to build branch master. If you don't see the tab GIT BRANCH go to Settings and check Expert Mode.

**Comment by NorgeSquad** [comment]
Allrighty. Got it! But whats the branch called in the Git branch?

**Comment by mha1** [comment]
master

**Comment by NorgeSquad** [comment]
Okay nice! My bagagde got lost at the airport with my Radio and module. 
But when I get it I will let you know. But Seems like it worked great!

**Comment by NorgeSquad** [comment]
Tested it now! Worked great! Would you guys recommend me to stay in the 
Master Git branch. Or should I flash back to Newest official Firmware?

**Comment by mha1** [comment]
I'd stay on the latest official firmware and wait fir 3.5 to be released

**Comment by NorgeSquad** [comment]
Oh Alright! I assume 3.5 is Around the corner

**Comment by NorgeSquad** [comment]
I found out that the BLE joystick Timeout every 20th minute. is there 
any way around this?

**Comment by JyeSmith** [comment]
Fix here https://github.com/ExpressLRS/ExpressLRS/pull/2944
