### ISSUE TITLE
v3.4.0+ ESP8285 brownout when starting WIFI or when flashing thru WIFI

### ISSUE THREAD

**Issue by Mkorho** [ExpressLRS/ExpressLRS#2819]
#2568 Increase the wifi power output on the ESP8285 devices from 13dBm to 20.5dBm.

Started updating my Happymodel EP1/2 to v3.4.3 from v3.3.X when I realized that after updating them, none of them could connect to WIFI anymore.

Tested 7x EP1 and 2x EP2 and they all stopped working.
Flashed them back to v3.3.0 and WIFI started to work again.

I downloaded v3.4.3 source code and changed the WIFI power level back to 13dBm and all the receivers started to work again.

I have 15x BAYCKRC 5xPWM receivers that started to corrupt firmware when flashing thru WIFI.
They connect to WIFI normally but after firmware upload they randomly fail to properly flash and this started with the WIFI power level change.
I think that there are brownouts when writing the flash memory while the WIFI is on.

All of my receivers work perfectly on older than v3.4.0 firmware.

**Comment by pkendall64** [comment]
If wifi power was to be added it would be to the hardware.json file, not the Lua.

**Comment by pitts-mo** [comment]
I have noticed this same behavior with my early HappyModel EP1 and EP2 receivers.
 
Adding a WiFi power setting or alternate RX WiFi low power mode to the LUA seems like the most user friendly solution... This way all the RX can be flashed and bound with a generic cloud build and the user would need to change WiFi power only for the affected RX.

I guess the easiest might be to add a low power WiFi flag at build time.



Side note: Recent builds of Formation Flight also experience related issues with early EP1 and EP2 RX:
FormationFlight/FormationFlight#54
:-/

**Comment by pitts-mo** [comment]
Would it work to add two or more WiFiPowerLevels (default high) in unified RX target and devWIFI.cpp? 

Then add a strWiFiPowerLevels segment in /src/lib/LUA/rx_devLUA.cpp to switch it from lua similar to strPowerLevels?

**Comment by pkendall64** [comment]
Lua is the wrong place to store this. Since it is related to under-spec'd component usage it should live in the hardware settings. This way we can override the default for these under-spec'd targets.
