### ISSUE TITLE
Problem failsafe mode gemini 

### ISSUE THREAD

**Issue by Mick51** [ExpressLRS/ExpressLRS#2881]
## Current Behavior

When a failsafe occurs, the link does not come back even next to the radio

## Steps to Reproduce

Radio jumper t20 gemini, rx dual TCXO happymodel mode gemini

1. Put this in failsafe 

2. Once the rx is in radio range, the link is not made there is no way to recover the link.

3. Cut the rx to turn it on again, the link comes back. 

## Possible Solution (Not obligatory)

It would be nice if the link could be made again once in range of the recovered radio. Normally the link is supposed to come back, but this is absolutely not the case in rx dual TCXO happymodel in gemini mode.

- TX hardware: jumper t20 gemini in gemini mode 
- RX hardware: happymodel dual TCXO 2,4ghz gemini mode
- Handset model: internal tx mode gemini
- OpenTX version (including nightly number) : v2.10.2
- ExpressLRS version (TX & RX MUST MATCH): v3.4.3
- Packet Rate: 150hz
- Telemetry Ratio: std 1:32
- user_defines:

**Comment by JyeSmith** [comment]
I have just tried this hardware on both 3.4.3 and the current development build master (v3.5 soon).

The below image show the link stats on connection.  And here is a demo video of the Rx gaining connection again after FS (good ol microware test) https://streamable.com/8suk0m
![image](https://github.com/user-attachments/assets/57941119-b94e-415d-8eda-6ce690d03281)

A couple of things you can try/test.

Try an Erase when flashing the Rx just in case you have a bad build.
![image](https://github.com/user-attachments/assets/0b49d4b5-7956-40ad-862b-db3a55bca4cb)

Are you also using Lock On Connection?  This will prevent the Rx from rate cycling on FS and hunting for a connection on a different RF mode.
![image](https://github.com/user-attachments/assets/6743cdcb-8ede-4858-8fd1-ea2020bf23b0)

Finally you could try downloading the binaries from the tx and rx and sharing them with me here or on discord.  Ill flash them and check for connection issues.
![image](https://github.com/user-attachments/assets/3e033288-7c8e-44d8-8bf3-520b2017f871)
