### ISSUE TITLE
Radiomaster RP4TD receiver missing WIFI connectivitity menu in fw 3.4.3 ?

### ISSUE THREAD

**Issue by sisari** [ExpressLRS/ExpressLRS#2888]
- TX hardware:  Radiomaster Nano TX module
- RX hardware: Radiomaster RP4TD diversity receiver
- Handset model: Jumper T-Lite v2
- OpenTX version : latest Edge TX
- ExpressLRS version (TX & RX MUST MATCH): 3.4.3
- Packet Rate:150Hz
- Telemetry Ratio: 1:32
- user_defines:

**Comment by pkendall64** [comment]
Maybe you could give a bit more detail about where you think this wifi menu should be! Perhaps a picture might be helpful.

**Comment by sisari** [comment]
closing issue - menu found but not in receiver's menu is in TX module menu ....
