### ISSUE TITLE
Wifi is enabled after 60 seconds despite unchecking auto_wifi_on_interval

### ISSUE THREAD

**Issue by LeasyBen** [ExpressLRS/ExpressLRS#2892]
Flashing the Happymodel EP1 through BFpassthrough, despite unselecting the auto_wifi_on_inverval definition the wifi comes on after 60s making it impossible to connect to the transmitter without a power cycle. Trying to flash 3.4.3.

Also, for some reason the flash fails when "erase before flash" is selected but unchecking that seems to be fine.

**Comment by pkendall64** [comment]
Unchecking wifi on interval does NOT mean that it's disabled, it means it uses the default.

**Comment by LeasyBen** [comment]
> Unchecking wifi on interval does NOT mean that it's disabled, it means it uses the default.

On previous versions, unchecking this box seemed to disable wifi. What can I set the value to now in order to effectively disable this feature?

**Comment by gsezz** [comment]
You can set the interval to a very high timespan. Like 2147483647 seconds, which is about 70 years.

But it would be nice if there was an more intuitive option to completely disable Wi-Fi mode and keep the Rx available for TX Connections.

**Comment by pkendall64** [comment]
There is, it's a bug which has a fix ready for the 3.5 release.
You should be able to turn the checkbox off and it should disable the wifi auto-on completely.

**Comment by anti-vaxxer** [comment]
duplicate of #2699
