### ISSUE TITLE
cant compile FW 3.4.3 for Radiomaster RP4TD receiver  - server error

### ISSUE THREAD

**Issue by sisari** [ExpressLRS/ExpressLRS#2904]
- Operating System and version:
- TX hardware:  Betafpv SuperG 2.4G
- RX hardware:  RP4TD receiver

**Comment by pkendall64** [comment]
Are you sure the receiver is an RP4TD that you are flashing? Because the RP4 is an ESP32 and has plenty of flash space and loads the new firmware into a seperate partition which will always have enough space!
