### ISSUE TITLE
[V3.5.0-RC1] Wrong name/image on screen in wifi admin section

### ISSUE THREAD

**Issue by RobertoD91** [ExpressLRS/ExpressLRS#2915]
## Current Behavior

On a tx module with screen, in the wifi admin, the names are incorrect, see the videos:

Wrong on 3.5.0-rc1:
https://github.com/user-attachments/assets/bebe66a6-2ae7-4bb9-aca6-7976d0040b1a

Correct on 3.4.3:
https://github.com/user-attachments/assets/bbeff174-8e10-4b9c-8a26-d347a0ddfac2

## Steps to Reproduce

1) Power up, press the 5d button on the module and go to the wifi admin section

## Your Environment

- TX hardware: BetaFPV Micro RF Module
- RX hardware: n.a.
- Handset model: n.a.
- OpenTX version: n.a
- ExpressLRS version: V3.5.0-RC1
- Packet Rate: n.a.
- Telemetry Ratio: n.a.
- user_defines: none

**Comment by pkendall64** [comment]
@RobertoD91 Thanks for this bug report.
