### ISSUE TITLE
[V3.5.0-RC2] Failsafe issue

### ISSUE THREAD

**Issue by 0crap** [ExpressLRS/ExpressLRS#2923]
## Current Behavior

After installing 3.5.0-RC2 I had a failsafe happening

## Steps to Reproduce

Flash both TX and RX to 3.5.0-RC2 and go fly.

## Possible Solution (Not obligatory)

v3.4.3 seems to solve the issue

## Details

I did two flights with my Dolphin on RC2, first flight had a failsafe, second flight went normally.
https://youtu.be/xOGtjDmgGMQ
![Failsafe](https://github.com/user-attachments/assets/f46784ea-a11a-4af0-817c-e4297871bcf9)

I also flashed my quad with RC2 which gave multiple "Telemetry lost" messages, but the link did not failsafe.
The quad uses a HM EP1. (Flashed with "betaflight passthrough" option.)
I was able to flash the TX and quad (HM EP1 - not dual) back to v3.4.3 which solved the issue.
(Quad uses 250Hz LoRa Std 1:64 setting.)
Dolphin is flashed back to v3.4.3 as well but no time to fly it again atm.

The quad as well as the plane have had many glitch free flights on v3.4.3

## Your Environment

- TX hardware: DIY2400 E28 ISM2G4
- RX hardware: HM EP1 Dual TCXO
- Handset model: Taranis QX7S with TBS inverter hardware mod (1.87MBps)
- OpenTX version (including nightly number): 2.3.15
- ExpressLRS version (TX & RX MUST MATCH): 3.5.0-RC2
- Packet Rate: 150Hz LoRa
- Telemetry Ratio: Std (1:32)
- user_defines:

**Comment by 0crap** [comment]
For the record, I was able to sqeeze in two flights with the Dolphin plane this morning, TX and RX on v3.4.3.
No issues.

**Comment by 0crap** [comment]
![OTX-log](https://github.com/user-attachments/assets/c1c59f2f-b31c-432b-8d52-b00c71ce4b60)

Here we have a part of the OpenTX logging on my handset at the moment of the failsafe.
(RTC of my handset was behind around 7 minutes, so forget the time stamps.)
Usually i receive one logline roughly every second, at the moment of the failsafe there is a gap of around 10 seconds.
So I guess the OTX logfile is of little help here...

**Comment by pkendall64** [comment]
That sounds like a reboot of either the TX module or the RX.

**Comment by 0crap** [comment]
Is there any way I as a user could have noticed which one rebooted? (If that happened.)

**Comment by pkendall64** [comment]
If you have OSD data as well you should be able to tie it up.
If the RX rebooted then you should see in the OSD that the LQ immediately goes to zero. If the TX rebooted then the LQ on the OSD would drop rapidly to zero but you will see the values as it drops.

**Comment by 0crap** [comment]
OK, well, I have nothing more besides the OSD data I used to render the YT video linked above.

**Comment by 0crap** [comment]
Yep, already done. :-)

**Comment by JyeSmith** [comment]
Have you been able to bench test and reproduce?

**Comment by 0crap** [comment]
Sorry, not yet.
I'm away from my gear until after the weekend.
I'll report back next week.

**Comment by 0crap** [comment]
I tested this a bunch of times on the bench.
Connect/disconnect a RX with some time in between to see if it disconnects.
I was not able to reproduce it.

If other users read this and had a failsafe, please add your findings to this issue.
Otherwise I'm probably alone here and we can only close this issue and see how it goes....

**Comment by JyeSmith** [comment]
We'll leave it open for a bit since RC2 will become the final release.  So we might suddenly get a whole lot of more users and some further info.
