### ISSUE TITLE
RCVR_UART_BAUD no effect in 3.5.0 and 3.5.1

### ISSUE THREAD

**Issue by Duese123** [ExpressLRS/ExpressLRS#2992]
## Current Behavior

RCVR_UART_BAUD is not overtaken the baudrate on UART

## Steps to Reproduce

Flash for FrSky R9 MM Mini newest SW 3.5.0 or 3.5.1 and change RCVR_UART_BAUD to 115200. Express Konfigurator 1.7.6 used

## Possible Solution (Not obligatory)

Flash back to older versions eg 3.4.1

## Details

Receiver is still sending in default baudrate 420000 (checked with logic analyzer). Changes have no effect. Flash to 3.4.1 eg TX is sending correctly with compiled firmware and set the variable baud RCVR_UART_BAUD  to 115200... flash back to newer version UART is again set to 420000 no matter what you will setup in the tool
![image](https://github.com/user-attachments/assets/7804564b-da4f-4475-9e88-a2078cdb4004)
![image](https://github.com/user-attachments/assets/46f9d0fb-e9e5-4fad-8c81-593c4bfb906b)

## Your Environment

- TX hardware: FrSky R9 MM Mini
- RX hardware: not relevant
- Handset model:not relevant
- OpenTX version (including nightly number) not relevant
- ExpressLRS version (TX & RX MUST MATCH): not relevant
- Packet Rate: not relevant
- Telemetry Ratio: not relevant
- user_defines: not relevant

**Comment by JyeSmith** [comment]
@Duese123 can you please test this PR https://github.com/ExpressLRS/ExpressLRS/pull/2997

**Comment by Duese123** [comment]
I was trying with new Branch "3.x.x-maintenance"
With Konfigurator but still not working
