### ISSUE TITLE
(native) Dynamic Power

### ISSUE THREAD

**Issue by greenbigfrog** [ExpressLRS/ExpressLRS#305]
Would reduce power consumption as well as reduce contribution to RF noise floor.

("requested" by Fernandez#5615)

( #124 is not really related to this)

**Comment by JyeSmith** [comment]
How would we like to do this?  Based on rssidbm might be good since we already have rf mode sensitivity hard coded.

If with 20dbm of the sensitivity increase the output power?  Plus add some hysteresis control.

https://github.com/AlessandroAU/ExpressLRS/blob/f9c54b0fbbf71d677083d490da60516bc28e4a08/src/src/common.cpp#L18

**Comment by greenbigfrog** [comment]
> If with 20dbm of the sensitivity increase the output power?
Linearly?

**Comment by JyeSmith** [comment]
Power output would just be bumped up to the next level. https://github.com/AlessandroAU/ExpressLRS/blob/f9c54b0fbbf71d677083d490da60516bc28e4a08/src/lib/POWERMGNT/POWERMGNT.h#L59

e.g. for 200Hz mode, if you drop below -92 then increase power.  If you go above -82 then decrease power.

**Comment by evildronepilot** [comment]
Is it possible to implement the behaviour similar to CSRF?
First add new option in lua script called dinamic power as a tick box.

IF ticked TX transmission power will start at minimum and progress (Base on lq, linearly or in steps) but only up to the preset power value?

**Comment by SunjunKim** [comment]
This implementation, by James, looks promising.

**Comment by SunjunKim** [comment]
I've implemented an elementary dynamic power function on top of the RC9 release.  Please try if you want:
https://github.com/SunjunKim/ExpressLRS/tree/c88d67a429812664d464b36ace8e225926e04076

Disclaimer: It's kinda working but not tested thoroughly. Use at your own risk.

**Comment by SunjunKim** [comment]
> I've implemented an elementary dynamic power function on top of the RC9 release. Please try if you want:
> https://github.com/SunjunKim/ExpressLRS/tree/feature/dynamic-tx-power
> 
> Disclaimer: It's kinda working but not tested thoroughly. Use at your own risk.

https://www.youtube.com/watch?v=Ah6h-QqM6Xs
A very first test of dynamic TX power. The feature was working great, and a terrifying flight into a fog 🤣 .
