### ISSUE TITLE
elrs lua script missing backpack options

### ISSUE THREAD

**Issue by dead-circuit** [ExpressLRS/ExpressLRS#3067]
## Current Behavior

 Missing some option in script.
 Lua Script -> Wifi Connectivity -> Enable Backpack Wifi (missing)
 Lua Script ->  Backpack (missing)
 Lua Script -> Other device(missing) 

## Details
 missing options mentioned above.so i can not connect mavlink through wifi.
tried to compiled with   
 "use_backpack": true,
"debug_backpack_baud": 460800,
"debug_backpack_rx": 3,
"debug_backpack_tx": 1,
but doesnt work.
Tried to config TX  via http://elrs_tx.local/hardware.html page but it wont work either.

## Your Environment

- TX :hardware:diy 2.4g esp32s3+e28+esp01fbackpack
- RX: hardware:betafpv nano 2.4g rx
- Handset model:
- OpenTX version (including nightly number):edgeTX x-7  v2.9.2
- ExpressLRS version (TX & RX MUST MATCH): tx 3.5.3  backpack 1.5.1  rx 3.5.3
- Packet Rate:
- Telemetry Ratio:
- user_defines:
-USE_TX_BACKPACK
![1733908762078](https://github.com/user-attachments/assets/56b0d1be-da97-4574-a1c8-bdec03704b1d)
![1733908734365](https://github.com/user-attachments/assets/be109606-dc94-4a8c-aa8f-3e3384036d44)

**Comment by pkendall64** [comment]
It's DIY hardware, you are expected to add the options that you have on your DIY module.
Other Device will be missing if the TX is not connected to an RX when the script is loaded.
