### ISSUE TITLE
Associate Gemini X settings profile with model ID to handle multiple quads

### ISSUE THREAD

**Issue by psychotik2k3** [ExpressLRS/ExpressLRS#3069]
### Discussed in https://github.com/ExpressLRS/ExpressLRS/discussions/3068

<div type='discussions-op-text'>

<sup>Originally posted by **psychotik2k3** December 11, 2024</sup>
Now that gemini X is out there is one flaw that breakds the charm of ELRS: switching drone/airplane.

i mean i do have an 8 inch LR drone with gemini X module i configured on dual 2.4ghz and sub ghz, 
another of my quad is on classic elrs 2.4ghz no redudancy .
(got lot of other quads/planes but the idea is the same)

when i switch i HAVE TO open the LUA script to change the settings accordingly to the quad i want to fly. i have to remember what do i have as config on this quad etc etc...

the idea would be to be able to store the settings of gemini X mode and associate with the model ID, as edge tx is already using model ID to check we are linked to the correct model, the "only" thing would be to store the settings associated with the model ID</div>

**Comment by pkendall64** [comment]
We already do this! See https://www.expresslrs.org/software/model-config-match/?h=model#model-configuration

**Comment by psychotik2k3** [comment]
oops sorry thanks for the info
