### ISSUE TITLE
Unable to build a firmware with DEBUG_LOG enabled for Unified_ESP8525_900_RX target.

### ISSUE THREAD

**Issue by zendulkaj** [ExpressLRS/ExpressLRS#3070]
## Current Behavior
Unable to build a firmware with DEBUG_LOG enabled for Unified_ESP8525_900_RX target.

![image](https://github.com/user-attachments/assets/fe95cf2a-36ee-4133-a631-c857542ca673)

## Steps to Reproduce
1) enable  -DDEBUG_LOG in user_defines.txt
2) build  Unified_ESP8525_900_RX target

## Possible Solution (Not obligatory)
There is a typo in _src/rx_main.cpp_ at line 2216. I think  the _ExpressLRS_nextAirRateIndex_ should be used instead of the _index_.

![image](https://github.com/user-attachments/assets/3bdd5074-f5bf-4a6f-a49b-7fc234301628)

## Your Environment

- TX hardware:
- RX hardware: Unified_ESP8525_900_RX 
- Handset model:
- OpenTX version (including nightly number)
- ExpressLRS version (TX & RX MUST MATCH): 3.5.3
- Packet Rate:
- Telemetry Ratio:
- user_defines: -DDEBUG_LOG

**Comment by pkendall64** [comment]
This is fixed in the master branch of the code.
