### ISSUE TITLE
ELRS is not working TX12?

### ISSUE THREAD

**Issue by waiphyoaung712** [ExpressLRS/ExpressLRS#3072]
## Steps to Reproduce

1.

2.

3.

4.

## Your Environment

- TX hardware:
- RX hardware:
- Handset model:
- OpenTX version (including nightly number)
- ExpressLRS version (TX & RX MUST MATCH):
- Packet Rate:
- Telemetry Ratio:
- user_defines:

**Comment by JyeSmith** [comment]
Closing as none of the requested information has been provided.
