### ISSUE TITLE
Support for Flysky FRM302

### ISSUE THREAD

**Issue by SUPANOOB-ZA** [ExpressLRS/ExpressLRS#310]
Hi Devs

Is it possible to extend this to the Flysky FRM302 hardware?

Thanks in advance

**Comment by greenbigfrog** [comment]
Yes, it should be able to run eLRS on FRM302 hardware, it's just that no one has bothered tracing the pins etc.
At their price point it's also not really competitive at all to the DIY 2.4 Tx module. The tx module is a rather simple build, only combining different modules.

Some people tried using the flysky Rx for eLRS, not sure what the state of that was. ( CC @JamesKingdon : IIRC they bought some at some point to play with)

**Comment by SpaghettiHands** [comment]
I have a FRM302 Unit that I would LOVE to flash with eLRS! what needs to be mapped out?

**Comment by SUPANOOB-ZA** [comment]
Hi Devs,

*PLEASE OPEN THIS ISSUE*

The FRM302 is a 2 watt TX using the Semtech SX1281 2.4GHz LoRa chip. Information below ...

(link 1: https://www.semtech.com/products/wireless-rf/lora-24ghz/sx1281) 

(link 2: https://media.digikey.com/pdf/Data%20Sheets/Semtech%20PDFs/SX1280-81_Rev3.2_Mar2020.pdf )

(link 3: http://www.multirotorguide.com/news/flysky-frm302-afhds3-long-range-system/ )

![image](https://user-images.githubusercontent.com/71846889/155266728-d3a2d5d4-342d-40ae-bd89-9b1c948925f0.png)


With the above information is it possible to create a target to flash firmware to this TX ?


Thanks
Regards

**Comment by rajnish22-glitch** [comment]
Hi , it has the same chip but the Power amplifier is different if the devs are ready to work on it i can provide them the necessary details as the module has a fixed gain amplifier which has been discontinued (AWB7232) and it has an rf switch as well, which has a really small package but i think the working should be the same as the ones in the diversity rx or [CG2214M6][https://www.cel.com/pdf/datasheets/CG2214M6.pdf] i have these chips for my DIY 4W tx and both of these look quite the same ill check the pinout in the weekend, but before this i want to know if the devs are interested.

**Comment by SUPANOOB-ZA** [comment]
Thank you !

**Comment by SUPANOOB-ZA** [comment]
Was this ever completed?

**Comment by commanderguy3001** [comment]
would be interesting to know what microcontroller is on that frm302 receiver, as that really is the most deciding factor if you can flash elrs to it or not

**Comment by SUPANOOB-ZA** [comment]
It seems it was done... To a point.. I'm - waiting for more info... ![Screenshot_20220710_134450_com.facebook.katana.jpg](https://user-images.githubusercontent.com/71846889/178143464-1121b54b-16b2-4dbe-a4a5-affeaee798c9.jpg)

https://www.facebook.com/groups/636441730280366/permalink/1008298993094636/

**Comment by nightflasher** [comment]
well well well...flysky has this new radio "[Elysium](https://www.flysky-cn.com/el18-specifications)"  with AFHDS-3, this could be the next ExpressLRS only radio!?
