### ISSUE TITLE
EEPROM discovery required

### ISSUE THREAD

**Issue by JyeSmith** [ExpressLRS/ExpressLRS#319]
The below hardware still requires the eeprom to be discovered and setup for features such as binding.

- [ ] R9slimplus
- [ ] R900
- [ ] Ghost Atto
- [ ] Ghost Zepto
- [ ] Ghost Tx

**Comment by cruwaller** [comment]
Would it be easiest to use part of the flash for this? Support is built into Arduino core for easy use...
