### ISSUE TITLE
Ghost TX Support

### ISSUE THREAD

**Issue by brandonrc** [ExpressLRS/ExpressLRS#322]
This is what I have so far. 
```
BUSY = PB15
DIO1 = PB2
MOSI = PA7
MISO = PA6
SCK = PA5
NSS = PA15
RST = PBO
LED = PB6

PA3 is analog feedback of the output power
PB11 is enable and will need to be set high to turn on the amp.  

```

**Comment by atr2600** [comment]
![Uploading image.png…]()

**Comment by atr2600** [comment]
![image](https://user-images.githubusercontent.com/25802530/104976892-e1fed080-59c3-11eb-93e8-f3a80c166e3f.png)

**Comment by atr2600** [comment]
![image](https://user-images.githubusercontent.com/25802530/104976925-efb45600-59c3-11eb-9094-bf5fdb0593eb.png)

**Comment by atr2600** [comment]
![image](https://user-images.githubusercontent.com/25802530/104976939-f93dbe00-59c3-11eb-965e-4bb5972b5d98.png)

**Comment by atr2600** [comment]
![Uploading image.png…]()

**Comment by atr2600** [comment]
![image](https://user-images.githubusercontent.com/25802530/104981140-aff26c00-59cd-11eb-9cf8-e7189b2cdb9b.png)

**Comment by atr2600** [comment]
![image](https://user-images.githubusercontent.com/25802530/104981721-c51bca80-59ce-11eb-8292-474c934d7647.png)

**Comment by mavericm1** [comment]
[https://i.imgur.com/CZHvgLg.jpeg](url)

**Comment by mavericm1** [comment]
https://i.imgur.com/51qPYOj.jpeg

**Comment by mavericm1** [comment]
https://i.imgur.com/JeqDSib.jpeg

**Comment by mavericm1** [comment]
https://i.imgur.com/X87XGgu.jpeg

**Comment by mavericm1** [comment]
https://imgur.com/a/eSphNFu

**Comment by atr2600** [comment]
![image](https://user-images.githubusercontent.com/25802530/105658752-c9435e80-5e8c-11eb-9947-d520a2adaa5c.png)

**Comment by howels** [comment]
Saw the ghost TX bootloader PR, what's the current status of ghost TX support?

**Comment by AlessandroAU** [comment]
It's ready :)

**Comment by howels** [comment]
> It's ready :)

Tx lite or only the full size?
