### ISSUE TITLE
Feature Request - configuration via CRSF engine

### ISSUE THREAD

**Issue by howels** [ExpressLRS/ExpressLRS#328]
In original Crossfire and Tracer modules the CRSF interface is used not just for radio commands but also to supply a menu interface to configure the TX module and RXs attached.  
These menus are driven dynamically via the firmware in the TX module and not just via hard-coded prompts in the lua scripts. Because of this an older radio can still use the CRSF engine to configure a newer module with newer features.

Could ELRS use this system also, so that ELRS features could magically appear when the TX was updated and not require new LUA scripts or specific on-radio support for ELRS beyond the existing CRSF support?

**Comment by expipiplus1** [comment]
Where/is this part of the crsf specification documented?

**Comment by howels** [comment]
> Where/is this part of the crsf specification documented?

The crossfire scripts on opentx are a good place to start: https://github.com/opentx/opentx/tree/2.3/radio/sdcard/taranis-x7/SCRIPTS/TOOLS/CROSSFIRE

**Comment by expipiplus1** [comment]
hahah, code as documentation, love to see it

**Comment by howels** [comment]
> hahah, code as documentation, love to see it

Well the eLRS code is written and working now so it wasn't that bad. 😉
I did the testing for deviation TX, it's a really neat feature.
