### ISSUE TITLE
feature request: Some sort of OLED Display

### ISSUE THREAD

**Issue by WillsGledhill** [ExpressLRS/ExpressLRS#345]
Just had a thought: Would there be a way to implement a OLED display and a joystick into the existing modules? Maybe just soldering to any unused pins on the processor?

**Comment by ariefadha** [comment]
Im the way on designing a pcb with oled and 5 way button, but with separate mcu that also handle buzzer.

Im planning with separate mcu because we might need extra features and display so we dont bother with esp32 that handling the rf communication.

**Comment by JyeSmith** [comment]
What would an oled be used for that lua can not?  It's also a heap of effort to make a UI.

**Comment by ariefadha** [comment]
Deviation does not have, and i think it will be faster to set.

I can make the UI

**Comment by jfrowies** [comment]
Everyone has a phone these days, how difficult would it be to interface with an app via wi-fi? I can make the app.

**Comment by nightflasher** [comment]
Well, immersionrc ghost got an oled screen - so this seems legit to ask for. I'm in, when buying an esp module, some come with oled screen, so why don't make user of it?
I also have some laying around.

**Comment by brandonrc** [comment]
@nightflasher Do you have any experience working with oled stuff? 

I worked on the ghost targets and have both the full and lite. I would love to add support for this.

**Comment by brandonrc** [comment]
https://photos.app.goo.gl/GtmHRMXc7JS4nDjE6

**Comment by brandonrc** [comment]
Removed the joy stick part.. opening a seperate issue now: 
https://github.com/ExpressLRS/ExpressLRS/issues/603

**Comment by brandonrc** [comment]
![image](https://user-images.githubusercontent.com/25802530/118385869-8262ab80-b5d8-11eb-9a1d-a01f80768fc6.png)
Full size 128x64

![image](https://user-images.githubusercontent.com/25802530/118385879-99a19900-b5d8-11eb-84ce-614786663a14.png)
Lite size 128x32


These are the ghost tx and ghost tx lite but you can add a OLED 128x64 or a 126x32 to your DIY TX and we can add support for it :)

**Comment by nightflasher** [comment]
I've done some work on oled, but mostly:
"foo: $val.foo"
"bar: $val.bar"
And that's all what's needed! IMHO

Maybe another tickbox in the configurator to activate the oled (Btw where can I connect a buzzer/piezo to the ttgo variants?). So you can add an oled if you like to do so and activate it - like the melody or beep.

**Comment by nightflasher** [comment]
Today I've started working on this for the ttgo_v2 lora32 with oled screen.
There will be some changes in the OLED defines, and I don't know, if it is okay to prepare the firmware for adding an i2c display for non-oled modules. I would recommend a checkbox and radio button in the configurator to select HAS_OLED and 128x64/128x32. And it should be smarter to program this part to shorten TARGET_TX_GHOST_LITE to HAS_OLED32 and HAS_OLED64 and it needs the ifdef _I2C to differentiate.

I hope everyone understands, been a while since I wrote "deep" technical stuff and so in english.

**Comment by brandonrc** [comment]
@nightflasher if you can use my branch pr-oled-support then make a merge request to that branch I would love to check the changes out!!!

I agree with your changes.. we do something smart where if 
```
#ifdef GPIO_PIN_OLED_I2C
Do xyz for i2c stuff
#else
Do oled stuff for SPI
#endif
```

So just based on which pins you are using we can know wether it is i2c of spi. :)

**Comment by brandonrc** [comment]
@nightflasher I just ordered a ttgo_v2.1 to help out something with debugging issues. I could also test your code when you make the pull-request to the `pr-oled-support` branch.

**Comment by nightflasher** [comment]
i'm already working with this branch, trying first time platformio, but doesn't seem to be to hard.
