### ISSUE TITLE
Betaflight TX Lua Scripts support

### ISSUE THREAD

**Issue by FireNWater** [ExpressLRS/ExpressLRS#353]
I'd like to gauge interest in having ExLRS support for Betaflight TX Lua Scripts.

https://github.com/betaflight/betaflight-tx-lua-scripts

Personally, I'd like to be able to change Vtx frequencies from my handset instead of having to move around the OSD.

**Comment by pitts-mo** [comment]
Yes, I do hope it is practical to implement full telemetry support in default builds and allow for setting the rx side telemetry to off, minimal, or full from lua script or at the time of binding,

**Comment by schugabe** [comment]
MSP is now available: https://github.com/ExpressLRS/ExpressLRS/wiki/OpenTX-and-Betaflight-Setup#msp
