### ISSUE TITLE
What is this comment about?

### ISSUE THREAD

**Issue by JBKingdon** [ExpressLRS/ExpressLRS#357]
There's a comment on a couple of the ExpressLRS_AirRateRFperf entries that reads

`// this means always send sync on ch[0] as soon as we can`

eg

https://github.com/ExpressLRS/ExpressLRS/blob/c70778f0f1391fb085386091d0c3b6a06e5faa35/src/src/common.cpp#L22

This comment has always confused me - is it still meaningful? If it is, any chance of making it clearer, and if not, can we get rid of it?

**Comment by AlessandroAU** [comment]
That's a good point, it really doesn't make sense.
