### ISSUE TITLE
WIKI: ESP32 link for 2.4 GHz Tx module does not work anymore

### ISSUE THREAD

**Issue by xRealNeon** [ExpressLRS/ExpressLRS#377]
![2021-03-09_23-57](https://user-images.githubusercontent.com/20997346/110550123-656eaf80-8133-11eb-84fa-3bd3d1518033.png)

**Comment by xRealNeon** [comment]
I have also noticed that the digikey link does not work

**Comment by JyeSmith** [comment]
Fixed https://github.com/ExpressLRS/ExpressLRS/pull/396
