### ISSUE TITLE
R9slim+  diversity

### ISSUE THREAD

**Issue by fpvDurman** [ExpressLRS/ExpressLRS#380]
good day. Will be support for r9 slim+ 
diversity?

**Comment by nangel0** [comment]
YEs, antena diversity suport is already merged and working on develop branch.

can we close this @fpvDurman ?

**Comment by mrgalex** [comment]
I have R9 Slim RX. No firmware to flash it discovered. The only Slim+ supported by ELRS, not the Slim, is that wright?

**Comment by nangel0** [comment]
Not sure if the target is the same now... I belive at são-me point the slim
target was available. Jump in discord to ask for that.

A quinta, 20/05/2021, 11:58, mrgalex ***@***.***> escreveu:
