### ISSUE TITLE
Support for SIYI FM30 TX

### ISSUE THREAD

**Issue by CapnBry** [ExpressLRS/ExpressLRS#381]
The SIYI FM30 is a 2.4GHz transmitter module for JR bays based on the SX1280 chip with +22.5dBm output power (via SiGe 2431L) and integrated bluetooth. The MCU is an STM32F103C8 with a 16MHz crystal (HSE_VALUE=16000000U). Flashing is done via STLINK through a conveniently labeled SWD pin header, but there is also a mini USB port connected. I'm working on support but I'm creating this ticket to provide the pin mapping and layout for interested parties.

| Pin | Function | Remarks
|---|---|---|
|PA0| 16 pos switch | Bit 0001
|PA1| 16 pos switch | Bit 0010
|PA2| USART2_TX | Bluetooth TX
|PA3| USART2_RX | Bluetooth RX
|PA4|16 pos switch| Bit 0100
|PA5| 16 pos switch | Bit 1000
|PA6| PPM Input? | Top pin (1) of JR module, labeled SBUS RX3 PPM, through diode
|PA7| LED Left Green | Active low
|PA8| Bluetooth VCC Enable | Low to enable Bluetooth chip's power
|PA9| USART1_TX | RC Signal TX, connected through XOR chip (input) / diodes to JR pin 5
|PA10| USART2_RX | RC Signal RX, connected through XOR chip (output) / diodes to JR pin 5
|PA11| USB | Mini USB port
|PA12| USB | Mini USB port
|PA13| SWDIO |
|PA14| SWCLK
|PA15| LED Left Red | Active low
|PB0| Button | Active high
|PB1| LED Right Green | Active low
|PB2| LED Right Red | Active low
|PB3| SX1280 RST |
|PB4| 2431L Antenna Select | Low for pre-installed antenna (Left IPEX)
|PB5| RX3 Inverter? | 
|PB6| TX1RX1 Inverter | Input to RX1 XOR Gate (PB6 XOR RX1TX1)
|PB7| TX1RX1 Inverter | Input to TX1 XOR Gate (PB7 XOR TX1) - BUFFER_OE
|PB8| SX1280 DIO1 |
|PB9| 2431L CTX | High for transmit, Low for receive
|PB10| USART3_TX | Not connected (missing resistor to connect to JR pin 2)
|PB11| USART3_RX | Connected through inverter to JR Pin 1 (shared with PPM)
|PB12| SX1280 SPI chip select |
|PB13| SX1280 SPI SCK |
|PB14| SX1280 SPI MISO |
|PB15| SX1280 SPI MOSI |

The RF module has pins brought out to castellations. One of the bottom left pins may not be ground, but it is connected directly to ground.
| Left | Right |
|---|----|
| | SX1280 RST
| | SX1280 DIO1
| | SX1280 SPI chip select
| | SX1280 SPI MOSI
| | SX1280 SPI MISO
| | 3.3V
| 2431L CTX | 
| SX1280 Busy |
| 2431L Antenna Select |
| SX1280 SPI SCK |
| GND |
| GND |

The connection to the Taranis is through UART1, via a SN74LVC2G86 dual XOR gate:
![fm30_inverter](https://user-images.githubusercontent.com/677183/111315754-0fb96c00-8639-11eb-8637-de29122c10ac.png)

### Challenges
* ~~No BUSY pin connected to MCU. ELRS TX works if you bypass the BUSY pin checks but I'm not sure how this will affect stability.~~
* ~~No external EEPROM. Configuration will need to be stored in STM32 flash, possibly using [AN2594 EEPROM Emulation](https://www.st.com/resource/en/application_note/cd00165693-eeprom-emulation-in-stm32f10x-microcontrollers-stmicroelectronics.pdf)~~
* ~~The RF amplifier is fairly limited, in that you can only transmit at full power or not at all. Input power is limited to +6dBm.~~
* Bluetooth would be sweet to add MSP support, but the chip label has been lasered off. Possibly Zhuhai Jieli Technology Co., Ltd. AC6905A or similar? 24pin QSOP.

Try to ignore my flying wires here, I forgot to take photos before I started.
![DSC07443](https://user-images.githubusercontent.com/677183/111034272-cbcd2980-83e2-11eb-889c-bfa684dfb8f5.JPG)

![DSC07444](https://user-images.githubusercontent.com/677183/111034275-cf60b080-83e2-11eb-86c7-a54e00896187.JPG)

The specs say voltage input is limited to 8V, but I've been using 3S. SIYI Technology posted to rc groups:
"*After consulting the hardware engineer, he says the module can be supplied with up to 15V.*"

## RF Power Outputs
| SetPowerLevel | Power (mW) |
|---|---|
|-16 | 7.7-8.0
|-15 | 10.5-10.7
|-12 | 21-22
|-11 | 26-27
|-8 | 47-48
|-7 | 55-56
|-6 | 62-63
|-3 | 75-76
|-1 | 84-85
|0 | 100
|1 | 115
|3 | 130
|6 | 150

**Comment by Dropsleutel** [comment]
Is there any hope that we can have the SiYi Rx ported to operate as a 2.4ghz Tx module ?  (A similar thing has been done with the R9 Rx at the time)
SiYi has the same cpu and RF chain, inc 250mW Pa. As it is super tiny it would be really great for embedding inside my tx. 

https://github.com/ExpressLRS/ExpressLRS/issues/308

**Comment by CapnBry** [comment]
I'm closing this because this is merged now. SIYI RX as a TX will come as a new PR if it is done.
