### ISSUE TITLE
Lua script does not show data and can´t save settings.

### ISSUE THREAD

**Issue by Noctaro** [ExpressLRS/ExpressLRS#389]
Hi all,
i have troubles using the LUA script for monitoring and adjusting settings on my Frksky X-Lite. After i have tested it with OTX 2.2.3, i decided to update my X-Lite to OTX 2.3.10 from the ELRS repo. I am using the TTGO V2 transmitter. The LUA script will always work the first time after changing the baudrate in the hardware tab in OTX. It does not matter what baudrate option i choose. If i close the LUA script, i again have to change the baudrate before i get data from the script again. If i change settings within the running script, they will not be stored. It seems to me there is a problem on how OTX handles the script. Is there anything i could have done wrong? 

Btw. the module does bind and i can fly it using my RX_Mini v0.1. But i would love to be able to adjust transmit power.

Update: 
I was told to mention the version of ExpressLRS, it is 0.1.3 Release Candidate 2. Here you can find my user-defines settings file
[user_defines.txt](https://github.com/ExpressLRS/ExpressLRS/files/6175989/user_defines.txt)

Update 2:
I have tested it with an connected rx. It seems i get data from the script as soon as an rx is connected. But if i change transmit power and exit the script, connection is lost and it will state ??? again. After rebooting the radio, LUA settings are restored to default. Also the rx will not bind, even after i disconnect it from power, until i restart the radio.
If i do not change any settings the rx stays connected after closing the LUA script. If i restart the script, i can see data again at least until i make any changes.

**Comment by GhVost** [comment]
I can only confirm the issue. I think the lua script instead of doing the right thing crashes the program of the module.

**Comment by GhVost** [comment]
I have question: why did you decided to use the "-DRegulatory_Domain_EU_868" in your 2.4 GHz module?

**Comment by Noctaro** [comment]
> 
> 
> I have a question: why did you decided to use the "-DRegulatory_Domain_EU_868" in your 2.4 GHz module?

I do have a 868mhz module, not 2.4ghz :)

**Comment by Noctaro** [comment]
I have tested my TTGO V2 using the dev branch today, LUA script is working now! :)
Should i close this issue?

**Comment by GhVost** [comment]
Great! Can you share the link?

**Comment by Noctaro** [comment]
> 
> 
> Great! Can you share the link?

https://github.com/ExpressLRS/ExpressLRS/tree/develop

**Comment by GhVost** [comment]
Hey,
thanks a lot! I use the dev branch since then without any issues. Do you know by any chance when the battery voltage and other important things will be added to the telemetry parameters?
Please close the issue, but add the solution in your last comment — the elrs is just picking up and it will definitely help hundreds.
By the way, I had this issue with the 2G4 DIY module.
 
Cheers
 
  
>Friday, March 26, 2021 8:29 PM +03:00 from Noctaro ***@***.***>:
> 
> 
>I have tested my TTGO V2 using the dev branch today, LUA script is working now! :)
>Should i close this issue?
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
A G
