### ISSUE TITLE
Feature: cache python dependencies and .platformio in github actions

### ISSUE THREAD

**Issue by jurgelenas** [ExpressLRS/ExpressLRS#442]
It would be great to cache python dependencies and `~/.platformio`. I think it has a great potential in reducing build times.

**Comment by jurgelenas** [comment]
If nobody implements that I am planning on implementing this during the weekend

**Comment by CapnBry** [comment]
That would be awesome. It is downloading the entire platformio platforms and packages every time right? It would be great not just for making them faster but also for taking fewer resources from github and pio.

**Comment by jurgelenas** [comment]
Yes we are good on this one. Great job @pkendall64. Closing.
