### ISSUE TITLE
DIY_2400_TX_ESP_SX1280_E28 no openTX communcation on develop

### ISSUE THREAD

**Issue by brandonrc** [ExpressLRS/ExpressLRS#452]
Using latest develop branch as of 4/9/2021, 

no communication :(

Currenlty tested commit hash
c68ef6d95b8b3234febddfe38eb78f1ef69fef0b
And that works. 

The issue happened between that hash and current.

**Comment by brandonrc** [comment]
c68ef6d95b8b3234febddfe38eb78f1ef69fef0b is working is what I ment

**Comment by AlessandroAU** [comment]
Give it another go with latest

**Comment by CapnBry** [comment]
Can we close this now @brandonrc, does 1.0RC1 work for you?

**Comment by phobos-** [comment]
works fine for me at least

**Comment by brandonrc** [comment]
Hardware issue, not software.
