### ISSUE TITLE
[Question] R900 and FrSky compatibility

### ISSUE THREAD

**Issue by LucaBertuolo** [ExpressLRS/ExpressLRS#503]
Hello,
could a Jumper R900 Rx bind with a  Frsky R9M Tx, both with ExpressLRS?

If yes, I'm in EU, so the R9M is configured with the 868MHz frequency, does the R900 work with 868MHz?

**Comment by JyeSmith** [comment]
Yes all 900 tx and rx will work with each other when flashed with the same freq domain.
