### ISSUE TITLE
1.0.0-RC1 Telemetry sensors missing with tlm ratio 1:64

### ISSUE THREAD

**Issue by alexvazquez** [ExpressLRS/ExpressLRS#509]
Today I flashed the latest release 1.0.0-RC1 to my TX and RX. On both, I set the ENABLE_TELEMETRY option and also HYBRID_SWITCHES_8. 

Additionally in the TX I enable TLM_REPORT_INTERVAL_MS and set the default of 320LU because my radio uses OpenTX.

Plugged the FC to the battery and turned on my radio and then I Delete all sensors from the telemetry page and started discoverting new ones. My surprise is that now instead of 14 from previews builds I only got 10. For example RxBt is gone.

Am I missing something?

**Comment by schugabe** [comment]
The rx sends all telemetry packages it does receive and I did just verifiy that RxBt still is displayed on my test setup (also after deleting + discovering the sensors).

What FC firmware are you using?

**Comment by alexvazquez** [comment]
> The rx sends all telemetry packages it does receive and I did just verifiy that RxBt still is displayed on my test setup (also after deleting + discovering the sensors).
> 
> What FC firmware are you using?

Hi @schugabe thanks for your reply. Im using a Mamba F405 Mini MK2 that users FURYF4OSD betaflight firmware 4.2.8 Feb 15 2021. Using this same FC but with 0.1.3-RC2 I can see RxBt (total 14 sensors). If I do the ExpressLRS firmware update to my receiver and TX to 1.0.0-RC1 then after I discover new sensors I can only see 10 and RxBt is not there anymore. So I don't think this could be related to the FC firmware. 

Anything I could try?

**Comment by schugabe** [comment]
Can you try to open the expresslrs lua script and set the tlm ratio to 1:16 and then try to discover the sensors?

**Comment by alexvazquez** [comment]
> Can you try to open the expresslrs lua script and set the tlm ratio to 1:16 and then try to discover the sensors?

@schugabe smart!! you found the issue. Once I set to 1:16 I got all of them. Beautiful.

Thanks a lot

**Comment by alexvazquez** [comment]
> Can you try to open the expresslrs lua script and set the tlm ratio to 1:16 and then try to discover the sensors?

@schugabe I could validate that it worked perfect with Betaflight, but now I use the same receiver but in a Matek F411 WSE FC having INAV firmware and when I do discover sensors I only get 10 sensors and there is no one about battery voltage. Is this an issue or expected?

Thanks

**Comment by 0crap** [comment]
Yeah, run into the same issue. I had telem stil on 1:64 and lost a few sensors.
After setting TLM to 1:16 they came back, including GPS and a few.

I did notice not all sensors have now the same refresh rate, is that normal?
(The * sign behind the sensors indicate different refresh rates.)

**Comment by schugabe** [comment]
> Yeah, run into the same issue. I had telem stil on 1:64 and lost four sensors.
> After setting TLM to 1:16 they came back, including GPS and a few.
> 
> I did notice not all sensors have now the same refresh rate, is that normal?
> (The * sign behind the sensors indicate different refresh rates.)

That is normal: Link status is updated independent: https://github.com/ExpressLRS/ExpressLRS/wiki/OpenTX-and-Betaflight-Setup#telemetry I did record some gifs to show the expected behaviour.

@alexvazquez inav should work as well but I will try it on my inav quad. Can you please change the title of the issue to "Telemetry sensors missing with tlm ratio 1:64" because that seems to be the configuration that does not work

**Comment by alexvazquez** [comment]
> > Yeah, run into the same issue. I had telem stil on 1:64 and lost four sensors.
> > After setting TLM to 1:16 they came back, including GPS and a few.
> > I did notice not all sensors have now the same refresh rate, is that normal?
> > (The * sign behind the sensors indicate different refresh rates.)
> 
> That is normal: Link status is updated independent: https://github.com/ExpressLRS/ExpressLRS/wiki/OpenTX-and-Betaflight-Setup#telemetry I did record some gifs to show the expected behaviour.
> 
> @alexvazquez inav should work as well but I will try it on my inav quad. Can you please change the title of the issue to "Telemetry sensors missing with tlm ratio 1:64" because that seems to be the configuration that does not work

Title changes @schugabe , let’s see what you get on your INAV quad. Thanks a lot.

**Comment by CapnBry** [comment]
I can also confirm that 1:64 does not seem to work on 500Hz, 250Hz, 150Hz rate (all I tested). The RX thinks it is sending it, getting Telemetry confirmations too, so I think it is on the TX side. I'm looking into it and will hopefully have a fix shortly.

**Comment by alexvazquez** [comment]
> I can also confirm that 1:64 does not seem to work on 500Hz, 250Hz, 150Hz rate (all I tested). The RX thinks it is sending it, getting Telemetry confirmations too, so I think it is on the TX side. I'm looking into it and will hopefully have a fix shortly.
> 
> EDIT: 1:128 also appears to not be working either

Awesome, appreciate it so much.

**Comment by schugabe** [comment]
> > Can you try to open the expresslrs lua script and set the tlm ratio to 1:16 and then try to discover the sensors?
> 
> @schugabe I could validate that it worked perfect with Betaflight, but now I use the same receiver but in a Matek F411 WSE FC having **INAV** firmware and when I do discover sensors I only get 10 sensors and there is no one about battery voltage. Is this an issue or expected?
> 
> Thanks

I did try my inav quad and it shows all tlm values (including gps). So I'm not sure why it's not working for you: try to check every part of the configuration to verify that all options are set accordingly.

**Comment by alexvazquez** [comment]
> > > Can you try to open the expresslrs lua script and set the tlm ratio to 1:16 and then try to discover the sensors?
> > 
> > 
> > @schugabe I could validate that it worked perfect with Betaflight, but now I use the same receiver but in a Matek F411 WSE FC having **INAV** firmware and when I do discover sensors I only get 10 sensors and there is no one about battery voltage. Is this an issue or expected?
> > Thanks
> 
> I did try my inav quad and it shows all tlm values (including gps). So I'm not sure why it's not working for you: try to check every part of the configuration to verify that all options are set accordingly.

Configuration for the Flight controller? I have Telemetry enabled in the Configuration tab in INAV dont know if I have to set something else. Any clue?

**Comment by alexvazquez** [comment]
> > > > Can you try to open the expresslrs lua script and set the tlm ratio to 1:16 and then try to discover the sensors?
> > > 
> > > 
> > > @schugabe I could validate that it worked perfect with Betaflight, but now I use the same receiver but in a Matek F411 WSE FC having **INAV** firmware and when I do discover sensors I only get 10 sensors and there is no one about battery voltage. Is this an issue or expected?
> > > Thanks
> > 
> > 
> > I did try my inav quad and it shows all tlm values (including gps). So I'm not sure why it's not working for you: try to check every part of the configuration to verify that all options are set accordingly.
> 
> Configuration for the Flight controller? I have Telemetry enabled in the Configuration tab in INAV dont know if I have to set something else. Any clue?

I erased the FC and flashed again with the firmware (INAV) and now is working. Very strange. But it worked. Thanks a lot

**Comment by alexvazquez** [comment]
With Express Lúa script 1:16 I get i my Taranis every 5 seconds “Lost telemetry” then “Telemetry recovered” and this all time. Very annoying 😫

**Comment by schugabe** [comment]
> With Express Lúa script 1:16 I get i my Taranis every 5 seconds “Lost telemetry” then “Telemetry recovered” and this all time. Very annoying 😫

Do you loose control if it reports tlm lost?

Please compare your telemetry page on the taranis with the gif here: https://github.com/ExpressLRS/ExpressLRS/wiki/OpenTX-and-Betaflight-Setup#telemetry the link senors should update in the same interval.

**Comment by sfjuocekr** [comment]
If you get "telemetry lost" you failsafe, if you get "sensor lost" you keep control.

**Comment by alexvazquez** [comment]
> If you get "telemetry lost" you failsafe, if you get "sensor lost" you keep control.

I dont feel Im getting failsafe when Telemetry lost message happens on my Taranis. I can keep flying but is annoying to have that message looping every 10 secs.

**Comment by alexvazquez** [comment]
> > With Express Lúa script 1:16 I get i my Taranis every 5 seconds “Lost telemetry” then “Telemetry recovered” and this all time. Very annoying 😫
> 
> Do you loose control if it reports tlm lost?
> 
> Please compare your telemetry page on the taranis with the gif here: https://github.com/ExpressLRS/ExpressLRS/wiki/OpenTX-and-Betaflight-Setup#telemetry the link senors should update in the same interval.

I don't loose control of the quadcopter.

**Comment by alexvazquez** [comment]
> I can also confirm that 1:64 does not seem to work on 500Hz, 250Hz, 150Hz rate (all I tested). The RX thinks it is sending it, getting Telemetry confirmations too, so I think it is on the TX side. I'm looking into it and will hopefully have a fix shortly.
> 
> EDIT: 1:128 also appears to not be working either

@CapnBry Hi, good morning. Do you have any estimation on the fix? Appreciate so much

**Comment by AlessandroAU** [comment]
Should be fixed in rc2

**Comment by alexvazquez** [comment]
> Should be fixed in rc2

Appreciate all the hard work. Is there any release date for RC2 ? Thanks 🙏

**Comment by AlessandroAU** [comment]
Released a few hours ago :)

**Comment by alexvazquez** [comment]
> Released a few hours ago :)

Wooow that was fast jaajajajaj. will flash my receivers and TX and test. Again thanks a lot for the great effort. If I can help on something please dont hesitate to let me know.

**Comment by alexvazquez** [comment]
Is there a way to get the Cell Voltage in the telemetry?

**Comment by schugabe** [comment]
> Is there a way to get the Cell Voltage in the telemetry?

If the flight controller sends cell voltage in the telemetry stream it's received as cell voltage (betaflight has a setting for that). Please use the github issues only for bug tracking and all further questions are better discussed on discord
