### ISSUE TITLE
Github Issue template

### ISSUE THREAD

**Issue by jurgelenas** [ExpressLRS/ExpressLRS#510]
I suggest creating github issue template like I have on the configurator: https://github.com/ExpressLRS/ExpressLRS-Configurator/tree/master/.github/ISSUE_TEMPLATE

Documentation about github issue templates: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by CapnBry** [comment]
We definitely need issue templates, but I don't want the Issue system to become a Q&A forum so it would be great if the templates pointed that out. I'm also not super keen on it becoming a wishlist either, but I can see some value in that.
