### ISSUE TITLE
Continuous Reset on DIY Module 900 ESP32 RFM95 --> LED.h

### ISSUE THREAD

**Issue by axelfenner** [ExpressLRS/ExpressLRS#537]
Neopixel Led library fault, cause continuous reset on esp32
ESP_ERROR_CHECK(pixelCount >= 2 ? ESP_OK : ESP_ERR_INVALID_ARG);

To resolve the error, change the LED.h
Line: 4  --> const uint16_t PixelCount = 1; // this example assumes 1 pixel
to
Line: 4  --> const uint16_t PixelCount = 2; // this example assumes 2 pixel

Target:DIY_900_TX_ESP32_SX127x_RFM95_via_UART

**Comment by AlessandroAU** [comment]
Thanks for pointing that out! Cheers, https://github.com/ExpressLRS/ExpressLRS/commit/ad715da4fe2671cef044fdb641f9a735acdc16ca
