### ISSUE TITLE
[1.0.0-RC2] Ghost Atto LED, link color

### ISSUE THREAD

**Issue by 0crap** [ExpressLRS/ExpressLRS#554]
When the Ghost Atto RX is powered, without the TX turned on, it flashes Red, Blue, Green, which is perfect.
When the TX is turned on and a link is established the LED turns into a solid Red.

Red is usually the color to tell something is wrong, which is not the case.
Can the Ghost Atto LED be a solid Green when the link is established?

When this is considered being to anal, please feel free to close this issue. ;-) 👍 

![LED Atto- connected](https://user-images.githubusercontent.com/31951195/116784282-ad56e680-aa93-11eb-86d2-4881bc2ec9a6.jpg)

**Comment by CapnBry** [comment]
Try a different packet rate 😉

**Comment by 0crap** [comment]
> Try a different packet rate 😉

Brilliant! Didn't see that one coming. 👍  
Case closed!
