### ISSUE TITLE
Flight Mode - !ERR*

### ISSUE THREAD

**Issue by nightflasher** [ExpressLRS/ExpressLRS#557]
![IMG_20210501_214843_409-01](https://user-images.githubusercontent.com/3342605/116793527-87e3d000-aac7-11eb-94e0-0dbaf76496ff.jpeg)

As you can see, I have this message on my second quad. I also had problems with link quality in osd, which disappeared after flashing new betaflight (4.2.9 over 4.2.6). This happens on my OMNIBUS_F4_PRO (OMNIBUSF4SD target), diy 20x20 868MHz RX on UART6.

Another receiver (same type) is working with flight modes.

**Comment by CapnBry** [comment]
We don't make that value, that's created by the flight controller and we pass it through unmodified. The flight controller is telling you "ERROR".

**Comment by nightflasher** [comment]
Okay, I've checked everything and suddenly the FM changed to "WAIT", and after a while outside (bc of gps) I got the flight modes right.
Don't know why someone did this, but now I know what is happening.
Thank you!
