### ISSUE TITLE
RGB WS2812B

### ISSUE THREAD

**Issue by XSJFYZS** [ExpressLRS/ExpressLRS#566]
I want RGB! ! !
That's coooool!
Can turn green after getting telemetry

**Comment by CapnBry** [comment]
Sure

**Comment by nightflasher** [comment]
Not sure who did it, but define LED as single I/O not ws2812. Needs to be changed for at least the ttgo variants (working on third ttgo like version).

**Comment by brandonrc** [comment]
@nightflasher was this not resolved?

**Comment by brandonrc** [comment]
If we need to look at this please leave a comment. Closing issue now because we have RGB light show now.
