### ISSUE TITLE
900 MHz TX pcb

### ISSUE THREAD

**Issue by nightflasher** [ExpressLRS/ExpressLRS#569]
As I've read in the fpv-racing-forum, someone is going to build a really small tx module to place it inside the jumper t-lite, using the stock external module socket.
But this module will be 2.4 GHz, but I could find any diy 900 MHz TX. Did I overread something?

**Comment by CapnBry** [comment]
The issue system is not a Q&A Help Forum. Please ask questions on Discord or the Facebook Group:
 * [<img src="https://camo.githubusercontent.com/79fcdc7c43f1a1d7c175827976ffee8177814a016fb1b9578ff70f1aef759578/68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f7376672f646973636f72642e737667" width="15" height="15"> Community Discord](https://discord.gg/dS6ReFY)
 * [<img src="https://camo.githubusercontent.com/8f245234577766478eaf3ee72b0615e99bb9ef3eaa56e1c37f75692811181d5c/68747470733a2f2f6564656e742e6769746875622e696f2f537570657254696e7949636f6e732f696d616765732f7376672f66616365626f6f6b2e737667" width="15" height="15"> Facebook Group](https://www.facebook.com/groups/636441730280366)

I don't believe there is though.

**Comment by 3518813067** [comment]
https://oshwhub.com/ELRS/915TX
