### ISSUE TITLE
Happymodel TX915 Can't Flash via BootLoader

### ISSUE THREAD

**Issue by kusnendar** [ExpressLRS/ExpressLRS#576]
My happymodel TX915 can't update to RC3. Can't update via bootloader.

If use via boot loader then my HM can't read on my radiomaster. So must use via STLINK for reflash and work again

**Comment by brandonrc** [comment]
@kusnendar this worked on RC2?

**Comment by kusnendar** [comment]
> @kusnendar this worked on RC2?

Yes

**Comment by kusnendar** [comment]
Solve in RC5 version

**Comment by kusnendar** [comment]
Fix on RC5 version
