### ISSUE TITLE
Add firmware version on update web server. 

### ISSUE THREAD

**Issue by brandonrc** [ExpressLRS/ExpressLRS#584]
Someone on facebook asked how could they verify a flash was succesful with the wifi updater. They are using a radio that does not have a lua script so no way to check hash on that. 

Can we display the hash on the web server so that will allow people to check the flashed hash/version?

**Comment by kubrick89** [comment]
Why not just write the version (not the hash) in the static web page on each new release?

**Comment by greenbigfrog** [comment]
This could be added nicely as a step to `src/html/compile.sh` from #527 by @pkendall64 
Just add a sed or the like to patch in `git rev-parse --short HEAD`.

**Comment by pkendall64** [comment]
Yes, I've got some code that I'm working on for this, but am a bit busy with other things. Once we get to merging features for 1.1 then I'll get that change in there.

**Comment by pkendall64** [comment]
Changes have been made to PR#527 which will provide the tag or branch followed by the commit hash as the version.

**Comment by CapnBry** [comment]
Resolved for 1.1 thanks to pkendall64 #527
