### ISSUE TITLE
An AUX channel with more than three positions.

### ISSUE THREAD

**Issue by 3DRacer** [ExpressLRS/ExpressLRS#589]
In order to be able to use a 6-position switch or a camera tilt with more than three positions, another proportional channel would be helpful. The latency is irrelevant for this channel.

**Comment by greenbigfrog** [comment]
This has been possible since at least 1.0RC1: https://github.com/ExpressLRS/ExpressLRS/wiki/Switch-Modes

Did you find the information that it only has 3-Pos support somewhere here in the repository? Please let us know where, so we can update it.

**Comment by 3DRacer** [comment]
I probably overlooked that. Thank you for pointing out that it already works on AUX 8
