### ISSUE TITLE
Update GitHub description and add tags

### ISSUE THREAD

**Issue by michidk** [ExpressLRS/ExpressLRS#599]
The current description
`STM32/ESP32/ESP8285 based High Performance Radio Link for Quads` (actually, shouldn't it be High-Performance [with a dash]?)
seems a little bit outdated, since the `README.md` clearly states `ExpressLRS is an open source RC link for RC applications.`.

Therefore I propose to change the description to:
`🛩️ STM32/ESP32/ESP8285-based High-Performance Radio Link for RC applications`

At the same time, we could also add some tags/topics, which increases the visibility of this awesome project.
I propose the following ones (inspired by [iNav](https://github.com/iNavFlight/inav)): `rc`, `remote-controlled`, `LoRa`, `quadcopter`, `fpv`, `airplane`, `ESP8285`, `ESP32`, `STM32`

**Comment by AlessandroAU** [comment]
Done :)
