### ISSUE TITLE
Feature request: Joystick for Modules

### ISSUE THREAD

**Issue by brandonrc** [ExpressLRS/ExpressLRS#603]
Add support for 5 way joy stick's. Left, right, down, up, and click. 

Current TX's with 5 pos switch = Ghost hardware.

Need to find the 5 pins the switch is using. 

![image](https://user-images.githubusercontent.com/25802530/118404693-9094e400-b639-11eb-8a83-1cd1f1b34a5a.png)

**Comment by maybenikhil** [comment]
Is this being worked on @FOG-Yamato

**Comment by FOG-Yamato** [comment]
Yes it is being worked on currently.

**Comment by jurgelenas** [comment]
@brandonrc I think this can be closed now?

**Comment by nightflasher** [comment]
Don't close too hasty!
As the new betafpv microTX has an oled screen AND a 5 way joystick too (like the ghost modules), this is somehow already done by betafpv.
The rgb led can also adapted to the ghost modules!?

**Comment by brandonrc** [comment]
This has been added to master and will be available on 2.1.
