### ISSUE TITLE
PP_RX getber file does not load to jlc without issue on Pad_1mm

### ISSUE THREAD

**Issue by dkuchay** [ExpressLRS/ExpressLRS#604]
Attempted to order the PP_RX from JLCPCB but ran in to a problem that instructions did not cover. 

Gerber file, bom file and cpl file loaded to jlc however the item of PAD_1MM kicked out saying it didnt make sense to their inventory system. I chat in to their help system and asked someone to look the files over. They, "Mitchell" confirmed that Pad_1mm is not an item they can find either. Mitchell also asked to make the bridges that connect the 20mm frame to the 10mm board at least 4mm otherwise it may not manufacture cleanly. I searched discord but only found mention of the item during what looked like design time verbosity.  Also I ordered all the items in the bom for rx_nano but upon sorting out it looks like I bought a number of parts that are not used. Inductors to name one. Are these files current? I wasted a lot of time and money on parts I wont use. 

To reproduce either load the gerber file, cpl and bom files to jlcpcb and attempt to mark for jlc assembly and press next and or download the bom for rx_nano and compare to the image that is left for hints on layout. The items pictured do not match the bom.

**Comment by CapnBry** [comment]
You may want to repost this Issue on ExpressLRS-Hardware, since this is no longer the repository for hardware stuff
