### ISSUE TITLE
How to bind Happymodel EP2 with DIY TX

### ISSUE THREAD

**Issue by anerg2046** [ExpressLRS/ExpressLRS#619]
Connect 3 times with vbat, not work
Set bind password, not work

**Comment by pitts-mo** [comment]
Hello @anerg2046
Have you figured this out?

The lack of information provided seemed to prevent me from even speculating on this issue.

-Have you tried rebuilding TX and RX on the new v1.0.0 RC7 release?
-make sure you are using the same user defines on TX and RX ?
-in testing traditional and BINDING_PHRASE binding on my R9 hardware I did find the BINDING_PHRASE method leaves less to question.

If you are still hitting issue please provide more detail. I did notice new templates for reporting ExpressLRS issues. Maybe start a new issue, fill in the detail requested, and paste it back here or create the new issue?

good luck,
-p
