### ISSUE TITLE
No connection to module when switching model profiles

### ISSUE THREAD

**Issue by Xedos9er** [ExpressLRS/ExpressLRS#628]
## Current Behavior
When switching to a different Model on my TX16S and back to the model using ELRS, no connection is established. The ELRS Lua is also not able to acces the module. I need to power cycle the Radio to get it working again.

## Steps to Reproduce
Create any additional model wich is using different or no module. Activate this model and then switch back to the ELRS model.

## Your Environment
- TX hardware: Radiomaster TX16S on N495 nightly
- RX hardware: Happymodel ES24TX running 1.0RC5
- Packet Rate: 250hz
- Telemetry Ratio: 1/16
- user_defines: 320LU

**Comment by CapnBry** [comment]
Thanks for your report with all the important information, I was easily able to understand your problem and reproduce it. 

This is a bug in OpenTX, should be fixed in EdgeTX
https://github.com/opentx/opentx/issues/8514
