### ISSUE TITLE
Model Match

### ISSUE THREAD

**Issue by harry1453** [ExpressLRS/ExpressLRS#629]
Most protocols, including CRSF, have a receiver number that can be used to effectively assign different bound receivers to different OpenTX model configurations. Does ELRS support this? I can't find any mention of receiver number in the codebase. If not, this would be a great feature!

**Comment by jbman** [comment]
This request seems to be a duplicate of issue https://github.com/ExpressLRS/ExpressLRS/issues/544

**Comment by pitts-mo** [comment]
Hello @harry1453 
Are you able to add any specific concerns under #544 and close this issue?
Thank you,
-p

**Comment by harry1453** [comment]
Oopsie! Didn't see that, sorry. Duplicate of #544
