### ISSUE TITLE
R9 Slim RX

### ISSUE THREAD

**Issue by mrgalex** [ExpressLRS/ExpressLRS#635]
I have R9 Slim RX. No firmware to flash it discovered. The only Slim+ supported by ELRS, not the Slim, is that right?

**Comment by StonedDawg** [comment]
@mrgalex there is, FRSKY_RX_R9_SLIM_VIA_STLINK

**Comment by mrgalex** [comment]
> FRSKY_RX_R9SLIM_VIA_STLINK Can't find it anythere, even in Configurator

**Comment by CapnBry** [comment]
This was missing in the configurator, fixed in Configurator 0.5.1

**Comment by mrgalex** [comment]
Thanks a lot!
