### ISSUE TITLE
R9m & R9slim+ short range

### ISSUE THREAD

**Issue by DroneQuad** [ExpressLRS/ExpressLRS#644]
Have an issue with short range after flash RC7, on RC5 range good even run on 1:2 200hz
Any suggest?

**Comment by mdj36** [comment]
I can confirm the same issue. I got rx loss at 290 meters tx r9 2019 rx r9 mini . Express lrs  RC7  run on 1:2 200hz 250 mw power...

**Comment by alquezajanmaverick** [comment]
Same issue with mine. R9M + R9MX RC7 200hz 100mw power. Rx loss at around 100meters

**Comment by DroneQuad** [comment]
Now i can confirm the short range issue fix at RC9 update
