### ISSUE TITLE
FrSky r9 slim+

### ISSUE THREAD

**Issue by davifelix** [ExpressLRS/ExpressLRS#656]
good morning.  I begin by congratulating for this project.  you have turned a really mediocre system (r9) into something crazy.  I have a question to ask, I have an r9 slim + receiver which has two receiving antennas.  I have installed the latest version of the firmware, could I know if diversity works or if only one antenna works?  thank you very much!

**Comment by deadbytefpv** [comment]
Wiki: https://github.com/ExpressLRS/ExpressLRS/wiki/Flashing-R9slim-PLUS-(2-Antennas)-with-TX#antenna-wiring

**Comment by davifelix** [comment]
thank you guys!  I did not understand exactly where I have to enter "DUSE_DIVERSITY" since this option is not present in the configurator.  anyway tomorrow I give a view to the configurator to check the blackbox ..... thanks again!

**Comment by CapnBry** [comment]
Diversity exists on R9 Slim+ when built using the USE_DIVERSITY option. Closing since it looks like you found it.
