### ISSUE TITLE
Picture on how to connect Atto Receiver to STlink missing from Wiki

### ISSUE THREAD

**Issue by MightyWobbert** [ExpressLRS/ExpressLRS#666]
Hello Guys!
This is not a bug in ELRS but the Picture on how to connect the Atto Receiver with the STlink V2 is Missing. The Wiki-page does have the normal Text but the picture that was there is missing, only a small picture icon is shown. For someone who wants to flash an Atto RX it would be usefull to have this connection diagram again ;)

**Comment by deadbytefpv** [comment]
This has been rectified with a wiki edit...

**Comment by MightyWobbert** [comment]
The picture is now back and visable in the wiki, thanks!
