### ISSUE TITLE
Can't bind after flash Hapyymodel EP1

### ISSUE THREAD

**Issue by TheMagno** [ExpressLRS/ExpressLRS#687]
Hi, I was having troubles to flash my happymodel EP1 to RC8, a user in discord here help me a lot by tould me to soldert the pad on the receiver I so a did it i I could update the RX...then I desolder the pad and now I can't bind to the Radiomaster...same firmware version and same password!!! Can anybody help, please?

**Comment by TheMagno** [comment]
I have to keep the brigde to bind after flash? because i removed the bridge between the pads after successfully flash, and now I can't bind with the TX?

**Comment by maybenikhil** [comment]
can you send all of your define settings for both the TX and RX, and the lua script on your handset
