### ISSUE TITLE
Add firmware version information in LUA script screen

### ISSUE THREAD

**Issue by MicroMontis** [ExpressLRS/ExpressLRS#702]
It would be great to have ELRS TX firmware version  (eg. "FW Ver. 1.0 RC8") on the LUA script screen. This would solve a lot of confusion as I can see people scratching their heads and wondering what exact version they have on their TX.
There is a plenty space for additional info on the screen ;)
![screen-2021-06-24-233956](https://user-images.githubusercontent.com/15938741/123390608-c36cb900-d5a3-11eb-8372-f27be50cc64d.jpg)

Related to the FR: https://github.com/ExpressLRS/ExpressLRS/issues/584

*Instead of commenting "I want this too", consider leaving a :+1: instead, to reduce spam and clutter*

**Comment by zhoumigo** [comment]
yes  nice !!!

**Comment by NiklasVoigt** [comment]
it is more accurate to specify the git hash because it is unique. this way you can identify which branch etc. it is.

98310a == RC8

![Screenshot 2021-07-07 110415](https://user-images.githubusercontent.com/18678779/124732254-54805000-df13-11eb-9ed2-c0178da9d1ec.png)

**Comment by MicroMontis** [comment]
A common user (that does not use github in everyday life) would rather see "V1.0.0 RC8" instead of "98310a9" ;)

**Comment by howels** [comment]
I'd rather have the hash, it's less ambiguous.

**Comment by MicroMontis** [comment]
Why can't we have both? "So the wolves could be fed and the sheep kept safe.”

**Comment by maybenikhil** [comment]
#813 does this, although not perfectly, but can fetch tags + branches that aren't master

**Comment by jurgelenas** [comment]
@CapnBry since it was implemented in #704, can we close this now?

**Comment by CapnBry** [comment]
I suppose we can. 2.0 has the TX version number in the lua, and both the RX and TX show their versions and target on the webui. 1.x has the version number of the TX in the lua but there's still no way to see the RX version number, and we're not going to fix it for that branch since it is already done in master.
