### ISSUE TITLE
R9M Lite Pro with expressLRS

### ISSUE THREAD

**Issue by druckgott** [ExpressLRS/ExpressLRS#713]
Hallo,

Is it posible to Flash the R9M Lite Pro with expresslrs. I Do not realy find something Abort this. As rx i habe a r9mini.

In the configutator i fo und the R9M Lite Pro but Not with Stock bootloader.what des this mean?

Can somebody help me?

**Comment by Dropsleutel** [comment]
Please revert to discord Help or read the R9M Lite pro topic first. Yes it works but you need to flash first time with use of ST link, it is not to difficult simple to solder.  Later you can flash direct from your open Tx radio.

**Comment by s2kaka** [comment]
see #326 for info

**Comment by CapnBry** [comment]
This is not a support forum. Use discord to ask questions.
