### ISSUE TITLE
Support different settings of "extra data" for each receiver 

### ISSUE THREAD

**Issue by error414** [ExpressLRS/ExpressLRS#748]
Hi,

at first have to say, it's awesome project. 

I would like to use ELRS for all my flying stuffs. But for each plane/quad I would like to use different settings.

1) race quad:  no telemetry, no hybrid_switches_8
2) long range quad: telemetry. hybrid_switches_8
3) race wing: telemetry, no hybrid_switches_8
4) long range plane: telemetry, 4 full channels + 2 at least 8 bit channels.

I have to have two TX modules with different settings now. 

So would be nice to be possible to set different settings for each receiver ID in taranis.

I have no idea whether in TX module is enough memory for all of that.

**Comment by maybenikhil** [comment]
I would say this was implemented by #765
