### ISSUE TITLE
Update error: ERROR[4]: Not Enough Space

### ISSUE THREAD

**Issue by miggy1952** [ExpressLRS/ExpressLRS#774]
Using Configurator version Version 1.0.3 on a Mac using Safari and I get this message. When I am trying to flash EP Rx with wi-fi

**Comment by jurgelenas** [comment]
Can you verify that there is enough disk space in your computer?

**Comment by miggy1952** [comment]
50GB available, should be enough?

**Comment by jurgelenas** [comment]
Can you post full logs?

**Comment by miggy1952** [comment]
Thanks for all you help but I am lost. How/where will I find the full logs?

**Comment by miggy1952** [comment]
Ahhh! I should have mentioned that get the "ERROR[4]: Not Enough Space" when I am trying to flash EP Rx with wi-fi

**Comment by fredbotton** [comment]
Just in case, did you double-check you did not try mistakenly to upload the TX binary to RX? It is bigger than the RX one, and I've ended with that Not enough space error trying to do it. I'm fortunate it did actually fail 8-)

**Comment by miggy1952** [comment]
The firmware was called "firmware.elf" and is 1.5MB in size. Hope that helps?

**Comment by fredbotton** [comment]
Seconded, that's firmware.bin. Around 850Kb for TX, 360Kb for RX.

**Comment by miggy1952** [comment]
Yes that works! Many thanks all is good now.
