### ISSUE TITLE
LUA script not working - syntax error

### ISSUE THREAD

**Issue by Sekilsgs2** [ExpressLRS/ExpressLRS#775]
## Current Behavior

LUA script not working - syntax error.

## Steps to Reproduce

Downloading script https://github.com/ExpressLRS/ExpressLRS/blob/master/src/lua/black_and_white_display_128x64/TELEMETRY/elrs.lua
, place to Radio and try execute.

## Your Environment

- TX hardware: r9m 2019
- RX hardware: r9mm
- Handset model: jumper t12
- OpenTX version (including nightly number) 2.3.13
- ExpressLRS version (TX & RX MUST MATCH): latest
- Packet Rate: 50
- Telemetry Ratio: 1:64
- user_defines:

**Comment by deadbytefpv** [comment]
Download Lua script from here:
https://www.expresslrs.org/quick-start/tx-prep/#lua-script

This one's for v1.1 and still a WIP
