### ISSUE TITLE
via_BetaflightPassthrough not working if the FC is flashed with INAV

### ISSUE THREAD

**Issue by miggy1952** [ExpressLRS/ExpressLRS#779]
Works fine if the FC is running INAV (Matek 405 std) but did not work is the same fc is running INAV

**Comment by P-I-Engineer** [comment]
what rx? it works with most.

**Comment by miggy1952** [comment]
It was on a R9 MM-OTA. Worked fine when the F405 was flashed with Betaflight.

**Comment by P-I-Engineer** [comment]
i'm using a ghost rx (stm based, same as r9) and have no issues flashing passthrough with inav.

try turning telemetry off in inav and see if it flashes.

**Comment by aMax52** [comment]
Well these are little information we are getting here. I flashed my SIYS Mini on a F405 / INAV 2.61 with ELRS version 1.0.
 No problem. 
Are you on INAV 3.01? Keep in mind, if you are a Win 10 user, this can be even a problem , because sometimes this OS plays roulette with ports after an patch update.

**Comment by CapnBry** [comment]
I also have no issues flashing though iNav on EP1 and EP2 RX, but have not tried my R9 Mini. There was a bug in older versions of iNav that broke the passthrough, which iNav are you on?

Also as P-I-Engineer suggested, maybe try with the Telemetry feature turned off in iNav, and also be sure your TX is off.

**Comment by miggy1952** [comment]
Using INAV 3.01, I "Think" it might be related to having the FC powered by a LiPo or powered via the USB. Will get back to you with my results soon.

**Comment by miggy1952** [comment]
False alarm! My apologies!!! All works fine in both INAV and Betaflight.
