### ISSUE TITLE
Model matching without reboot of the handset.

### ISSUE THREAD

**Issue by bike797** [ExpressLRS/ExpressLRS#819]
Model matching idea(#765) is a fantastic feature, but it doesn't work without a power reboot after a model change on the handset (TX16S).

I don't know if this behavior is intended or a problem. 
However, I hope the model matching works well without rebooting the handset when changing the model.

**Comment by pkendall64** [comment]
This is a bug in OTX/ETX. The ETX fellas have fixed it in their master branch.
As a workaround, you can select a different model, then back to the model with the change and it sends the modelid command to the TX module.
