### ISSUE TITLE
R9 SX support

### ISSUE THREAD

**Issue by pskmac** [ExpressLRS/ExpressLRS#831]
Hey - I did not find R9 SX which I own, on the supported TX list.
Has anybody actually tried it? R9 SX seems to be an slightly upgraded version of R9 Slim+ which is supported, so i just thought that  it might work on R9 SX too some way.

Thanks, Maciej

**Comment by maybenikhil** [comment]
Currently no native recievers have PWM support

**Comment by pskmac** [comment]
Thanks!

**Comment by CapnBry** [comment]
Any flight controller that supports CRSF protocol and can output to servos will output to servos. We just send channel data.

**Comment by pskmac** [comment]
> Any flight controller that supports CRSF protocol and can output to servos will output to servos. We just send channel data.

I apologize, I am not sure that I fully follow. As guys were mentioning about pwm previously I thought they meant direct connection of servo to rx. I'm using FC so will elrs work on r9 sx?

**Comment by CapnBry** [comment]
No there is no support for FrSky R9 SX and there are no plans to support it since none of the developers has that hardware.

**Comment by pskmac** [comment]
Thanks, clear to me now.

**Comment by drtrigon** [comment]
> No there is no support for FrSky R9 SX and there are no plans to support it since none of the developers has that hardware.

I have one to spend if anybody is intressted just contact me.

**Comment by pskmac** [comment]
> > No there is no support for FrSky R9 SX and there are no plans to support it since none of the developers has that hardware.
> 
> I have one to spend if anybody is intressted just contact me.

Me too ;-)
