### ISSUE TITLE
Using INAV Lua using version 1.0.1 and INAV Lua  1.7.4

### ISSUE THREAD

**Issue by miggy1952** [ExpressLRS/ExpressLRS#836]
When I set to 10mw it correctly displays the power as 10mw in the INAV Lua
But when I turn the power up the INAV Lua displays 0mw. 

Is this a problem for the INAV Lua or for expresslrs?

**Comment by aMax52** [comment]
Google helps...https://github.com/teckel12/LuaTelemetry/releases. Plese read.
Just update some files, no complete new installation needed.

**Comment by miggy1952** [comment]
OK thanks, it made things better and it will display the correct power output but only sometimes.
between 10 and 25mw it is fine. between 25 and 50 only working sometimes.

I just noticed that once I change the power output in the expresslrs Lua and press enter that it will often roll back to the previous power setting.

**Comment by aMax52** [comment]
... you are right, After a recent test with an EP2,  I am missing the 50 mw display,  This works with my SIYI Mini on every setting.
Seems to be an issue with the EP rx. ( shows  10, 25, 100, 250 from a HW tx modul) and even the rates on the top line are not right . 150 as 50 and 50 as 150. Well, I can  live with that, as long the ELRS Lua does it show correctly.

**Comment by CapnBry** [comment]
There's no CRSF value for 50mW, so OpenTX, Betaflight, iNav, (etc including the iNav Lua) do not display it. That needs to be addressed on their side as there's nothing we can do about it from the ELRS side. We don't send "100mW" we send "3" which means 100mw and there's not value for 50mW.
