### ISSUE TITLE
TBS Fusion VRX WiFi Connection

### ISSUE THREAD

**Issue by microraptor** [ExpressLRS/ExpressLRS#839]
The TBS Fusion VRX module can connect to the WiFi of a TBS Crossfire/Tracer module, which enables these features:

- automatic VTX/VRX frequency sync
- dynamic VTX power
- telemetry OSD inserted on the VRX side

See page 24 onwards at: https://www.team-blacksheep.com/tbs-fusion-manual.pdf

It would be great, if someone could figure what kind of data/protocol the TBS Fusion needs for this connection. So that it will be possible to connect a TBS Fusion to an ExpressLRS TX with an ESP backpack and use these features.

@JyeSmith has already got the frequency sync working with a DIY VRX module: https://github.com/ExpressLRS/ExpressLRS/wiki/VRx-Backpack

*Instead of commenting "I want this too", consider leaving a :+1: instead, to reduce spam and clutter*

**Comment by CapnBry** [comment]
Take this to the [Backpack](https://github.com/ExpressLRS/Backpack) firmware project as that's where this is being worked on. Wez is already working on Fusion integration if it isn't already done.
