### ISSUE TITLE
If 1.1 is not compatible with 1.0 is it actually 2.0?

### ISSUE THREAD

**Issue by howels** [ExpressLRS/ExpressLRS#861]
## Current Behavior

Tested master on TX against RX on 1.0. Various reasons mean that this doesn't work, which is ok. 

However what is not ok is that next release is being called 1.1 which implies a minor update to 1.0. Actually there are breaking changes from 1.0. Breaking the behaviour of the prior version means that we have a new major version, 2.0 and not a minor update 1.1

Something to consider, most modern software uses semantic versioning to easily convey what a version number means. I don't think anyone will complain if we end up with version 17 in a few years; at least compatibility would be clear.

**Comment by CapnBry** [comment]
Yes
