### ISSUE TITLE
Ghost TX OpenTX Flashing Issues

### ISSUE THREAD

**Issue by maybenikhil** [ExpressLRS/ExpressLRS#867]
## Current Behavior

Ghost TX LED freezes on blue when I attempt to flash it through openTX

## Steps to Reproduce

Compile latest master via ExpressLRS Configurator and press "flash external module" in EdgeTX.

## Details

The TX works fine when flashed via STLinkv2

## Your Environment

- TX hardware: IMRC Ghost TX
- RX hardware: N/A
- Handset model: OpenTX
- OpenTX version (including nightly number)
- ExpressLRS version (TX & RX MUST MATCH): any master ver.
- Packet Rate: N/A
- Telemetry Ratio: N/A
- user_defines: N/A

Also @brandonrc asked me to tag @cruwaller

**Comment by brandonrc** [comment]
@cruwaller 

I am going to test this out but looks like something happened with the bootloader on the master branch for ghost tx's.

**Comment by cruwaller** [comment]
Ok, need to check. Have you flashed it successfully earlier?
Maybe it is something related to bootloader 🤔

**Comment by brandonrc** [comment]
I have not seen this issue. 

was it resolved? @cruwaller @maybenikhil 

Just flashed my stuff to 1.0 to 1.1 to 1.0 and back to 1.1-oled

**Comment by cruwaller** [comment]
No, I have done nothing and nothing is changed to bootloader.
@brandonrc , do you have the latest bootloader in use?
