### ISSUE TITLE
Change rx upload speed for Linux compatibility?

### ISSUE THREAD

**Issue by JBKingdon** [ExpressLRS/ExpressLRS#88]
The current upload speed for the rx doesn't work on Linux and it catches me out everytime. Would it be ok if we changed it to 460800?

**Comment by AlessandroAU** [comment]
For the pass-through programming? You can't change it because the RX is already listening at 420000baud for the special characters to reboot into bootloader.

**Comment by JamesKingdon** [comment]
No, this is for the initial direct flash. For some reason the speed we currently have doesn't work on Linux. Because I only do the initial flash rarely I always forget to change the upload speed and assume that I messed up the build of the rx. It would be likely to confuse someone new to the project as well :)

**Comment by JBKingdon** [comment]
No, this is for the initial direct flash. For some reason the speed we currently have doesn't work on Linux. Because I only do the initial flash rarely I always forget to change the upload speed and assume that I messed up the build of the rx. It would be likely to confuse someone new to the project as well :)

**Comment by AlessandroAU** [comment]
Ah right, does this happen for the ESP32 boards too?

**Comment by JBKingdon** [comment]
No, the esp32 boards are fine.

**Comment by AlessandroAU** [comment]
Ah ok, Are you using long hookup cables to connect the UART adaptor? I've seen that issue with long cables, I try to keep mine <10cm.

**Comment by JBKingdon** [comment]
Interesting idea. These are actually pretty short. I should do some more testing and see if I can figure out what the underlying issue is.

**Comment by cruwaller** [comment]
I haven't have any issue using Debian.
Which distro you are using?

**Comment by JBKingdon** [comment]
Mint. From the sound of it, it's most likely a limitation of the particular uart adapter I'm using.

**Comment by wvarty** [comment]
Missed this issue thread. FYI @JBKingdon uploading doesnt work reliably at 921600 either, and everytime I checkout a fresh branch, I need to manually set the rate to 115.2k before I flash, otherwise it fails.

**Comment by AlessandroAU** [comment]
You guys still having a problem with 921600 ?

**Comment by JBKingdon** [comment]
I always use 460800. The original problem reported was because the default came as a nonstandard speed that my Linux distro won't accept, but looks like they've been changed now. A quick test suggests 921600 is fine on my esp32 devkit. I don't have an rx handy to test on.

**Comment by wvarty** [comment]
Uploading fails 99% of the time on 921600. I have to change to 115200 every time. It’s habit now so no big deal.

**Comment by JBKingdon** [comment]
But if it fails for you it will fail for a new user who won't know what's going on.

**Comment by greenbigfrog** [comment]
I haven't had any issues ever anywhere on DIY and R9 stuff.
*I use arch btw*

**Comment by MonroeKA** [comment]
I use ubuntu as well no issues

**Comment by brandonrc** [comment]
@JBKingdon is this still an issue? 

Considering we have a Configurator now I will close this issue and if we see flashing issue we can open up the issue on that side. 

@jurgelenas do you think this is something we can add to the configurator? I think we talked about this before on the discord.
