### ISSUE TITLE
I still get a red error when I build any firmwares in China.

### ISSUE THREAD

**Issue by imjanuary** [ExpressLRS/ExpressLRS#885]
## Current Behavior

I still get a red error when I build any firmwares in China. I know we have an especial internet environment. 
Would you please take some time to fix this issue? Thank you!

request to https://raw.githubusercontent.com/ExpressLRS/ExpressLRS/1.1.0/src/user_defines.txt failed, reason: connect ECONNREFUSED 0.0.0.0:443

Mac OS

**Comment by deadbytefpv** [comment]
Great Firewall

**Comment by flosean** [comment]
You need to download the latest branch and build it from local, or you should use VPN to build online.

**Comment by 0crap** [comment]
@imjanuary Of course nothing the ExpressLRS team can do about.
Ask the great firewall to fix it.
Please close this issue, thank you.

**Comment by howels** [comment]
Maybe we can include instructions for offline builds? Perhaps user could download configurator plus a release archive and build from that.
