### ISSUE TITLE
New targets not included in 1.1.0

### ISSUE THREAD

**Issue by satyagupta** [ExpressLRS/ExpressLRS#893]
I had submitted a PR for new targets 

https://github.com/ExpressLRS/ExpressLRS/pull/790

It was merged in master, but the new targets are missing from the new release which is 1.1.0

![image](https://user-images.githubusercontent.com/443536/132805336-d8be696e-7442-4677-931c-e07c9487e55c.png)

In configurator select 
Release 1.1.0
Target: QuadKopters 2.4 Ghz
Device: Quadkopters JR 2400 TX

Our device is set to be released by next week. 
By when can we expect the new targets to be available for flashing via configurator. 

Thanks in advance

**Comment by sohamsp14** [comment]
Much needed merge in latest release! This will help with more hardware options in the market !

**Comment by CapnBry** [comment]
I had heard something about USE_DIVERSITY being explicitly disabled for your hardware, was that something you were going to change?

**Comment by satyagupta** [comment]
Yes, the current receiver that we have does not supports diversity but the new receiver would. 
There is sometime for the new receiver to come out, when we plan for that will submit a new PR with necessary changes for the receiver.

**Comment by CapnBry** [comment]
Gotcha, just trying to get all the information. There's a good chance we'll be targeting 2.0 before the end of the year and we're probably not going to do two more 1.x.x releases before that. I'm just trying to work out the timeline for what will go where.

**Comment by satyagupta** [comment]
Also the PWM receiver that we discussed over DM on discorrd thats on cards as well ;)

**Comment by CapnBry** [comment]
Closing as this was resolved in 1.2.0
