### ISSUE TITLE
EP2 doesn't want to work with SucceX E F405 Fc

### ISSUE THREAD

**Issue by Marcelogix** [ExpressLRS/ExpressLRS#921]
## Current Behavior

At first I tried to connect the EP2 with the Fc of the Nazgul 5 v1 as with my Diatone L4.
With the Diatone L4 it works perfectly fine. On the SucceX E F405 (Nazgul FC) it got stock in Bootloader. 
After searching for a while I found #655 and tried to use a pull-up resistor but it didn't work for me. 
When I power cylce the Rx while the FC is still connected it works perfectly fine (using binding with radio) until I unplug the whole FC.
As i didnt want to power cycle the Rx everytime with the FC still powered up, I moved to another Uart. On Uart6 it works sometimes after power cycling as in #912. Sometimes i need to connect the battery 2-3 times, sometimes way more often.
Everytime the Rx doesn't work, the led is dimmed (I used this as an Indicator).
I recognised that the EP2 gets quiet hot sometimes (as in #918). I didn't figure out wether its just normal or when wifi turned on.
After several times (everytime cooled back down to normal temperature) the receiver instantly broke and wouldn't turn back on.
I tried this twice and both EP2's burned out (first after 4-5 tries and second after ~25 tried).

Just ordered some more for testing

## Steps to Reproduce

1. Connect EP2 to Uart6 instead of Uart2

2. Connect the battery/usb cable

3. Power Cycle until the dimmed LED gets bright

4. After a lot of testing it burns ;)

## Possible Solution (Not obligatory)

At first receiver the ESP8285 broke. Maybe disabling wifi fixes the problem if its an overheating issue.

## Details

Tried with version 1.0.1 and 1.1.0 but left auto wifi always on (using 40 secs, so it shouldnt turn on usually?)

## Your Environment

- Quad: Nazgul 5 6s V1 (FC: SucceX E F405)
- TX hardware: Happymodel ES24TX
- RX hardware: HappyModel EP2 2.4 GHz
- Handset model:  RadioMaster Tx16s and RadioKing Tx16s (using T18 software)
- OpenTX version (including nightly number): 2.3.14-otx
- ExpressLRS version (TX & RX MUST MATCH): 1.0.1 and 1.1.0
- Packet Rate: 250Hz
- Telemetry Ratio: 1:64
- user_defines:
        REGULATORY_DOMAIN_ISM_2400
        BINDING_PHRASE
        LOCK_ON_FIRST_CONNECTION
        HYBRID_SWITCHES_8
        ENABLE_TELEMETRY
        AUTO_WIFI_ON_INTERVAL (40s)

**Comment by Marcelogix** [comment]
![Foto 21 09 21, 23 59 53](https://user-images.githubusercontent.com/76734338/134346442-f8ede1f7-571d-4b86-b673-d7a6f56872ca.jpg)

This is the first Ep2 which broke. The second one doesnt have these obvious spots

**Comment by Magginator98** [comment]
The second Ep2: The SDG gets hot here...
![1632319803626](https://user-images.githubusercontent.com/91203958/134360200-a5a92f1c-106b-49e1-8b66-995c3e7d92c9.jpg)
![1632319803614](https://user-images.githubusercontent.com/91203958/134360214-6293376e-6d70-4545-b224-9600ee4ff225.jpg)
.

**Comment by djgoldeneye** [comment]
i had this same issue. replaced by rotorvilllage. the replacement works better but still every so often i have a "sensor lost" message. im also having an issue where my quad falls out of the sky. Using Tx16 radio. Tried using my radiomaster R81 Rx didnt have an issue with that Rx. Except for very poor range and penetration.

Whenever the quad dies, theres a voltage drop, Could this be related.?
