### ISSUE TITLE
Lua script issue

### ISSUE THREAD

**Issue by N0v4v2** [ExpressLRS/ExpressLRS#926]
Hello everybody,
I'm introducing myself in expresslrs and I've successful connect and update my rx but when I tried to ran lua script on my taranis qx7 to wi-fi update, after selecting force use this is the message shown on display 
syntax error elrs.lua:250 attempt to compare number with nil

What's wrong?
How to solve this issue?

Thanks everybody for help!

- TX hardware: happy model 2.4ghz tx
- RX hardware:
- Handset model:
- OpenTX version (including nightly number)
- ExpressLRS version (TX & RX MUST MATCH):
- Packet Rate: 
- Telemetry Ratio:
- user_defines:

**Comment by pkendall64** [comment]
You haven't filled in any of the information that would help us fix your problem. And this is not a bug, you should ask in the help-and-support channel on discord.
