### ISSUE TITLE
Yappu CRSF Ardupilot support

### ISSUE THREAD

**Issue by RMFPV** [ExpressLRS/ExpressLRS#933]
Please add it!

More info here
https://discuss.ardupilot.org/t/passthrough-telemetry-over-crsf-crossfire/62668

*Instead of commenting "I want this too", consider leaving a :+1: instead, to reduce spam and clutter*

**Comment by schugabe** [comment]
I'm closing this issue because it is a duplicate of #650 
Please follow the other issue for more information on the topic
