### ISSUE TITLE
Happymodel ES900TX Power Cycles (reboots) continuously when set at 1W

### ISSUE THREAD

**Issue by alpine85** [ExpressLRS/ExpressLRS#940]
## Current Behavior

Happy model ES900TX Power Cycles (reboots) continuously when set at 1W
Fan hunts up and down, and telemetry warning sound as it reboots continuously after configuring 1W

## Steps to Reproduce

1. build and Install ELRS 1.1.0 - 915AU firmware on ES900TX/RX

2. Install EdgeTX 2.4.0 and ELRS Lua script

3. Configure 1W power output

## Details

password is elrs - these videos show the issue with the rebooting when set at 1w. and the behaviour, e.g unable to set back to 500mw once its rebooting.

1. https://itcsaust-my.sharepoint.com/:v:/g/personal/alpine_fullthrottle_id_au/EYWHdrIkjXtNk6XFUElvItIBwG2dcCluCLm_ChKqF0t-XQ?e=Ee3XCI
2. https://itcsaust-my.sharepoint.com/:v:/g/personal/alpine_fullthrottle_id_au/EYuBGVILPh9Fu8LezUbO_Y8BQOXscU4vDu8KeQ_VoxJdGg?e=qlG37v

 penetration testing, 1W at 50HZ
 

## Your Environment

- TX hardware: ES900TX
- RX hardware: ES900RX
- Handset model: RadioMaster TX16S
- OpenTX version (including nightly number) EdgeTX 2.4.0
- ExpressLRS version (TX & RX MUST MATCH): 1.1.0
- Packet Rate: 50HZ (issue observed with multiple packet rates)
- Output Power: 1W
- Telemetry Ratio: -
- user_defines: -

**Comment by token9** [comment]
i'm no expert but from the sound of that fan, it looks like the voltage is sagging as you set it to higher RF power.... you can hear it, when the voltage recovers, fan revs up, and the RF link comes back. 

Is your radio battery fully charged? Is there a way for you to monitor Tx module voltage to check for how low it sags, if at all?

**Comment by alpine85** [comment]
> i'm no expert but from the sound of that fan, it looks like the voltage is sagging as you set it to higher RF power.... you can hear it, when the voltage recovers, fan revs up, and the RF link comes back.
> 
> Is your radio battery fully charged? Is there a way for you to monitor Tx module voltage to check for how low it sags, if at all?

Hey Token9... I use tracer at 1w no issues, TX16S with 2 x Samsung 25R 18650 in batter bay, fully charged - it deff is rebooting as soon as i configure 1w and yes fan notisibly drops, but continues to change as its reboots, not sure if firmware issue or hadrware. have not tried downgrading firmware just yet, its new, just arrived, after settign up I ecountered this, after raising in discord was asked to open here for review. maybe if someone with same setup can confirm if ES900TX at 1W on firmware 1.1.0 is good or not?

**Comment by sohamsp14** [comment]
I faced the same issue. From what I can tell it's a board overheating issue. I disconnected the TX. Let it cool down. Then reconnected and it popped up and bound perfectly. Was able to bring down the power to 250mW again. 
But if I set it to 1W, this behavior repeats after the board heats up. I'm guessing the fan isn't able to cool down the module. 
PS: Should the fan blow air in or out? Mine blows out

**Comment by alpine85** [comment]
> I have an ES900TX and haven't run it at 1W for extended periods, but I can tell you that with the fan blowing in the temperature is about 10C cooler (tested with a FLIR camera with the lid on for 15 minutes in both orientations). I did not experience any reboots during the test though.
> 
> In any instance, this is not a bug in ExpressLRS, so if the hardware is overheating on you, consider upgrading your cooling solution or maybe don't run at 1W because why would you need 1W? There's also dynamic power in master branch that will cut the power when it isn't needed which might give you more longevity without changing the cooling.

fan blows in, the issue starts as soon as you set 1W, the heatsink is cool to touch, 1W is necessary for maximum penetration, I’m flying quad 10+k on mountain ridge and don’t want micro failsafe when flying close to or nearby obstacles.

**Comment by alpine85** [comment]
> The thermal cutoff is in hardware, there's nothing we can do to influence it. I can not reproduce at all. Maybe your heatsink isn't attached properly or the film under it is wrinkled or something? Try running it at 10mW and see if it reboots.

I am not having any issues with any power setting other than 1W. only 1W is rebooting (within 20 seconds of bootup as pere the videos) the heat sink and thermal film went on perfectly. the fan is noisy but effective. the heatsink is mildly warm not hot when it is continuously resetting. Set at 500mw 30mins on the bench and no reboot. im suspecting hardware fault, will try get a replacement given its not reproduceable (must be isolated issue).

**Comment by alpine85** [comment]
Thank you, yes, very unfortunate for me :) I have raised a support case with the bang, they are generally pretty good with support and warranty, so hopefully I am sent a replacement and can confirm soon that it was just hardware related. thanks again!
