### ISSUE TITLE
ES900RX binds only few times after flash + LQ drops

### ISSUE THREAD

**Issue by sohamsp14** [ExpressLRS/ExpressLRS#948]
I have been noticing a weird problem with my ES900TX. After I flash the receiver, it binds to the TX only 2-3 times and then it stops binding. I have to reflash again to get it to bind again. 
Also, there are continuous LQ drops with the radio being directly beside the RX (higher drops when far away). This is seen in the goggles as RXLOSS accompanied by micro failsafes with an eventual complete failsafe. (As happened in today's flight☹️)
The RX was working fine on the previous FW. I recently updated to 1.1.0 and this issue has been popping up. But my other receiver which is also on 1.1.0 seems to be working fine. 

Video of problem:
[Youtube Link](https://youtu.be/gjva3aevqq8)

RX Settings
![image](https://user-images.githubusercontent.com/83373078/135774290-e7cb7771-ae69-474d-8a51-4963fce97188.png)

TX Settings
![image](https://user-images.githubusercontent.com/83373078/135774300-085cbffa-dec4-42fb-8679-2d5fcb398649.png)

Your Environment

TX hardware: ES900TX
RX hardware: ES900RX
Handset model: RadioMaster TX16S
OpenTX version (including nightly number) EdgeTX 2.4.0
ExpressLRS version (TX & RX MUST MATCH): 1.1.0
Packet Rate: 200Hz
Output Power: 500mW (happens on all power levels)
Telemetry Ratio: - 1:32 (tried 1:16 and 1:64 as well)
user_defines: -

**Comment by deadbytefpv** [comment]
Can you flash the RX with the branch 1.1.x-maintenance, please?

**Comment by sohamsp14** [comment]
Did not work. Put in another receiver eventually and the LQ seems to be much better. >=97 at close range (although this should be 100 ideally). So probably a bad receiver? Will do a field test soon.

**Comment by sohamsp14** [comment]
Changing the receiver fixed the issue. My guess is it was a hardware problem. Closing
