### ISSUE TITLE
Send only the AUX channels that changed

### ISSUE THREAD

**Issue by skorokithakis** [ExpressLRS/ExpressLRS#963]
Currently, AUX channels are constantly sent in a round-robin manner. Maybe instead only the AUX channel that changed could be sent (since they only change a few times per flight). This would allow for a basically infinite number of channels, as long as they didn't all frequently change together.

The problem with this is that it would require some sort of ack from the telemetry, to verify that a change was received. If telemetry was lost, but not the RC link, the receiver would still see the change, so that wouldn't be as much of a problem (the transmitter would just keep sending it until an ACK). To prevent the queue for overflowing, maybe there could be an LRU cutoff, where if N changes are in the queue and sent in a round-robin manner, one more change would knock the oldest one out of the queue.

Since we can easily tell if a queued change is on the same channel, we could also replace that one with the new change and preserve queue space.

In general, this change would make latency be one packet in the vastly more common case of good telemetry and AUX changing rarely, and would still allow the system to work even with no telemetry.

What does everyone think?

**Comment by schugabe** [comment]
CRSF limits the number of channels to 16 so there is a hard limit for the amount of channels. We use 4 channels + 8 switch channels so this would only gain 4 more channels. With crsfv3 this limit is increasted but I think we only have three bits for the switch index and so we have a hard limited on the number of aux channels.

We always have to assume that the tlm from the rx back to the tx is the weakest point and bad things (TM) would happen if we designed a system only for best case assumptions.

**Comment by skorokithakis** [comment]
I agree if you have a fixed number of bits (for 8 channels you can just send one per packet all the time), but if you could somehow squeeze a few more bits in, you'd need a better way to send channels, as then they'd become too many to send every time...

A bit off topic, is there a packet diagram? It would help me understand the packet size and allowances better.
