### ISSUE TITLE
New Target Feichow RX24T

### ISSUE THREAD

**Issue by ballistRC** [ExpressLRS/ExpressLRS#965]
This RX has the same TX lineup as the BetaFPV 2.4 RX.  Tested with the BetaFPV profile in PIO.  All seems to work fine.  This RX seems to be sold under a number of different brandnames.

*Instead of commenting "I want this too", consider leaving a :+1: instead, to reduce spam and clutter*

**Comment by MicroMontis** [comment]
Don't judge the Chinese company by its website. JHEMCU is known by the lack of the social/website/email communication and the marketing is at the lower level. But the prices are good instead. Also the quality is good. Even the FPVCycle confirms it. 

Meanwhile show me the "Feichao" product, that is not manufactured by the other company. Do you know the BetaFPV LiteRadio2 ? Also manufactured by Feichao? (https://qwinout.com/products/2-4g-8ch-2-radio-literadio-transmitter-remote-controller-for-frsky-protocol-for-fpv-simulator-drone-quadcopter?_pos=10&_sid=f9b07e1ae&_ss=r)

**Comment by qubic** [comment]
I suggest adding feichao name to betafpv target

**Comment by MicroMontis** [comment]
Just to confirm the JHEMCU is the manufacturer and the 'Feichao' is just a simple rebrand, I've contacted the JHEMCU and got a reply:

![image](https://user-images.githubusercontent.com/15938741/136922703-9fceef5e-5dce-40c9-acba-a58612fa4ddc.png)

**Comment by howels** [comment]
> Just to confirm the JHEMCU is the manufacturer and the 'Feichao' is just a simple rebrand, I've contacted the JHEMCU and got a reply:
> 
> ![image](https://user-images.githubusercontent.com/15938741/136922703-9fceef5e-5dce-40c9-acba-a58612fa4ddc.png)

Sorry to distract from the original issue but I was looking at this board, are you sure that the JHEMCU GH743AIO is a 25x25mm board? Thanks!

**Comment by MicroMontis** [comment]
Yes, I'm sure. The gyro is rotated 45 deg. It's toothpick board.  The specs are copied from the previous 30x30mm board. They have not bothered to change the dimensions. I've also measured the board photos with the ruler by the reference jst-sh1.0 connector. Its 25x25mm, (+- 0.5mm) mount size.
Unfortunately all other resellers have copied the wrong specs. But this happens quite often. Asian manufacturers are rushing the products, their marketing deps are working like the floor is on lava and they usually don't bother fixing the mistakes. I would be very surprised if they fix the wrong specs in the listing on their website, despite they've promised to. :)

**Comment by howels** [comment]
> Yes, I'm sure. The gyro is rotated 45 deg. It's toothpick board. The specs are copied from the previous 30x30mm board. They have not bothered to change the dimensions. I've also measured the board photos with the ruler by the reference jst-sh1.0 connector. Its 25x25mm, (+- 0.5mm) mount size. Unfortunately all other resellers have copied the wrong specs. But this happens quite often. Asian manufacturers are rushing the products, their marketing deps are working like the floor is on lava and they usually don't bother fixing the mistakes. I would be very surprised if they fix the wrong specs in the listing on their website, despite they've promised to. :)

Thanks a lot for confirming. I was hoping it was the case. Appreciate your detective work to find this out. I had to write a Unified Target for the JHE F405 PRO board because it wasn't available.  JHEMCU hardware is great but getting software to work can be tricky!

**Comment by pkendall64** [comment]
These have been added as aliases in Configurator, closing.
