### ISSUE TITLE
Targets have multiple TX_DEVICE_NAMEs defined

### ISSUE THREAD

**Issue by CapnBry** [ExpressLRS/ExpressLRS#975]
On master, environments such as `HappyModel_ES24TX_2400_TX_via_UART` have multiple `TX_DEVICE_NAME` defines. This is because the base `DIY_2400_TX_ESP32_SX1280_E28_via_UART` defines a device name, and the device target extends that so it gets both.

The right way to fix this is to have a proper clean base that is extended by both DIY and the vendor-specific clones. Things that extend the DIY ESP32 TX (along with their wifi versions):
* HappyModel_ES24TX_2400_TX_via_UART
* HappyModel_ES24TX_Slim_Pro_2400_TX_via_UART
* HGLRC_Hermes_2400_TX_via_UART
* QuadKopters_JR_2400_TX_via_UART

The other 2400 and 900 TXes should be examined to determine if they have a similar issue, and the RX should probably be fixed too since those will likely get device names as well at some point and we'll have to go through this again.

**Comment by pkendall64** [comment]
I've noticed this too. I have another PR almost ready to go that build on the power management cleanup that pulls all the hardware specific defines for targets out of `targets.h` and into seperate header files which are included in the .ini files. This will make adding a new target very simple in future.
