### ISSUE TITLE
Changing the settings while the Lua script is loading leads to failsafes and radio emergency mode

### ISSUE THREAD

**Issue by skorokithakis** [ExpressLRS/ExpressLRS#986]
## Current Behavior

If you change a setting, and then change it again while the Lua script is in a "Loading..." state, the craft will start failsafing at best, the radio will go into emergency mode at worst. This goes away with a restart of the radio.

## Steps to Reproduce

1. Change a setting.
2. While it's loading, quickly change it again.
3. Failsafe/emergency mode.

## Your Environment

- TX hardware: Happymodel ELRS 2.4 TX
- RX hardware: Happymodel ELRS 2.4 RX
- Handset model: RadioMaster TX16S
- OpenTX version (including nightly number): 2.3.11-otx (4328055e)
- ExpressLRS version (TX & RX MUST MATCH): master d318f1
- Packet Rate: 50
- Telemetry Ratio: 1:16
- user_defines: Unsure

**Comment by CapnBry** [comment]
Try the latest master, this will likely be fixed by this:
https://github.com/ExpressLRS/ExpressLRS/pull/972

**Comment by skorokithakis** [comment]
I'll try it and report back,thanks.
