### ISSUE TITLE
Failure to connect EP1 to TX16s (ES24TX)

### ISSUE THREAD

**Issue by Wedwards1** [ExpressLRS/ExpressLRS#990]
When plugging in the battery to my quad SucceX-E F7 flight controller. the module will not connect no matter what, if I unplug the battery and plug it back in after roughly 1 second it connects instantly. This occurs every time the quad is powered up.

**Comment by deadbytefpv** [comment]
Try flashing it with 1.1x-maintenance

**Comment by Wedwards1** [comment]
fixed the issue, thanks
